### ISSUE TITLE
Bug: Error in Otel Collector if pipelines are disabled?

### ISSUE THREAD

**Issue by only-a-user** [open-telemetry/opentelemetry-helm-charts#1003]
When disabling the `metrics` and `logs` pipelines in `config.service.pipelines` as described in the [README.md][1] for the otel collector, I get an error, which occurs in line 36 of the [templates/NOTES.txt][2]:

```Go
{{- if .Values.configMap.create }}
{{- range $key, $value := (((.Values.config).service).pipelines) }}
{{- if has "logging" ($value.exporters) }}
[WARNING] The logging exporter is deprecated.  Use the debug exporter instead.
{{- end }}
{{- end }}
{{- end }}
```

This is because the `$value.exporters` can not be reached, if the corresponding pipeline is disabled like this:

```yaml
config:
  ...
  service:
    ...
    pipelines:
      logs: null
      metrics: null
      traces:
        exporters:
          - debug
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - jaeger
```

A workaround is to add `{{- if $value }}` before the call of `$value.exporters`, but I don't know, if that is a bug, or intended behaviour and I'm doing something wrong?

[1]: https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector#basic-top-level-configuration
[2]: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/templates/NOTES.txt

**Comment by TylerHelmuth** [comment]
@Only-a-User I was not able to reproduce this issue.  With the latest version of the chart and this values.yaml, everything is rendered as expected:

```yaml
mode: daemonset

config:
  service:
    pipelines:
      metrics: null
      logs: null
      traces:
        exporters:
          - debug
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - jaeger
```

What version of helm are you using?  What version of the chart are you using?
