### ISSUE TITLE
How to access the telemetry file the in the Otel collector?

### ISSUE THREAD

**Issue by yinfangchen** [open-telemetry/opentelemetry-helm-charts#1041]
After using helm to deploy my otel-collector in my Kind cluster, I want to export the telemetry into a file in `/tmp/otel_output.json` like this:
```
config:
  exporters:
    debug: {}
    file:
      path: /tmp/otel_output.json
  service:
    pipelines:
      traces:
        receivers: 
          - otlp
        exporters:
          - debug
          - file
      logs:
        receivers: 
          - otlp
        exporters: 
          - debug
          - file
      metrics:
        receivers: 
          - otlp
        exporters: 
          - debug
          - file
```

I have created a PVC (PersistentVolumeClaim) used by the collector:
```
extraVolumes:
  - name: otel-data
    persistentVolumeClaim:
      claimName: otel-output-pvc

extraVolumeMounts:
  - name: otel-data
    mountPath: /tmp
```
but I don't know how to access the telemetry output file (i.e., `/tmp/otel_output.json` in my case). 

I have tried to use `kubectl cp` to copy the file from the pod to my local workstation, but I got:
`OCI runtime exec failed: exec failed: unable to start container process: exec: "tar": executable file not found in $PATH: unknown`

I have also tried to use `kubectl exec` with `cat` but the `cat` is also not there.

I have also tried to ssh into the pod but did not succeed. 

Any ideas on how to address this? Do I need to build a custom image myself with those utilities?
