### ISSUE TITLE
Question: How to use environment variables linked to secrets using the operator?

### ISSUE THREAD

**Issue by sicil1ano** [open-telemetry/opentelemetry-helm-charts#1043]
Hi.

I'm using Terraform to deploy OpenTelemetry Operator using its Helm chart 0.47.0.
Afterwards, I'm deploying OpenTelemetry using a sidecar container for my microservices and a collector to centralise the logs/traces collection from the sidecars.
I configured the collector to send data to Grafana Cloud using its OTLP endpoint URL, API token and instance ID. Everything works, except when I'm configuring the collector to get that sensitive information (URL, token and instance ID) from environment variables linked to secrets.
Here's my deployment chart:

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: "{{ include "opentelemetry.fullname" . }}-gateway"
spec:
  mode: deployment 
  nodeSelector:
    kubernetes.io/os: "linux"
  config: |
    {{- if .Values.grafanaCloudExporterEnabled }}
    extensions:
      basicauth/otlp:
        client_auth:
          username: $OTLP_COLLECTOR_GRAFANACLOUD_INSTANCE_ID
          password: $OTLP_COLLECTOR_GRAFANACLOUD_API_TOKEN
    {{- end }}

    receivers:
      otlp:
        protocols: 
          grpc:
          
    processors:
      {{ toYaml .Values.gateway.processors | nindent 6 }}

    exporters:
      {{- if .Values.grafanaCloudExporterEnabled }}
      otlphttp:
        auth:
          authenticator: basicauth/otlp
        endpoint: $OTLP_COLLECTOR_GRAFANACLOUD_ENDPOINT
      {{- end }}
      logging:
        loglevel: info
      {{- with .Values.jaegerCollectorSvcName }}
      otlp/jaeger:
        endpoint: '{{ . }}.default.svc:4317'
        tls:
          insecure: true
      {{- end }}

    service:
      {{- if .Values.grafanaCloudExporterEnabled }}
      extensions: [basicauth/otlp]
      {{- end }}
      telemetry:
        metrics:
          address: 0.0.0.0:8888
      pipelines:
        logs:
          exporters:
            - logging
            {{- if .Values.grafanaCloudExporterEnabled }}
            - otlphttp
            {{- end }}
          processors: [memory_limiter]
          receivers:
            - otlp
        metrics:
          exporters:
            - logging
            {{- if .Values.grafanaCloudExporterEnabled }}
            - otlphttp
            {{- end }}
          processors: [memory_limiter]
          receivers:
            - otlp
        traces:
          exporters:
            - logging
            {{- if .Values.grafanaCloudExporterEnabled }}
            - otlphttp
            {{- end }}
            {{- if .Values.jaegerCollectorSvcName }}
            - otlp/jaeger
            {{- end }}
          processors: [memory_limiter]
          receivers:
            - otlp
```

and here's `values.yaml`, configured accordingly with extraEnvsFrom, which, according to source code, should add environment variables coming from a Secret for the container:

```
jaegerCollectorSvcName: null

grafanaCloudExporterEnabled: false

agent:
  processors:
    memory_limiter:
      check_interval: 5s
      limit_mib: 200
      spike_limit_mib: 25
  resources:
    limits:
      cpu: 20m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi

gateway:
  processors:
    memory_limiter:
      check_interval: 5s
      limit_mib: 2000
      spike_limit_mib: 250

  environmentVariables :
  - name: OTLP_COLLECTOR_GRAFANACLOUD_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: grafana-cloud-otlp-endpoint-url-secret
        key: url
  - name: OTLP_COLLECTOR_GRAFANACLOUD_INSTANCE_ID
    valueFrom:
      secretKeyRef:
        name: grafana-cloud-otlp-endpoint-auth-secret
        key: username
  - name: OTLP_COLLECTOR_GRAFANACLOUD_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: grafana-cloud-otlp-endpoint-auth-secret
        key: password
```

Here's how I create the secrets:

```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-otlp-endpoint-url-secret
type: Opaque
stringData:
  url: {{ quote .Values.grafanaCloudOtlpEndPointSecret.url }}
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-otlp-endpoint-auth-secret
type: kubernetes.io/basic-auth
stringData:
  username: {{ quote .Values.grafanaCloudOtlpEndpointAuthSecret.instanceId }}
  password: {{ quote .Values.grafanaCloudOtlpEndpointAuthSecret.apiToken }}
```

When I describe the pod, none of the environment variables I'm using are part of the deployment. The pod will then crash because the environment variables don't exist and values are empty. The secrets are correctly created. 
I changed approach using extraEnvs block in values.yaml, passing the hard-coded info as a test, but it didn't work either.

Is this how am I supposed to use environment variables linked to secrets? Why does this setup do not work?

**Comment by TylerHelmuth** [comment]
@sicil1ano the opentelemetry chart that lives in this repo cannot make an OpenTelemetryCollector object.  What helm chart does your `values.yaml` apply to?

**Comment by sicil1ano** [comment]
Hi @TylerHelmuth. Yes, I had some confusion about the charts creating the OpenTelemetryCollector object.

I inherited this from a previous team member who wrote all of this. This morning I figured out that values.yaml is applied to a chart linked OpenTelemetry Operator. I followed the specification (https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollector) in the OpenTelemetryCollector deployment chart: 

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: "{{ include "opentelemetry.fullname" . }}-gateway"
# This spec section follows the specifications for OpenTelemetryCollector described here: https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollector
spec:
  mode: deployment 
  nodeSelector:
    kubernetes.io/os: "linux"
  {{- if .Values.grafanaCloudExporterEnabled }}
  env: {{ toYaml .Values.gateway.environmentVariables | nindent 6 }}
  {{- end }}
  config: |
    {{- if .Values.grafanaCloudExporterEnabled }}
    extensions:
      basicauth/otlp:
        client_auth:
          username: $OTLP_COLLECTOR_GRAFANACLOUD_INSTANCE_ID
          password: $OTLP_COLLECTOR_GRAFANACLOUD_API_TOKEN
    {{- end }}

    receivers:
      otlp:
        protocols: 
          grpc:
          
    processors:
      {{ toYaml .Values.gateway.processors | nindent 6 }}

    exporters:
      {{- if .Values.grafanaCloudExporterEnabled }}
      otlphttp:
        auth:
          authenticator: basicauth/otlp
        endpoint: $OTLP_COLLECTOR_GRAFANACLOUD_ENDPOINT
      {{- end }}
      logging:
        loglevel: info
      {{- with .Values.jaegerCollectorSvcName }}
      otlp/jaeger:
        endpoint: '{{ . }}.default.svc:4317'
        tls:
          insecure: true
      {{- end }}

    service:
      {{- if .Values.grafanaCloudExporterEnabled }}
      extensions: [basicauth/otlp]
      {{- end }}
      telemetry:
        metrics:
          address: 0.0.0.0:8888
      pipelines:
        logs:
          exporters:
            - logging
            {{- if .Values.grafanaCloudExporterEnabled }}
            - otlphttp
            {{- end }}
          processors: [memory_limiter]
          receivers:
            - otlp
        metrics:
          exporters:
            - logging
            {{- if .Values.grafanaCloudExporterEnabled }}
            - otlphttp
            {{- end }}
          processors: [memory_limiter]
          receivers:
            - otlp
        traces:
          exporters:
            - logging
            {{- if .Values.grafanaCloudExporterEnabled }}
            - otlphttp
            {{- end }}
            {{- if .Values.jaegerCollectorSvcName }}
            - otlp/jaeger
            {{- end }}
          processors: [memory_limiter]
          receivers:
            - otlp

```

I solved my problem. Thanks for the support.
