### ISSUE TITLE
[opentelemetry-collector] StatefulSets do not delete PVCs when scaled or deleted

### ISSUE THREAD

**Issue by lindeskar** [open-telemetry/opentelemetry-helm-charts#1056]
When creating PVCs through the OTelCol StatefulSet the PVCs are not removed on scale-down or when the StatefulSet is deleted.

This behaviour could be changed by adding `.spec.persistentVolumeClaimRetentionPolicy`.

More information here: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention

**Comment by lindeskar** [comment]
#1057 will allow setting the values:

```yaml
statefulset:
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenDeleted: Delete
    whenScaled: Delete
```

which resolves this issue.
