### ISSUE TITLE
OpenTelemetry Operator Helm Chart Automatically Generated Self-Signed Certificate Documentation

### ISSUE THREAD

**Issue by igooch** [open-telemetry/opentelemetry-helm-charts#1088]
As of version 0.50.0 the below helm command in the [charts/opentelemetry-operator/README.md](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-operator#readme) no longer works and gives an error:

```
helm install  --set admissionWebhooks.certManager.enabled=false --set admissionWebhooks.certManager.autoGenerateCert=true \
  opentelemetry-operator open-telemetry/opentelemetry-operator
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-operator:
- admissionWebhooks.certManager: Additional property autoGenerateCert is not allowed
```

This command works with version 0.49.1.

This looks like an explicit choice to remove the additional properties field in 5712c12. 

Adding the below values.yaml file also works:

```
admissionWebhooks:
  # Disables certManager
  certManager:
    enabled: false
  # Helm will create a self-signed cert and secret
  autoGenerateCert:
    enabled: true
```

I see that the default is set to true https://github.com/open-telemetry/opentelemetry-helm-charts/blob/5712c1281923abbe313b2b49bc0015d64d420cac/charts/opentelemetry-operator/values.yaml#L222-L226

Is there an updated inline command for creating an automatically generated self-signed certificate? Or is `helm install  --set admissionWebhooks.certManager.enabled=false \
  opentelemetry-operator open-telemetry/opentelemetry-operator` the new preferred way?
