### ISSUE TITLE
[opentelemetry-collector] Add conditional to override mounting ConfigMap

### ISSUE THREAD

**Issue by chunter0** [open-telemetry/opentelemetry-helm-charts#1124]
Hi all,

Sample from templates below show current requirements to have configuration mounted using the well defined naming schema needs `configMap.create` to be set to true.

```
    volumeMounts:
      {{- if .Values.configMap.create }}
      - mountPath: /conf
        name: {{ include "opentelemetry-collector.lowercase_chartname" . }}-configmap
      {{- end }}
volumes:
  {{- if .Values.configMap.create }}
  - name: {{ include "opentelemetry-collector.lowercase_chartname" . }}-configmap
    configMap:
      name: {{ include "opentelemetry-collector.fullname" . }}{{ .configmapSuffix }}
      items:
        - key: relay
          path: relay.yaml
  {{- end }}
```

In the scenario where opentelemetry-collector is deployed as a subchart with a custom configuration, users will need to specify the name of the custom configuration using the `extraVolumes` and `extraVolumeMounts` fields. This process can be streamlined by enabling conditional override capability.

For instance, we can enable override via `configMap.mount` and couple it with `configMap.create` using an OR condition. This approach will facilitate mounting the configuration using the existing naming convention if:

  - configMap.create is set to true
  - configMap.mount is set to true
  - both options set to true

#### Potential Solution
```
    volumeMounts:
      {{- if or .Values.configMap.create .Values.configMap.mount }}
      - mountPath: /conf
        name: {{ include "opentelemetry-collector.lowercase_chartname" . }}-configmap
      {{- end }}
volumes:
  {{- if or .Values.configMap.create .Values.configMap.mount }}
  - name: {{ include "opentelemetry-collector.lowercase_chartname" . }}-configmap
    configMap:
      name: {{ include "opentelemetry-collector.fullname" . }}{{ .configmapSuffix }}
      items:
        - key: relay
          path: relay.yaml
  {{- end }}
```

**Comment by TylerHelmuth** [comment]
@chunter0 What's confusing to me is that the name of the confmap/mount isn't change based on whether "create" or "mount" is used. When would a user use "mount" instead of "create"? It seems they do the same thing. 

Can you provide a subchart example where this feature would be used?

**Comment by chunter0** [comment]
Mount isn't coupled with creation of the ConfigMap because as a user we would like to own the template in the parent chart for ConfigMap creation.

### Current

As a user we're currently using the naming schema and have to get the ConfigMap mounted using extraVolumes. This is sub-optimal because this has to be specified in the parent chart and the data type is an array. If a user of the parent wants to specify another volume they will have to pass in their volumes as well as the parent chart defaults.

Parent Chart
```
apiVersion: v2
dependencies:
- alias: telemetryCollector
  condition: telemetryCollector.enabled
  name: opentelemetry-collector
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.74.0
name: parent
```

This example is how the parent mounts the config under the well known naming schema
```yaml
extraVolumes:
- name: telemetry-configmap
  configMap:
    name: {{ telemetryCollector.fullnameOverride }}-config
    items:
      - key: relay
        path: relay.yaml
```

Another example if a user of the parent chart wants to add another volume, as we can see from the values below they would need to redefine the entire `extraVolumes` field to avoid removing the parent chart ConfigMap

```
extraVolumes:
- name: telemetry-configmap
  configMap:
    name: {{ telemetryCollector.fullnameOverride }}-config
    items:
      - key: relay
        path: relay.yaml
- name: user-defined
```

@TylerHelmuth

**Comment by TylerHelmuth** [comment]
So this is a situation when using the chart as a subchart AND supplying your own configuration file with the same name as the one the collector would have created? So instead of 

```yaml
configMap:
  create: false
extraVolumes:
- name: telemetry-configmap
  configMap:
    name: {{ telemetryCollector.fullnameOverride }}-config
    items:
      - key: relay
        path: relay.yaml
```

you'd do 

```yaml
configMap:
  create: false
  mount: true
```
