### ISSUE TITLE
Collector CRD 0.99.0 requires templated conversion webhook

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-helm-charts#1167]
Created from https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1164 

The conversion webhook defined in the collector CRD should be templated because it references the operator webhook service which can be dynamically set:

```bash
helm install --namespace=my-opentelemetry-operator-system --create-namespace my-opentelemetry-operator ./charts/opentelemetry-operator
```

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: opentelemetry-operator-system/opentelemetry-operator-serving-cert
    controller-gen.kubebuilder.io/version: v0.14.0
  name: opentelemetrycollectors.opentelemetry.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: {missing my-}opentelemetry-operator-webhook
          namespace: {missing my}opentelemetry-operator-system
          path: /convert
      conversionReviewVersions:
      - v1alpha1
      - v1beta1
```
