### ISSUE TITLE
binding pod IP to otlp grpc receiver does not work

### ISSUE THREAD

**Issue by iamKunal** [open-telemetry/opentelemetry-helm-charts#1171]
Using the out-of-the-box configuration to use the grpc protocol with otlp receiver leads to a connection refused on the service end when doing a port-forward

What fixed it was using 0.0.0.0 as the grpc endpoint in the receiver:
```yaml
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
```
