### ISSUE TITLE
[operator] service "opentelemetry-operator-webhook" not found

### ISSUE THREAD

**Issue by davgia** [open-telemetry/opentelemetry-helm-charts#1199]
Hi everyone, I have disabled the webhook as suggested by the documentation. The helm chart installation completes successfully without errors but I do not see pods created after I apply the collector definition. Moreover when I try to list opentelemetrycollector resources from kubectl I receive the following error:

``` log
kubectl get opentelemetrycollector --all-namespaces
Warning: OpenTelemetryCollector v1alpha1 is deprecated. Migrate to v1beta1.
Error from server: conversion webhook for opentelemetry.io/v1beta1, Kind=OpenTelemetryCollector failed: Post "https://opentelemetry-operator-webhook.monitoring.svc:443/convert?timeout=30s": service "opentelemetry-operator-webhook" not found
```

Helm chart:

``` yaml
# helm upgrade --install opentelemetry-operator open-telemetry/opentelemetry-operator --version "0.60.0" -f .\values.yaml -n monitoring
manager:
  collectorImage:
    repository: "otel/opentelemetry-collector-k8s"
  # disable webhooks
  env:
    ENABLE_WEBHOOKS: "false"
  # resources configuration
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 5m
      memory: 32Mi
# disable admission webhooks
admissionWebhooks:
  create: false
```

Collector definition:

``` yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: "${kubernetes_namespace_v1.environment.id}"
spec:
  mode: deployment
  config:
    receivers:
      jaeger:
        protocols:
          grpc: {}
          thrift_http: {}
          thrift_compact: {}
      otlp:
        protocols:
          grpc: {}
          http: {}
      zipkin: {}
    extensions:
      health_check: {}
      pprof: {}
      zpages: {}
    processors:
      batch: {}
    exporters:
      otlp:
        endpoint: tempo.monitoring:4317
        tls:
          insecure: true
    service:
      extensions:
        - health_check
        - pprof
        - zpages
      pipelines:
        traces:
          receivers:
            - otlp
            - jaeger
            - zipkin
          processors:
            - batch
          exporters:
            - otlp
```
Can someone help me to pinpoint the error or the misconfiguration?

Thanks in advance
