### ISSUE TITLE
We are facing Error scraping metrics  tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by shbasha-clgx** [open-telemetry/opentelemetry-helm-charts#1247]
Hi Team,
We are trying to install otel collector using helm and trying to get the kubernetesAttributes:
    enabled: true
  kubeletMetrics:
    enabled: true
  hostMetrics:
    enabled: true
  logsCollection:
    enabled: true
    includeCollectorLogs:

configuration added in values.yaml how ever we are facing below error , attached file for your reference.

Kindly look into this and please assist

error   scraperhelper/scrapercontroller.go:197  Error scraping metrics  {"kind": "receiver", "name": "kubeletstats", "data_type": "metrics", "error": "Get \"
[https://xxxxxx:xxxx/stats/summary\":]
tls: failed to verify certificate: x509: certificate signed by unknown authority", "scraper": "kubeletstats"}

we do not have self signed cert and need assistance on how to bypass this.

**Comment by shbasha-clgx** [comment]
@dmitryax Hi , can someone assist on this issue please

**Comment by shbasha-clgx** [comment]
@dmitryax Hi did anyone got a chance to go through the issue, we still see the same issue

**Comment by shbasha-clgx** [comment]
> you can try enabling preset and also providing receiver config:
> 
> ```
> receivers:
>   kubeletstats:
>     insecure_skip_verify: true
> ```
> 
> Check this discussion around tls issues - #1034

@povilasv Thank you for your response
after adding 
receivers:
>   kubeletstats:
>     insecure_skip_verify: true

we not seeing the tls error now but we are not able to get the cluster metrics in the otel collector logs although as exporter we put debug , below the values.yaml file we are using.


mode: daemonset

presets:
  kubernetesAttributes:
    enabled: true
  kubeletMetrics:
    enabled: true
  hostMetrics:
    enabled: true
  logsCollection:
    enabled: true
    includeCollectorLogs: true

config:
  exporters:
    debug: {}  # Enable OTLP HTTP exporter
  service:
    pipelines:
      logs:
        exporters:
          - debug
  receivers:
    kubeletstats:
      insecure_skip_verify: true

nodeSelector:
  kubernetes.io/hostname: xxxxxx
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    effect: "NoSchedule"

**Comment by shbasha-clgx** [comment]
@povilasv 

Thank you for your response
after adding 
receivers:
>   kubeletstats:
>     insecure_skip_verify: true

we not seeing the tls error now but we are not able to get the cluster metrics in the otel collector logs although as exporter we put debug , below the values.yaml file we are using.


mode: daemonset

presets:
  kubernetesAttributes:
    enabled: true
  kubeletMetrics:
    enabled: true
  hostMetrics:
    enabled: true
  logsCollection:
    enabled: true
    includeCollectorLogs: true

config:
  exporters:
    debug: {}  # Enable OTLP HTTP exporter
  service:
    pipelines:
      logs:
        exporters:
          - debug
  receivers:
    kubeletstats:
      insecure_skip_verify: true

nodeSelector:
  kubernetes.io/hostname: xxxxxx
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    effect: "NoSchedule"

**Comment by shbasha-clgx** [comment]
@povilasv Hi , did you get a chance to look into this issue , can you please assist.

**Comment by bixu** [comment]
>  below the values.yaml file we are using.

@shbasha-clgx, it'll help the community debug your issue if you paste formatted YAML.

You can do that by surrounding your YAML blocks with triple backticks, or selecting the YAML you've pasted and then clicking on the `<>` in the comment editor.

**Comment by D13410N3** [comment]
The same issue. How to deal with it?

**Comment by dmitryax** [comment]
@shbasha-clgx @D13410N3  Please post helm chart config (values.yaml), collector logs output, and k8s environment details (managed k8s? what version? etc.). I'd help reproduce and potentially fix the problem

**Comment by cardoner1993** [comment]
Hi we are using the opentelemetry-operator version 0.78.0.
Using self signed certificate after some hours of activity we get the following error: 
Failed to load live state: conversion webhook for opentelemetry.io/v1beta1, Kind=OpenTelemetryCollector failed: Post "https://otel-opentelemetry-operator-webhook.tools.svc:443/convert?timeout=30s": tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "opentelemetry-operator-operator-ca")

Our values yaml is as follows:
```yaml
opentelemetry-operator:
  manager:
    collectorImage:
      repository: otel/opentelemetry-collector-k8s
  admissionWebhooks:
    certManager:
      enabled: false
    autoGenerateCert:
      enabled: true
```

Then:
ca-clusterissuer.yaml
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: root-secret
```
selfsigned-ca-certificate.yaml
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
  namespace: tools
spec:
  isCA: true
  commonName: selfsigned-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
```
selfsigned-clusterissuer.yaml
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
```
We started by allowing cert manager to create and sign the certificate as the documentation recommends but the same error was appearing immediately.

Thanks in advice.
