### ISSUE TITLE
[opentelemetry-kube-stack] Inconsistent TargetAllocator Schema

### ISSUE THREAD

**Issue by sergeybataev** [open-telemetry/opentelemetry-helm-charts#1250]
I found inconsistencies between the stack `values.schema.json` and the CRD. When attempting to add the following lines into charts/opentelemetry-kube-stack/examples/cloud-demo:
```
  targetAllocator:
    image: ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:main
    enabled: true
    prometheusCR:
      enabled: true
      serviceMonitorSelector:
        matchLabels:
          app: my-app
```

the `make generate-examples` command raised the following errors:
```
Generating example: cloud-demo
Error: values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-kube-stack:
- collectors.defaultCRConfig.targetAllocator.image: Invalid type. Expected: object, given: string
- collectors.defaultCRConfig.targetAllocator.prometheusCR.serviceMonitorSelector.matchLabels: Invalid type. Expected: string, given: object
```

Additionally, the line `"$id": "https://github.com/open-telemetry/opentelemetry-operator/apis/v1alpha1/open-telemetry-collector-spec"`, in `values.schema.json` seems irrelevant. The stack generates apiVersion: opentelemetry.io/v1beta1 and the file in the provided URL does not exist.
