### ISSUE TITLE
Support for hostPort Configuration in opentelemetry-kube-stack Chart

### ISSUE THREAD

**Issue by hmsayem** [open-telemetry/opentelemetry-helm-charts#1278]
I am attempting to configure the `hostPort` for the daemon collector using the `opentelemetry-kube-stack` Helm chart, but it seems that the schema does not currently support the `hostPort` property in the ports configuration.

###  Issue Description

When setting the `hostPort` for the daemon in the ports section as follows:

```yaml
collectors:
  daemon:
    ports:
    - appProtocol: grpc
      name: otlp-grpc
      port: 4317
      protocol: TCP
      hostPort: 4317
    - appProtocol: http
      name: otlp-http
      port: 4318
      protocol: TCP
      hostPort: 4318
```

I receive the following error with helm install:

```
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-kube-stack:
- collectors.daemon.ports.0: Additional property hostPort is not allowed
- collectors.daemon.ports.1: Additional property hostPort is not allowed
```

### Steps to Reproduce:
Modify the `values.yaml` for the `opentelemetry-kube-stack` chart to include `hostPort` under the `daemon.ports` configuration.
Try installing the chart using Helm.

### Additional Context:

It would be helpful to have this configuration option available to ensure that instrumented applications can send telemetry data to agents running on the same node.
