### ISSUE TITLE
[collector] Enable node metrics for the kubeletMetrics preset

### ISSUE THREAD

**Issue by rogercoll** [open-telemetry/opentelemetry-helm-charts#1283]
Configure the [Kubelet node metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kubeletstatsreceiver#collect-k8scontainerpodcpumemorynodeutilization-as-ratio-of-total-nodes-capacity) when the `kubeletMetrics` preset is enabled. The main reason about this addition is that node metrics require additional K8s api permissions to be added into the service account, thus just modifying the `kubeletstats` receiver configuration won't work.

Permissions error:

```
2024-07-30T15:20:00.952Z        error   kubeletstatsreceiver@v0.105.0/scraper.go:113    call to /pods endpoint failed       {"kind": "receiver", "name": "kubeletstats", "data_type": "metrics", "error": "kubelet request GET https://gke-otel-default-pool-6a2b7a08-ldsm:10250/pods failed - \"403 Forbidden\", response: \"Forbidden (user=system:serviceaccount:default:otel-daemonset-otel-opentelemetry-collector, verb=get, resource=nodes, subresource=proxy)\""}
```

If preferred, we could just add the additional permission rules for the `daemonset` mode + `kubeletMetrics`

cc @ChrsMark

**Comment by TylerHelmuth** [comment]
Typically the presets dont configure for non-default metrics. To use the preset and enable those optional metrics you'd do:

```yaml
presets:
  kubeletMetrics:
    enabled: true

config:
  receivers:
    kubeletstats:
      node: '${env:K8S_NODE_NAME}'
      metrics:
        k8s.container.cpu.node.utilization:
          enabled: true
        k8s.pod.cpu.node.utilization:
          enabled: true
        k8s.container.memory.node.utilization:
          enabled: true
        k8s.pod.memory.node.utilization:
          enabled: true
          
clusterRole:
  create: true
  rules:
    - apiGroups: 
        - ""
      resources:
        - nodes/proxy
      verbs:
        - get
```
