### ISSUE TITLE
webhook "mopentelemetrycollectorbeta.kb.io": failed to call webhook

### ISSUE THREAD

**Issue by Ituninant** [open-telemetry/opentelemetry-helm-charts#1295]
Hi!

I have this setup:

```shell
kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml
``` 

then try to apply that config:

```
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: spring-app
spec:
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      otlp:
        endpoint: http://host.minikube.internal:4317
        tls:
          insecure: true
      prometheus:
        endpoint: 0.0.0.0:8889
      elasticsearch:
        endpoints: [ "http://host.minikube.internal:9200" ]
        logs_index: "otel-collector"
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ prometheus ]
``` 

And get that error on applying:
`Error from server (InternalError): error when creating "/Users/ait/IdeaProjects/kubernetes/config/otel-operator/collector.yaml": Internal error occurred: failed calling webhook "mopentelemetrycollectorbeta.kb.io": failed to call webhook: Post "https://opentelemetry-operator-webhook-service.opentelemetry-operator-system.svc:443/mutate-opentelemetry-io-v1beta1-opentelemetrycollector?timeout=10s": dial tcp 10.96.11.36:443: connect: connection refused
`
