### ISSUE TITLE
Logs support using FluentBit 

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-helm-charts#13]
I have researched the possibility of using a common [Fluent Bit Helm Chart](https://github.com/fluent/helm-charts/tree/master/charts/fluent-bit) for log collection on K8s (as a DaemonSet), passing them through OpenTelemetry Collector and getting K8s metadata tagged.

The details are available in this document: https://docs.google.com/document/d/1QlFbXz0eQUaKXK1WrnEs3VqRkcPD2RAdXJdJMjnOSd8/edit#

There are several issues that need to be solved first, before metadata tagging will be available: https://github.com/open-telemetry/opentelemetry-collector/issues/1884,  https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1146 and https://github.com/open-telemetry/opentelemetry-collector/issues/1652

Also, the fields such as `pod_uid` need to be separately converted into semantic-conventions compatible one, like `k8s.pod.uid` (it's not possible to use such capture group name, but another process can change the attribute name).

Having said of all that, it's plausible to setup an optional pipeline for log collection as part of the Helm Chart. Either taking the Fluent Bit Helm Chart as a dependency or via a similar approach

Fluent Bit config for retrieving logs using the CRI log path format (as suggested by @dashpole) and exporting to OpenTelemetry Collector:
```
    [INPUT]
        Name tail
        Path /var/log/pods/*/*/*.log
        Parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [OUTPUT]
        Name forward
        Match kube.*
        Host <OPENTELEMETRY_COLLECTOR_HOST>
        Port <OPENTELEMETRY_COLLECTOR_FLUENT_FORWARDER_PORT>
```

The attribute extraction from Fluent Bit tag can be done using following processor:
```
    processors:
      attributes:
        actions:
          - key: fluent.tag
            action: extract      
            pattern: ^kube\.var\.log\.pods\.(?P<namespace_name>[^_]+)_(?P<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:[a-z0-9](?:[-a-z0-9]*[a-z0-9])?)*)_(?P<pod_uid>[-a-z0-9]+).(?P<container_name>.+)\.(?P<restarts>[0-9]+)\.log$
```
