### ISSUE TITLE
Different in size of data volume in ServiceNow Cloud Observability and Azure Application Insight logs from OTel Collector chart

### ISSUE THREAD

**Issue by sahanruwanga** [open-telemetry/opentelemetry-helm-charts#1319]
### Description

I'm using [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector) helm chart in an AKS cluster to receive and export logs, metrics, and traces from AKS workloads. There are two exporters. One is an Azure Application Insight resource and the other one is Service Now Cloud Observability(lightstep).

Even though I expect that I will have same data(volume) in both Azure Application Insight and Service Now Cloud Observability, I can see 3~4 times data volume in Azure Application Insight compared to what I see in SN cloud observability. I'm trying to understand the reason for this difference. Can it be depended on the platform/service that I config as exporter endpoints and how/what they handle/store data? Any supportive answer would be highly appreciated. 

[opentelemetry-helm-charts](https://github.com/open-telemetry/opentelemetry-helm-charts) version: `0.93.3`

Following is the related configuration in my `open-telemetry-opentelemetry-collector-agent` config map in AKS.
```
exporters:
      azuremonitor/appi:
        connection_string: <value>
      otlp/cloud-obs:
        endpoint: ingest.lightstep.com:443
        headers:
          lightstep-access-token: <value>

receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

service:
      pipelines:
        logs:
          exporters:
          - azuremonitor/appi
          - otlp/cloud-obs
          receivers:
          - otlp
        metrics:
          exporters:
          - azuremonitor/appi
          - otlp/cloud-obs
          receivers:
          - otlp
        traces:
          exporters:
          - azuremonitor/appi
          - otlp/cloud-ob
          receivers:
          - otlp
```
