### ISSUE TITLE
Additional property is not allowed

### ISSUE THREAD

**Issue by mk-raven** [open-telemetry/opentelemetry-helm-charts#1322]
helm upgrade -i otel-demo open-telemetry/opentelemetry-demo -f custom-values.yaml --create-namespace  --version  0.32.6
```
helm.go:84: [debug] values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-demo:
- (root): Additional property extraVolumes is not allowed
- (root): Additional property namespaceOverride is not allowed
- (root): Additional property configMap is not allowed
- (root): Additional property mode is not allowed
- (root): Additional property resources is not allowed
- (root): Additional property clusterRole is not allowed
- (root): Additional property config is not allowed
- (root): Additional property ports is not allowed
- (root): Additional property presets is not allowed
- (root): Additional property replicaCount is not allowed
- (root): Additional property extraVolumeMounts is not allowed
```
my custom-values.yaml 

```
opentelemetry-collector:
  enabled: false

jaeger:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

opensearch:
  enabled: false
```
