### ISSUE TITLE
what's the equivalent config of 'OTEL_EXPORTER_OTLP_PROTOCOL' for collector ?

### ISSUE THREAD

**Issue by Arcadia822** [open-telemetry/opentelemetry-helm-charts#1329]
I'm following the collector chart document to figure out how to sending data from inside k8s to my own endpoints.

I can send telemetry data from sdk with `exporter_otlp_protocol=http/protobuf`.  But when use the collector I got following error:

```
2024-09-06T07:58:48.132Z	info	exporterhelper/retry_sender.go:118	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "logs", "name": "otlp/log", "error": "rpc error: code = Unavailable desc = name resolver error: produced zero addresses", "interval": "6.423739265s"}
```

I'm assuming this error is caused by the protocol configuration not set. But cannot find the proper setup.

values.yaml:
```
mode: daemonset

image:
  repository: otel/opentelemetry-collector-k8s

presets:
  # enables the k8sattributesprocessor and adds it to the traces, metrics, and logs pipelines
  kubernetesAttributes:
    enabled: true
  # enables the kubeletstatsreceiver and adds it to the metrics pipelines
  kubeletMetrics:
    enabled: true
  hostMetrics:
    enabled: true
  # Enables the filelogreceiver and adds it to the logs pipelines
  logsCollection:
    enabled: true

config:
  exporters:
    otlp/log:
      endpoint: <my log endpoint>
    otlp/metric:
      endpoint: <my metric endpoint>
    otlp/trace:
      endpoint: <my trace endpoint>
  service:
    pipelines:
      traces:
        exporters: [ otlp/trace ]
      metrics:
        exporters: [ otlp/metric ]
      logs:
        exporters: [ otlp/log ]
```
