### ISSUE TITLE
image.repository check in sub-chart failing

### ISSUE THREAD

**Issue by Meider4cloud** [open-telemetry/opentelemetry-helm-charts#1330]
I have a custom helm chart that uses the opentelemetry-collector chart twice as subcharts to deploy the collector as agent on every node and gateway for sending the telemetry.

I have successfully done this with version ^0.90.0. Now after upgrading to anything from ^0.91.0 I receive an error:

```
Error: UPGRADE FAILED: execution error at (k8s_collector_service/charts/opentelemetry-collector/templates/NOTES.txt:2:3): [ERROR] 'image.repository' must be set. See https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/UPGRADING.md for instructions.
```

I understand that the  templates/NOTES.txt checks for the image.repository and fails when it is not available.  But I have configured it in my values.yaml for every sub-chart. (See the attached extract for de deployment).

## Expected Behaviour
Test passes when it finds the image.repository in the sub-charts.
Updating to newer charts be possible.

## Current Behaviour
in version ^0.90.0 : Image changing works properly. No error messages.
in newer versions: Updates fails because of error message.

```yaml
# Charts.yaml
...

dependencies:
  - name: opentelemetry-collector
    version: "^0.104.0"
    repository: "@open-telemetry"
    alias: collector-deployment
    condition: collector-deployment.enabled
    tags:
      - deployment

  - name: opentelemetry-collector
    version: "^0.104.0"
    repository: "@open-telemetry"
    alias: collector-daemonset
    condition: collector-daemonset.enabled
    tags:
      - daemonset
 ```

```yaml
# values.yaml

### GATEWAY Deployment
collector-deployment:
  image:
    repository: otel/opentelemetry-collector-contrib
  enabled: true
  nameOverride: otelcol-gw
  mode: deployment
  extraEnvsFrom:
    - configMapRef:
        name: proxy-config    
  presets:
  ...
```

**Comment by TylerHelmuth** [comment]
@Meider4cloud I have been unable to reproduce your error.  The `open-telemetry/opentelemetry-demo` chart, for example, is installable and uses the opentelemetry-collector chart as a subchart without issue.

Can you provide a test case that reproduces the issue for me to try locally?

**Comment by Meider4cloud** [comment]
Hello,

Thank you for your help @dosu and @TylerHelmuth.

@TylerHelmuth How can I provide a test case for you?

I was giving a try again now and it becomes even stranger.

1. All my collector configurations have the  image.repository included. 
2. I have added a 3. collector config as a second Gateway for another backend. I just copied and pasted from before and changed the exporter endpoint.
3. I can update  2 of the 3 collector sub-charts to version 0.104.0 without error. Just the 3. is still failing.

```yaml

# Charts.yaml
apiVersion: v2
name: k8s_collector_service
description: A Helm chart for Kubernetes. It can be used to deploy OpenTelemetry Collectors and configure them from one place.

type: application
version: 0.1.0
appVersion: "2024.05.03"

dependencies:
  - name: opentelemetry-collector
    # version: "^0.90.0"
    version: "^0.104.0"
    repository: "@open-telemetry"
    alias: collector-deployment
    condition: collector-deployment.enabled
    tags:
      - deployment

  - name: opentelemetry-collector
    # version: "^0.90.0"
    version: "^0.104.0"
    repository: "@open-telemetry"
    alias: collector-daemonset
    condition: collector-daemonset.enabled
    tags:
      - daemonset
  
  - name: opentelemetry-collector
    version: "^0.90.0"
    # version: "^0.104.0"
    repository: "@open-telemetry"
    alias: collector-dash0
    condition: collector-dash0.enabled
    tags:
      - dash0
```

```yaml
# values.yaml
nodeSelector: {}

tolerations: []
affinity: {}
default: {}

### GATEWAY Deployment
collector-deployment:
  image:
    repository: otel/opentelemetry-collector-contrib
  enabled: true
  nameOverride: otelcol-gw
  mode: deployment
 
    
  presets:
    kubernetesAttributes:
      enabled: true
    clusterMetrics:  # It does create permissions for the receiver automatically!!! Have it activated! 
      enabled: true
    kubernetesEvents:
      enabled: false  # should be collected by the agent collectors
  extraEnvs:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: OTEL_RESOURCE
      value: k8s.node.name=$(MY_NODE_NAME)

  resources:
    limits:
      memory: 2000Mi
  service:
    type: ClusterIP
  ports:
    metrics:
      enabled: true
    prometheus:
      enabled: true
      containerPort: 9464
      servicePort: 9464
      protocol: TCP
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9464"
    opentelemetry_community_demo: "true"
  
  config:
    ...


### AGENT Daemonset
collector-daemonset:
  nameOverride: otelcol-ag
  enabled: true
  mode: daemonset
  image:
   # repository: "otel/opentelemetry-collector-k8s"
    repository: "otel/opentelemetry-collector-contrib"
  presets:
    hostMetrics:
      enabled: true
    kubeletMetrics:
      enabled: true
    kubernetesAttributes:
      enabled: true
    kubernetesEvents:
      enabled: true   
    logsCollection:
      enabled: true
      includeCollectorLogs: true 


    ### Using the K8s downwardApi to get the node name and attach it to all resources
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: OTEL_RESOURCE
      value: k8s.pod.ip=$(MY_POD_IP)
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: OTEL_RESOURCE
      value: k8s.node.name=$(MY_NODE_NAME)

  resources:
    limits:
      memory: 400Mi
  service:
    type: ClusterIP
    enabled: true
  ports:
    metrics:
      enabled: true
    prometheus:
      enabled: true
      containerPort: 9464
      servicePort: 9464
      protocol: TCP
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9464"
    opentelemetry_community_demo: "true"

  clusterRole:
    create: true
    name: "opentelemetry-collector-admin"
    rules:
    - verbs: ["*"]
      resources: ["*"]
      apiGroups: ["*"]
    - verbs: ["*"]
      nonResourceURLs: ["*"]
    clusterRoleBinding:
      name: "opentelemetry-collector-admin"
  serviceAccount:
    create: true
    name: "opentelemetry-collector-admin"
  config:
   ...

### Collector for dash0
collector-dash0:
  enabled: true
  image:
    repository: otel/opentelemetry-collector-contrib
  nameOverride: otelcol-dash0
  mode: deployment

  presets:
    kubernetesAttributes:
      enabled: true
    clusterMetrics:  # It does create permissions for the receiver automatically!!! Have it activated! 
      enabled: true
    kubernetesEvents:
      enabled: false  # should be collected by the agent collectors

  extraEnvs:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: OTEL_RESOURCE
      value: k8s.node.name=$(MY_NODE_NAME)
    - name: DASH0_AUTHORIZATION_TOKEN
      valueFrom:
        secretKeyRef:
          name: dash0-secrets
          key: dash0-authorization-token
          optional: false

  resources:
    limits:
      memory: 2000Mi
  service:
    type: ClusterIP
  ports:
    metrics:
      enabled: true
    prometheus:
      enabled: true
      containerPort: 9464
      servicePort: 9464
      protocol: TCP
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9464"
    opentelemetry_community_demo: "true"
  
  config:
   ...
```
