### ISSUE TITLE
[opentelemetry-kube-stack] Optionally install cert-manager CRDs

### ISSUE THREAD

**Issue by rogercoll** [open-telemetry/opentelemetry-helm-charts#1340]
Cert-manager is the recommended dependency for managing Operator's webhooks TLS certificates: https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1331

If `cert-manager` CRDs are not available on the k8s cluster, an additional Helm command will be need to deploy the kube-stack chart:

```
$ helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.15.3 --set crds.enabled=true
$ helm install --create-namespace --namespace opentelemetry-operator-system opentelemetry-kube-stack open-telemetry/opentelemetry-kube-stack
```

It would be great if the kube-stack Chart could be installed as a single pipeline step, and conditionally add the `cert-manager` dependency. Has this been considered previously? Are there any known blockers?

### Optional dependency

I have tried to add the cert-manager Helm Chart as an optional dependency to the kube-stack Chart and pospone the corresponding CRDs creation with annotations (`"helm.sh/hook": post-install,post-upgrade`), but I get timeout issue due this known issue https://github.com/cert-manager/cert-manager/issues/1829

```yaml
dependencies:
...
  - name: cert-manager
    version: v1.15.3
    repository: https://charts.jetstack.io
    alias: cert-manager
    condition: cert-manager.enabled
```

Another option would be to manually add [cert-manager CRDs](https://github.com/cert-manager/cert-manager/tree/master/deploy/crds) to the current `crds` internal kube-stack Chart: https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-kube-stack/charts/crds

**Comment by jvoravong** [comment]
Have you checked out using the self signed certs using values like this using the operator chart as a subchart? This is a popular option for users in one of my projects.

```
operator:
  enabled: true
  admissionWebhooks:
    certManager:
      enabled: false
    autoGenerateCert:
      enabled: true
```
