### ISSUE TITLE
Chart doesn't respect null jaeger/zipkin/prometheus default receivers

### ISSUE THREAD

**Issue by stonkie** [open-telemetry/opentelemetry-helm-charts#1357]
Hello,

The documentation says to set the default receivers to null to disable them. This doesn't work and still outputs the receiver configs, so a chizeled otel collector image that doesn't contain those receivers fails to load in the default charts.

Link to doc : https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/README.md#basic-top-level-configuration 

I would expect the jaeger entry to be absent from the ConfigMap here :

![image](https://github.com/user-attachments/assets/a4bafd18-6f09-410d-a811-02bd5d3cf964)

To show this way of configuring actually works : 

![image](https://github.com/user-attachments/assets/8ce8dcb5-5b25-4005-96a4-500900e50d04)

To repro, drop this Chart.yaml file into a templates directory : 

```yaml
apiVersion: v2
name: opentelemetry-collector
description: Sets up an OpenTelemetry Collector
type: application
version: 1.0.0
appVersion: "0.77.0"
dependencies:
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.106.1
```

Then run those commands : 

```shell
helm repo add opentelemetry-helm-charts https://open-telemetry.github.io/opentelemetry-helm-charts
helm dependency build
helm template test . --set "opentelemetry-collector.image.repository=test,opentelemetry-collector.mode=deployment,opentelemetry-collector.config.receivers.jaeger=null"
```
