### ISSUE TITLE
Kubernetes infra metrics not scrapped due to a wrong ServiceMonitor selector in opentelemetry-kube-stack-0.2.1

### ISSUE THREAD

**Issue by davidcaste** [open-telemetry/opentelemetry-helm-charts#1362]
**Please describe your use case / problem.**

I was giving a try to the `opentelemetry-kube-stack` v0.2.1 chart when I realized almost none of the kubernetes infrastructure metrics were scrapped. After some debugging I found the selector in some `ServiceMonitor` objects were using a missing `release` label.

These are some examples I got when generating the manifests using `helm template`. This is the `ServiceMonitor` for `kube-controller-manager`:

```
# Source: opentelemetry-kube-stack/templates/exporters/kube-controller-manager/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opentelemetry-kube-stack-kube-controller-manager
  namespace: monitoring
  labels:
    app: opentelemetry-kube-stack-kube-controller-manager
    helm.sh/chart: opentelemetry-kube-stack-0.2.1
    app.kubernetes.io/version: "0.107.0"
    app.kubernetes.io/managed-by: Helm
    release: "opentelemetry-kube-stack"
spec:
  jobLabel: jobLabel
  
  selector:
    matchLabels:
      app: opentelemetry-kube-stack-kube-controller-manager
      release: "opentelemetry-kube-stack"
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
```

but as we can see here the `Service` lacks the `release` label:

```
# Source: opentelemetry-kube-stack/templates/exporters/kube-controller-manager/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-kube-stack-kube-controller-manager
  labels:
    app: opentelemetry-kube-stack-kube-controller-manager
    jobLabel: kube-controller-manager
    helm.sh/chart: opentelemetry-kube-stack-0.2.1
    app.kubernetes.io/version: "0.107.0"
    app.kubernetes.io/managed-by: Helm
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10257
      protocol: TCP
      targetPort: 10257
  selector:
    component: kube-controller-manager
  type: ClusterIP
```

so it would never be scrapped properly.

**Describe the solution you'd like**

I'd like the generated `Service` objects to have the proper `release` label, so the `ServiceMonitor` is able to find them properly.

**Describe alternatives you've considered**

Update the `opentelemetry-kube-stack.labels` defined in `charts/opentelemetry-kube-stack/templates/_helpers.tpl` to add the `release` label.

**Additional context**

n/a
