### ISSUE TITLE
[collector] kubernetesAttributes preset ClusterRole does not include "nodes"

### ISSUE THREAD

**Issue by lindeskar** [open-telemetry/opentelemetry-helm-charts#1377]
The [kubernetesAttributes preset](https://opentelemetry.io/docs/kubernetes/helm/collector/#kubernetes-attributes-preset) does not include "nodes" in it's ClusterRole, leading to errors when trying to access Node metadata:

> `User "system:serviceaccount:opentelemetry-collector:otelcol-opentelemetry-collector" cannot list resource "nodes" in API group "" at the cluster scope`

Example chart values causing the error:

```yaml
mode: "daemonset"
image:
  repository: otel/opentelemetry-collector-contrib
config:
  processors:
    k8sattributes:
      extract:
        labels:
          - { tag_name: zone, key: "topology.kubernetes.io/zone", from: node }
presets:
  logsCollection:
    enabled: true
  kubernetesAttributes:
    enabled: true
```

This addition to values fixes the problem:

```yaml
clusterRole:
  rules:
    - apiGroups: [""]
      resources: ["nodes"]
      verbs: ["get", "list", "watch"]
```

Is this by design? I think we could update the preset documentation, or simply add "nodes" to the template:

https://github.com/open-telemetry/opentelemetry-helm-charts/blob/694c38d175d72fe8e3bc6cc5c182728615f72cbd/charts/opentelemetry-collector/templates/clusterrole.yaml#L18-L28

--

From the k8sattributesprocessor [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md#cluster-scoped-rbac):

> _When using `k8s.node.uid` or extracting metadata from node, the processor needs get, watch and list permissions for `nodes` resources._
