### ISSUE TITLE
opentelemetry-kube-stack doesn't provide a way to pass --enable-multi-instrumentation=true to the operator manager container

### ISSUE THREAD

**Issue by garrmark** [open-telemetry/opentelemetry-helm-charts#1385]
In the **opentelemetry-operator** chart one can pass args to the manager via **extraArgs**, but no such mechanism appears to exist in the **opentelemetry-kube-stack** chart

My bad, it works:
```
opentelemetry-operator:
  manager:
    extraArgs: 
      - '--enable-multi-instrumentation=true'
```
