### ISSUE TITLE
[charts/opentelemetry-kube-stack] configMap volumeMounts indentation issue with DaemonSet collector pod.

### ISSUE THREAD

**Issue by MG-Nix** [open-telemetry/opentelemetry-helm-charts#1389]
Hi,

Using configMap to mount a volume in the collectors seems to generate buggy YAML, which causes an issue with installing with Helm.

## Configuration
open-telemetry/opentelemetry-kube-stack version=0.2.3

#### values.yaml
```
defaultCRConfig:
  enabled: true

  volumeMounts:
    - name: myorg-cert-volume
      mountPath: /etc/ssl/certs/myorg  # The directory inside the container where the certificates will be copied
  volumes:
    - name: myorg-cert-volume
      configMap:
        name: myorg-ca-certs  # The name of the ConfigMap containing the certificates
```

I'm using myorg CA certificate for exporters `endpoint` and volume isn't mounting to the collector pods.

```
      exporters:
        otlphttp:
          auth:
            authenticator: basicauth/grafana_cloud
          endpoint: https://otlp-gateway-prod-eu-west-2.grafana.net/otlp
          tls:
            ca_file: /etc/ssl/certs/myorg/MyOrgG3RootCA.crt
```

## Issue

While installing with this configuration, I'm getting the following error with `helm install`

```
otel-kube-stack> helm install --namespace monitoring --create-namespace opentelemetry-kube-stack open-telemetry/opentelemetry-kube-stack -f values.yaml
Error: INSTALLATION FAILED: YAML parse error on opentelemetry-kube-stack/templates/collector.yaml: error converting YAML to JSON: yaml: line 437: did not find expected key
```

## Resolution

The issue is with an incorrect indentation in the DaemonSet collector pod specification for `configMap` and `mountPath`
Fixing the indentation manually in the template and applying the template has fixed the issue.

![image](https://github.com/user-attachments/assets/cdbeff1a-debe-468f-aeec-3b6493c68350)

![image](https://github.com/user-attachments/assets/c9b86d8a-93d9-45d5-a6af-10dca34953cd)
