### ISSUE TITLE
Q: What does config look like to export traces to two backends?

### ISSUE THREAD

**Issue by naseemkullah** [open-telemetry/opentelemetry-helm-charts#14]
Maybe a snippet to export to jaeger + zipkin at the same time would be nice to have in README.md as a reference.

**Comment by naseemkullah** [comment]
In particular I would have expected this to be a list https://github.com/open-telemetry/opentelemetry-helm-charts/blob/8d5bcf0f7e30a7d6d187f149ff7527735263c5f4/charts/opentelemetry-collector/values.yaml#L19 if multiple exporters are supported, @dmitryax do you know if its possible to have multiple exporters configured via this chart?

**Comment by dmitryax** [comment]
@naseemkullah yes, multiple exporters can be set in `agent(standalone)Collector.configOverride`. anything set there will be merged to the default config. For example to have two exporters, we'd need:
```
configOverride:
  exporters:
    jaeger:
      ...
    zipkin:
      ...
  service:
    pipelines:
      traces:
        exporters: [zipkin, jaeger]
```

I'll add a few examples
