### ISSUE TITLE
Able to get metrics from pods and container but not for nodes

### ISSUE THREAD

**Issue by Yiyito11** [open-telemetry/opentelemetry-helm-charts#1467]
Hello Folks, I installed inside our AKS the opentelemetry colector  helm chart. We have being using it to send logs from services into splunk si far. Now I had configured the `kubeletMetrics: enabled: true` so to also get metrics from pods and nodes
and configured the kubeletstat this way to get those metrics 
```
kubeletstats:
      collection_interval: 10s
      auth_type: 'serviceAccount'
      endpoint: 'https://${env:K8S_NODE_NAME}:10250'
      insecure_skip_verify: true
      metric_groups:
       - container
       - pod
       - node
```
I´m getting in splunk metrics like: `metric_name:k8s.pod.memory.usage` and  `metric_name:k8s.pod.cpu.utilization` or `metric_name:system.memory.usage` (among others) but all related to pods and container or system. I can´t see those for the nodes. am I missing something? according to the doc node metrics should also be there: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/documentation.md 

what else should I be configuring or I could be missing? thank you!
