### ISSUE TITLE
[opentelemetry-kube-stack] Support private repositories for opentelemetry-operator images

### ISSUE THREAD

**Issue by Amoolaa** [open-telemetry/opentelemetry-helm-charts#1468]
At the moment there is no way to specify repositories for the opentelemetry-operator (and the kube-rbac-proxy) images. This is already supported in the opentelemetry-operator helm chart.

**Comment by JaredTan95** [comment]
It is currently customizable: 
```yaml
opentelemetry-operator:
  # Field indicating whether the operator is enabled or not
  enabled: true
  manager:
    image:  #👈
      repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator #👈
```
