### ISSUE TITLE
missing variables and doc for endpoint credentials

### ISSUE THREAD

**Issue by travisghansen** [open-telemetry/opentelemetry-helm-charts#1469]
https://github.com/open-telemetry/opentelemetry-operator/blob/main/cmd/otel-allocator/README.md#service--pod-monitor-endpoint-credentials

The pre-reqs described in that doc are not sufficient. The feature was not working and eventually I noticed in the following in the logs:

`Cert-Manager is not available to the operator, skipping adding to scheme.`

I do indeed have `cert-manager` installed so the log was a bit perplexing. After digging through the code I found this: https://github.com/open-telemetry/opentelemetry-operator/blob/main/internal/autodetect/autodetectutils/utils.go which detects the service account name and *only* does so via env var. This should probably be documented in the above link.

In addition is may be good to have more seamless integration with the helm chart to autoset the env vars.

Alternatively, it may be easier to have the code decode the `token` file and pull the data out similar to reading the data from the `namespace` file.

```yaml
manager:
  env:
    # these are required to make cert-manager detection work properly
    SERVICE_ACCOUNT_NAME: {{ .Release.Name }}
    NAMESPACE: {{ .Release.Namespace }}
```
