### ISSUE TITLE
Hi guys,

### ISSUE THREAD

**Issue by matheus-meneses** [open-telemetry/opentelemetry-helm-charts#1477]
Hi guys,

I would like to propose a new feature and a breaking change to improve the autoscaling capabilities of the OpenTelemetry Collector Helm chart.

1. Add KEDA support:
   KEDA (Kubernetes Event-driven Autoscaling) reached General Availability in August 2023, and its ecosystem is growing rapidly. Given its importance in the Kubernetes autoscaling landscape, I believe it's crucial to add support for KEDA in our Collector's Helm chart.

2. Restructure autoscaling configuration:
   To accommodate both HPA (Horizontal Pod Autoscaler) and KEDA, I propose a breaking change in the autoscaling configuration. This change will provide a clear separation between the two autoscaling methods and improve the overall structure of the configuration.

Proposed changes:
a. Move `autoscaling.behavior` to `autoscaling.hpa.behavior`
b. Introduce an `autoscaling.mode` field to select between `hpa` (default) and `keda`
c. Create a new configuration section `autoscaling.hpa` to support KEDA-specific settings
d. Create a new configuration section `autoscaling.keda` to support KEDA-specific settings

Example of the proposed structure:
```yaml
autoscaling:
  enabled: true
  mode: hpa | keda
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  hpa:
    behavior: {}
  keda:
    # ... KEDA-specific settings
```       

_Originally posted by @matheus-meneses in https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1475_
