### ISSUE TITLE
[operator] Setting multiple feature gates causes operator panic

### ISSUE THREAD

**Issue by swiatekm** [open-telemetry/opentelemetry-helm-charts#1481]
When we set multiple feature gates using `featureGatesMap`, we get a malformed command line argument for the operator, leading to a panic.

Using the following values file:

```yaml
manager:
  featureGatesMap:
    operator.targetallocator.mtls: false
    operator.collector.targetallocatorcr: false
    operator.sidecarcontainers.native: true
    operator.observability.prometheus: false
    operator.golang.flags: true
    operator.collector.default.config: false
```

results in the operator getting the following command line argument:

```
--feature-gates=,,operator.golang.flags,,operator.sidecarcontainers.native,
```

This is an invalid value, and causes the operator to crash. At a glance, this is caused by the fact that [we add a comma to the feature gate string](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/b08f21445167ef5830788e1a0a17e195c0ebfa82/charts/opentelemetry-operator/templates/_helpers.tpl#L167) even if the value in the map is false.

Originally reported in https://github.com/open-telemetry/opentelemetry-operator/pull/3559.
