### ISSUE TITLE
Not able to override collection_interval in kubernetes presets.

### ISSUE THREAD

**Issue by shubham805** [open-telemetry/opentelemetry-helm-charts#1488]
When I am configuring otel-collector with kubernetes presets, I want to override collection_interval. The collection_interval for receivers are hard coded in this file - charts/opentelemetry-collector/templates/_config.tpl  (https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/templates/_config.tpl)

Example
```
presets:
  kubernetesAttributes:
    enabled: true
    extractAllPodLabels: true
    extractAllPodAnnotations: true
  kubeletMetrics:
    enabled: true
    collection_interval: 30s
  kubernetesEvents:
    enabled: true
    collection_interval: 30s
  hostMetrics:
    enabled: true
    collection_interval: 30s
  logsCollection:
    enabled: true
  clusterMetrics:
    enabled: false

```

**Comment by TylerHelmuth** [comment]
@shubham805 you can override it by configuring the component in `confg`. For example:

```yaml
presets:
  kubeletMetrics:
    enabled: true

config:
  receivers:
    kubeletstats:    
      collection_interval: 30s
```

We purposefully do not allow configuring the component properties directly via the preset section.
