### ISSUE TITLE
[opentelemetry-operator]: `featureGatesMap` properties not allowed

### ISSUE THREAD

**Issue by peske** [open-telemetry/opentelemetry-helm-charts#1489]
I'm using `opentelemetry-operator` Helm chart version `0.78.1`, and I have the following part in my values file:

```yaml
manager:
  featureGatesMap:
    targetAllocatorMtls: false
    targetAllocatorCR: false
    targetAllocatorFallbackStrategy: false
    nativeSideCarContainers: false
    prometheusOperator: false
    golangFlags: true
    collectorDefaultConfig: false
```

When I try to export generated manifests to review them:

```console
helm template -f ./10-otel/values.yaml opentelemetry-operator \
    open-telemetry/opentelemetry-operator --version 0.78.1 \
    --namespace otel-operator-system > ./temp.yaml
```

I'm getting the following error:

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-operator:
- manager.featureGatesMap: Additional property collectorDefaultConfig is not allowed
- manager.featureGatesMap: Additional property golangFlags is not allowed
- manager.featureGatesMap: Additional property nativeSideCarContainers is not allowed
- manager.featureGatesMap: Additional property prometheusOperator is not allowed
- manager.featureGatesMap: Additional property targetAllocatorCR is not allowed
- manager.featureGatesMap: Additional property targetAllocatorFallbackStrategy is not allowed
- manager.featureGatesMap: Additional property targetAllocatorMtls is not allowed
```

Am I doing something wrong, or if there's a problem with the chart?

**Comment by TylerHelmuth** [comment]
Related https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1463

**Comment by TylerHelmuth** [comment]
@peske also in your scenario the keys need to match exactly to the feature gate name. Like

```yaml
manager:
  featureGatesMap:
    operator.targetallocator.mtls: false
    operator.collector.targetallocatorcr: false
    operator.sidecarcontainers.native: true
    operator.observability.prometheus: false
    operator.golang.flags: true
    operator.collector.default.config: false
```
