### ISSUE TITLE
Can't contact OTEL agent daemon set from other PODs without using hostNetwork

### ISSUE THREAD

**Issue by carlosjgp** [open-telemetry/opentelemetry-helm-charts#149]
when configuring the environment variables as
```
- name: HOST_IP
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
- name: OTEL_EXPORTER_OTLP_ENDPOINT
  name: http://${HOST_IP}:4318
```

`opentelemetry-collector` chart does not allow to set `hostNetwork` for the DaemonSet which is both useful and required when using some CNIs like Cilium

PR created [here](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/148)
