### ISSUE TITLE
OpenTelemetry Demo Failing to Install using Helm Chart

### ISSUE THREAD

**Issue by kmgalla58** [open-telemetry/opentelemetry-helm-charts#1494]
Hi, today I tried to install the demo application using helm as recommended in this [article](https://opentelemetry.io/docs/demo/kubernetes-deployment/#install-using-helm-recommended). I successfully created my values.yml file and added the repository. However, when I go to do the helm install step I get this output: 
```
Error: INSTALLATION FAILED: template: opentelemetry-demo/templates/component.yaml:12:12: executing "opentelemetry-demo/templates/component.yaml" at <include "otel-demo.deployment" $config>: error calling include: template: opentelemetry-demo/templates/_objects.tpl:106:16: executing "otel-demo.deployment" at <include "otel-demo.pod.env" .>: error calling include: template: opentelemetry-demo/templates/_pod.tpl:43:4: executing "otel-demo.pod.env" at <tpl (toYaml $allEnvs) .>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: - name: OTEL_SERVICE_NAME
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: metadata.labels['app.kubernetes.io/component']
- name: OTEL_COLLECTOR_NAME
  value: '{{ include "otel-demo.name" . }}-otelcol'
- name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
  value: cumulative
- name: FLAGD_METRICS_EXPORTER
  value: otel
- name: OTEL_EXPORTER_OTLP_ENDPOINT
  value: http://$(OTEL_COLLECTOR_NAME):4318
- name: OTEL_RESOURCE_ATTRIBUTES
  value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version={{
    .Chart.AppVersion }}: "BasePath" is not a value
```

My first thought was to test installing without my custom values yaml but I got the same output. It looks like it is an error in the actual source code but please correct me if I'm missing something. When I had originally installed this around a week or two ago, the installation was successful so I'm not sure if any major changes to the code have been made since then. I had to go back and uninstall and then reinstall the app however because at the time I didn't realize I needed my custom values yaml to deploy properly. Please let me know your thoughts and anything I can do to fix/workaround this issue!

**Comment by puckpuck** [comment]
Do you have Helm 3.14 or greater installed as listed in the [prerequisites](https://opentelemetry.io/docs/demo/kubernetes-deployment/#prerequisites) for this?

**Comment by zhangxianyu777** [comment]
i have the same question，my k8s version : v1.24.0，helm version ：v3.8.2，Did I choose the wrong version? What version should I choose

**Comment by meswapnilk** [comment]
As mentioned in the prereqs [here](https://opentelemetry.io/docs/demo/kubernetes-deployment/#prerequisites)

- Kubernetes 1.24+
- 6 GB of free RAM for the application
- Helm 3.14+ (for Helm installation method only)

**Comment by cmaluend** [comment]
I assume you are installing the demo for [SigNoz](https://signoz.io/docs/install/kubernetes/local/#optional-install-opentelemetry-demo) because I had the same issue. The values file says:
```
default:
  env:
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: "metadata.labels['app.kubernetes.io/component']"
    - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
      value: cumulative
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: 'service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version={{ .Values.appVersion }}'
    - name: OTEL_COLLECTOR_NAME
      value: signoz-otel-collector.<namespace>.svc.cluster.local
```

The bug is the reference to the _appVersion_. It should be `{{ .Chart.AppVersion }}` Instead of `{{ .Values.appVersion }}` .
