### ISSUE TITLE
kubeletstats: failed to verify certificate: x509 error

### ISSUE THREAD

**Issue by vipinvkmenon** [open-telemetry/opentelemetry-helm-charts#1513]
Helm Chart Version: `0.111.2`

Helm Configuration:

```
mode: daemonset
#nameOverride: otel-collector-ds
image:
  repository: "otel/opentelemetry-collector-k8s"

command:
  name: "otelcol-k8s"

replicaCount: 1

presets:
  kubeletMetrics:
    enabled: true
  hostMetrics:
    enabled: true
config:
  # deltatocumulative processor is needed to convert metrics with delta temporality to cumulative temporality.
  # VictoriaMetrics doesn't support delta temporality. Skip this processor if you don't use delta temporality.
  processors:
    deltatocumulative:
      max_stale: 5m
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  exporters:
    otlphttp/victoriametrics:
      compression: gzip
      encoding: proto
      metrics_endpoint: http://victoria-metrics-single-server:8428/opentelemetry/v1/metrics
      tls:
        insecure: true
  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [deltatocumulative]
        exporters: [otlphttp/victoriametrics]
```
However, the `kubletstats` receiver does not work. It throws the error:

```
2025-02-03T14:57:04.706Z        error   kubeletstatsreceiver@v0.115.0/scraper.go:103    call to /stats/summary endpoint failed  {"kind": "receiver", "name": "kubeletstats", "data_type": "metrics", "error": "Get \"https://10.180.13.7:10250/stats/summary\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver.(*kubletScraper).scrape
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver@v0.115.0/scraper.go:103
go.opentelemetry.io/collector/scraper.ScrapeMetricsFunc.ScrapeMetrics
        go.opentelemetry.io/collector/scraper@v0.115.0/metrics.go:24
go.opentelemetry.io/collector/receiver/scraperhelper.newObsMetrics.func1
        go.opentelemetry.io/collector/receiver@v0.115.0/scraperhelper/obs_metrics.go:52
go.opentelemetry.io/collector/scraper.ScrapeMetricsFunc.ScrapeMetrics
        go.opentelemetry.io/collector/scraper@v0.115.0/metrics.go:24
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport
        go.opentelemetry.io/collector/receiver@v0.115.0/scraperhelper/scrapercontroller.go:202
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1
        go.opentelemetry.io/collector/receiver@v0.115.0/scraperhelper/scrapercontroller.go:185
```

Any guidance on how this could be resolved is appreciated.

**Comment by JaredTan95** [comment]
maybe this https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26481 can solve your problem.

**Comment by jonath92** [comment]
For me, it was enough to add: 

```yaml
config:
  receivers:
    kubeletstats:
      insecure_skip_verify: true
```
