### ISSUE TITLE
[opentelemetry-kube-stack] Error scraping metrics hostfs - permission denied

### ISSUE THREAD

**Issue by rdelacruz2** [open-telemetry/opentelemetry-helm-charts#1526]
Currently using the following stack with Kustomize:

```
helmCharts:
  - name: opentelemetry-kube-stack
    releaseName: opentelemetry-kube-stack
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.3.13
    namespace: <namespace>
    valuesFile: values.yaml
    includeCRDs: true
```

We are getting an error in the following pod: opentelemetry-kube-stack-cluster-stats-collector-84bbc4978rscw7

```
2025-02-14T12:50:09.768Z	error	scraperhelper/scrapercontroller.go:205	Error scraping metrics	{"kind": "receiver", "name": "hostmetrics", "data_type": "metrics", "error": "failed to read usage at /hostfs/run/containerd/runc/k8s.io/10fc15005c08a38abed8f20655764b69965663ca0cc59bfe5d5aa69a3f2307cb/runc.FUuXf7: permission denied", "scraper": "hostmetrics"}
```

The workaround in here is to provide root permissions to the collector but this is not recommended in the documentation, no more changes were made in the collector:

```
  # Security context for the collector
  securityContext: {}
    # privileged: true
    # runAsUser: 0
    # capabilities:
    #   add:
    #     - SYS_ADMIN
    #     - DAC_READ_SEARCH
  #   runAsUser: 1000
  #   capabilities:
  #     drop:
  #       - ALL
```

If more information is needed, let me know!
Thanks!
