### ISSUE TITLE
[opentelemetry-kube-stack] Work with kube-prometheus-stack dashboards

### ISSUE THREAD

**Issue by Utwo** [open-telemetry/opentelemetry-helm-charts#1545]
This is more a question than an issue. Is this chart supposed to work out of the box with the rules and dashboards defined in the [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)?

**Comment by N214** [comment]
Hey, do you mind sharing your opentelemetry-kube-stack values file to make it work with kube-prom-stack? Thanks

**Comment by Utwo** [comment]
For the cluster label, you can add this in the values file
```
extraEnvs:
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: "k8s.cluster.name=<clusterName>,cluster=<clusterName>"
```

For the job label I have no idea.

**Comment by N214** [comment]
Thank you, I see this [PR](https://github.com/open-telemetry/opentelemetry-collector/pull/2979) has made job label available for prom exporter but what aboutotlp exporter?

I'm no sure if the resource attribute below could solve the issue. 
https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/#resource-attributes

**Comment by N214** [comment]
After some research, I made it work with two different configurations.

First method and the easiest one is to add the label to OTEL_RESOURCE_ATTRIBUTES env var like below `cluster=k3s` and `job=opentelemetry` here 

```yaml
extraEnvs:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "k8s.cluster.name=k3s,cluster=k3s,job=opentelemetry,service.name=otel,service.instance.id=test,service.namespace=monitoring"
```

The second method, is to add a custom resource processor.
```yaml
processors:
  resource:
    attributes:
      - key: cluster
        value: k3s
        action: insert
      - key: job
        value: opentelemetry
        action: insert
```

However, both method should not be used together, during my test, adding only job as resource processor lead the cluster label to become <unspecified> for some reason. 

Which method is the right one to use? Maybe @TylerHelmuth has more insights?
