### ISSUE TITLE
[opentelemetry-kube-stack] - wrong environment value on K8sAttributesConfig

### ISSUE THREAD

**Issue by hbangT** [open-telemetry/opentelemetry-helm-charts#1548]
when deploying opentelemetry-kube-stack using helm chart, otel-collector-daemonset has environment value as below.
```
  - name: OTEL_K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
```
https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-kube-stack/templates/collector.yaml#L142-L145

This conflicts with "opentelemetry-collector.kubernetesAttributesConfig"
```
  {{- if eq .Values.mode "daemonset" }}
    filter:
      node_from_env_var: K8S_NODE_NAME
  {{- end }}
```
https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/templates/_config.tpl#L210-L213.

This makes k8sattributes processor to get kubernetes node name when otel collector is running in agent mode.

The correct filter should be 
```
  {{- if eq .Values.mode "daemonset" }}
    filter:
      node_from_env_var: OTEL_K8S_NODE_NAME
  {{- end }}
```

**Comment by TylerHelmuth** [comment]
@hbangT I am confused because the kube-stack chart does not depend on the opentelemetry-collector chart. https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/templates/_config.tpl#L210-L213 refers the the template for rendering the OpenTelemetryCollector Custom Resource, which is an independent template from the collector chart's k8sattributes processor preset concept.

Did you run into an issue when using either of these charts?

**Comment by hbangT** [comment]
Hi @TylerHelmuth, thanks for the review! The issue isn't really coming from OtelCollector it self. My apologies if the title of this issue confuses you.

The issue is more related to this doc.
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md#deployment-scenarios

If you look at the `As an agent` section, 
```
2. Set "filter.node_from_env_var" to the name of the environment variable holding the node name.
k8sattributes:
  filter:
    node_from_env_var: KUBE_NODE_NAME # this should be same as the var name used in previous step
```

I'm trying to run otel collector as agent and restrict each otel agent to query pods running on the same node. k8sattributes config template is using   `KUBE_NODE_NAME`  while the otel container is using `OTEL_KUBE_NODE_NAME`, which block filtering to happen.

Maybe, on the helm chart, we can do something as below?
```
{{- if eq .Values.mode "daemonset" }}
  filter:
    node_from_env_var: {{ .Values.node_from_env_var | default "K8S_NODE_NAME" }}
{{- end }}
```
