### ISSUE TITLE
[opentelemetry-demo] "components: Additional property frontendProxy is not allowed"

### ISSUE THREAD

**Issue by mviitane** [open-telemetry/opentelemetry-helm-charts#1551]
When using the latest opentelemetry-demo helm chart, the following component configurations (in the values file) are no longer allowed and lead to an Error:
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-demo:
- components: Additional property frontendProxy is not allowed
```

```
components:
  frontendProxy:
    service:
      type: NodePort
      nodePort: 32000
    resources:
      limits:
        memory: 80Mi
  loadgenerator:
    resources:
      limits:
        memory: 1.5G
```

I'm using the latest chart for the demo:
`version: 0.36.0`

I was using the same config successfully with the previous chart version.
