### ISSUE TITLE
Open telemetry collector exporter appends endpoint url with /v1/logs

### ISSUE THREAD

**Issue by madseen777** [open-telemetry/opentelemetry-helm-charts#1556]
Hi, i have set up otel collector for trace and log receiving. traces are sent via otel and zipkin receiver to to collector. Logs are sent to collector via otel receiver.  Then they are forwarded further to Loki via otlphttp exporter.

```
config:
    exporters:
      debug: {}
       otlphttp/loki:
        endpoint: https://loki.domain.net:443/loki/api/v1/push
      otlphttp/host:
        endpoint: https://host.domain.net:443
      otlphttp/ip:
        endpoint: http://10.10.10.10:8088
    processors:
      batch: {}
      memory_limiter: null
    receivers:
      otlp:
        protocols:
          http:
            cors:
              allowed_origins:
                - https://*
                - http://*
              allowed_headers:
                - Authorization
                - Content-Type
                - Origin
                - Accept
      jaeger: null
      prometheus: null
    service:
      pipelines:
        traces:
          exporters:
            - debug
            - otlhttp/host
          processors:
            - batch
          receivers:
            - otlp
            - zipkin
        logs:
          exporters:
            - debug
            - otlphttp/ip
            - otlphttp/loki
          processors:
            - batch
          receivers:
            - otlp
        metrics: null
```

I have also set up ingress on collector side to split the incoming traffic accordingly.

```
ingress:
    hosts:
      - host: otel.domain.net
        paths:
          - pathType: Prefix
            path: "/"
            port: 9411
          - pathType: Prefix
            path: "/v1/traces"
            port: 4318
          - pathType: Prefix
            path: "/v1/logs"
            port: 4318
```
So now when i send logs to https://otel.domain.net/v1/logs i should send the logs further to https://loki.domain.net:443/loki/api/v1/push but instead it tries to reach site https://loki.domain.net:443/loki/api/v1/push/v1/logs

Can anyone advise on what is done wrong here?
I am using version 0.114.0 of otel
