### ISSUE TITLE
[Collector-chart] Self Monitoring not Setting Job name

### ISSUE THREAD

**Issue by Syndlex** [open-telemetry/opentelemetry-helm-charts#1562]
I updated from 0.116.0 to 0.117.12, and now the job name used to scrape its own configuration is not working anymore.

This is my setup:
```
- job_name: telemetry/internal_service_name
  scrape_interval: 20s
  static_configs:
    - targets:
        - ${env:MY_POD_IP}:8888
```

I know that the Prometheus Scraper was updated, so I think the problem is there. The job name is always shown as `job="otelcol-contrib"`.

Also, `service.name` is now exported in the labels as: `otelcol-contrib;internal_service_name`.

Does anyone have an idea of what changed?

I tried using just `- job_name: internal_service_name` and also overwriting it with `relabel_configs`, but neither worked.
