### ISSUE TITLE
Replace default config with config presets

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-helm-charts#158]
Instead of providing default configuration, we should have presets of configurations that are applied to the collector. Suggested presets configuration:

```yaml
presets:
  traces:
    enabled: true
  metrics:
    enabled: false
    hostMetrics:
      enabled: false
    selfScraping:
      enabled: true
  logs:
    enabled: false
    containerLogs: 
      enabled: false
```

User also must be able to provide their own config that must be applied after all the presets.

```yaml
config: {}
# receivers: ...
# processors: ...
# exporters: ...
# service: ...
```

Each of the enabled presets and user custom config can be provided to the collector as a configuration argument, no need to merge them in the helm chart.

**Comment by TylerHelmuth** [comment]
The charts now support removing the default config [using null](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/ci/config-override-values.yaml).  User are able to wipe remove all default configuration and replace it with their own.  Does that meet the needs of this issue?

**Comment by dmitryax** [comment]
Yes, I think we still need to move to the presets as a cleaner way than setting nulls. We already have a preset for logs collection, I think we need to apply similar approach to other use cases.

Some presets can require rendering of other resources not configmap only, e.g. `hostMetrics`

**Comment by TylerHelmuth** [comment]
> Some presets can require rendering of other resources not configmap only, e.g. hostMetrics

Like using the presets to determine if we need to render extra permissions or something?

> no need to merge them in the helm chart.

What do you mean by this? 

Finally, if a customer enabled host metrics (or something else also preset) but also defined that component in their config then which wins? I would say their version of the hostMetrics config be what renders in the configmap.

**Comment by dmitryax** [comment]
> Like using the presets to determine if we need to render extra permissions or something?

hostMetrics requires host volume mounts 

> What do you mean by this?

Collector can accept many config files https://github.com/open-telemetry/opentelemetry-collector/blob/150c1ede2f7fb5607035d3c7a10bfcab61c39afe/service/flags.go#L47-L48. I think we should supply each preset as another configuration file and let collector do the merging instead of using helm capabilities. Let me know if it makes sense to you

> Finally, if a customer enabled host metrics (or something else also preset) but also defined that component in their config then which wins? I would say their version of the hostMetrics config be what renders in the configmap.

I believe what user provides in `config` should have precedence over all the presets

**Comment by TylerHelmuth** [comment]
To avoid breaking changes I think we'll need a presets for each item in the current default config or presets that encompasses them.

**Comment by TylerHelmuth** [comment]
> Collector can accept many config files

Today I learned. 

This is an interesting idea. It will certainly reduce logic in the helm chart, but I am initially concerned that by having the collector do the merge the final ending configuration is more obscure. Is it well defined how the collector handles multiple configs if those configs conflict?

**Comment by dmitryax** [comment]
> To avoid breaking changes I think we'll need a presets for each item in the current default config or presets that encompasses them.

Right, ideally the set of presets enabled by default should end up in an equivalent config that we have by default now

**Comment by dmitryax** [comment]
> Is it well defined how the collector handles multiple configs if those configs conflict?

I believe it must be done in a predictable way, same way as helm is doing it (not 100% sure tho):
- Configs that are going later in the command arguments list likely have precedence.
- Maps are merged
- Lists are replaced

All the presets should get their order in the command line in a way that combinations of them works well with each other.

**Comment by TylerHelmuth** [comment]
I'll take a look at this today, but I am not totally convinced yet about the multiple configs. Concerns I'd like to address:

1. Is their documentation we can link to detailing how multiple configs work
2. Does using multiple configs simplify the charts
3. Are presets easy to understand as a consumer of the chart.  We'd be moving away from explicit configuration and I want to make sure it is still easy to understand what each preset does.  
4. How does it feel to interact in k8s with the installed charts when there are multiple configs.

**Comment by TylerHelmuth** [comment]
> Lists are replaced

Won't this mean that if someone uses any presets, but also adds their own configuration, they will have to list preset components in their pipeline section?

```yaml
presets:
  traces:
    enabled: true

config:
  receivers:
    some-extra-receiver:
service:
  pipelines:
    traces:
      receivers: [some-extra-receiver, otlp, zipkin, jaeger]

``` 

I don't love having to list receivers that aren't defined.

**Comment by TylerHelmuth** [comment]
Thinking more about containerLogs as an example, the main benefit of that field is the ability to build out the complex receiver and setup the k8s stuff.  The fact that it also sets up service.logs.receiver is a "nice-to-have", but will have to get overwritten.  In fact, our daemonset-collector-logs example is actually wrong right now because it doesn't update the logs pipeline's receivers.

I'm gonna take a look at this with the perspective of only defining the components and not the pipeline.  This will also make it easier to determine when to include receivers used between multiple pipelines, such as otlp.

**Comment by TylerHelmuth** [comment]
I'm starting to ramble, but here is another consideration:

```yaml
# components enabled by default will be included in the appropriate pipelines(s) by default.  
# If any presets are enabled, or if a component is configured via the 'config' field, then the appropriate 
# component list needs to be configured in the `config` field to include all desired  components
presets:
  extensions:
    health_check:
      enabled: true
    memory_ballast:
      enabled: true
  receivers:
    otlp: 
      enabled: true
    jaeger:
      enabled: true
    zipkin:
      enabled: true
    prometheus: 
      enabled: true
      selfScraping: true
    hostMetrics:
      enabled: false
    filelog: 
      enabled: false
  processors:
    batch:
      enabled: true
    memory_limiter:
      enabled: true
  exporters:
    logging:
      enabled: true

config: {}
```

I'm not convinced this is better than our current config, but I like that in the scenario that you need to manually defined the component list you can see each component to include.
