### ISSUE TITLE
Need help defining argocd application using otel-collector chart

### ISSUE THREAD

**Issue by rojomisin** [open-telemetry/opentelemetry-helm-charts#1581]
I thought this would be a simple task to use argocd to wrap the installation of our otel-collector chart, but I am unable to get the right urls and names and versions of the charts and containers.

I'm using this page as the source of truth
https://opentelemetry.io/docs/platforms/kubernetes/helm/collector/

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-datadog-otel
  namespace: argocd
  labels:
    team: monitoring
spec:
  project: dev
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    # repoURL: https://otel.github.io/opentelemetry-helm-charts
    chart: open-telemetry/opentelemetry-collector
    # chart: opentelemetry-helm/opentelemetry-k8s-operator
    # https://github.com/open-telemetry/opentelemetry-helm-charts/releases
    targetRevision: "0.117.3" # Use the desired version of the chart
    helm:
      valueFiles:
      - ../datadog/values-otlp.yaml
      parameters:
      - name: image.repository
        value: "otel/opentelemetry-collector-k8s"
      # - name: image.tag
      #   value: "0.121.0"
  destination:
    namespace: datadog
    name: gke_dev-project_us-east4_dev-cluster1
  # syncPolicy:
  #   automated:
  #     prune: true
```

our working installation from last year uses:
```
helm upgrade --install datadog-opentelemetry-collector opentelemetry-helm/opentelemetry-collector --values values-otlp.yaml
```

any advice is appreciated

error is
```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm pull --destination /tmp/1ac709d6-701f-44cc-b3de-136a97205f88 --version 0.117.3 --repo https://open-telemetry.github.io/opentelemetry-helm-charts open-telemetry/opentelemetry-collector` failed exit status 1: Error: chart "open-telemetry/opentelemetry-collector" version "0.117.3" not found in https://open-telemetry.github.io/opentelemetry-helm-charts repository
```

version not found, but the page is a 404 🤔 
<img width="504" alt="Image" src="https://github.com/user-attachments/assets/4129fa2f-4698-4c28-9053-4440687f136f" />

**Comment by rojomisin** [comment]
if it helps anyone, this setups up an argo application and allows overriding with values from a separate repo

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-datadog-otel
  namespace: argocd
  labels:
    team: monitoring
spec:
  project: dev
  sources:
  - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: "0.119.0" # Use the desired version of the chart
    helm:
      valueFiles:
      - $values/dev/app/datadog/values-otlp.yaml
      parameters:
      - name: image.repository
        value: "otel/opentelemetry-collector-k8s"
  # - name: image.tag
  #   value: "0.121.0"
  - repoURL: https://github.com/YourOrg/your-repo.git
    targetRevision: refs/tags/argocd-dev. # master
    ref: values
  destination:
    namespace: datadog
    name: gke_gcp-project1_us-central1_app-cluster1-dev
  # syncPolicy:
  #   automated:
  #     prune: true
```
