### ISSUE TITLE
extraVolumeMounts in opentelemetry-collector chart is not creating mount path

### ISSUE THREAD

**Issue by shnigam2** [open-telemetry/opentelemetry-helm-charts#1590]
When using extraVolume and extraVolumeMounts mounts is not getting created 
```
            extraVolumes:
               - name: dynatrace-token
                 secret:
                   secretName: dt-secret
                   items:
                    - key: DT_API_TOKEN
                      path: DT_API_TOKEN
            extraVolumeMounts:
              - name: dynatrace-token
                mountPath: /etc/dynatrace
                readOnly: true
```

when debugging into collector pod
```
kubectl debug -it dynatrace-collector-opentelemetry-collector-agent-5vk9b --image=busybox:1.28 --target=opentelemetry-collector -n dynatrace
Targeting container "opentelemetry-collector". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
Defaulting debug container name to debugger-wwzh9.
If you don't see a command prompt, try pressing enter.

/ # ls -ld /etc/dynatrace
ls: /etc/dynatrace: No such file or directory
/ # 
```

When describing pod it is showing mounts and volumes
```
Volumes:  
dynatrace-token:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  dt-secret
    Optional:    false

    Mounts:
      /conf from opentelemetry-collector-configmap (rw)
      /etc/dynatrace from dynatrace-token (ro)
      /hostfs from hostfs (ro)
      /var/lib/docker/containers from varlibdockercontainers (ro)
      /var/log/pods from varlogpods (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-rqj5k (ro)
```
