### ISSUE TITLE
Unable to increase memory limit for flagd-ui container

### ISSUE THREAD

**Issue by obs-gh-frankmartens** [open-telemetry/opentelemetry-helm-charts#1593]
Here's my values.yaml file I'm attempting to pass: 
```
default:
  image:
    repository: ghcr.io/open-telemetry/demo
    pullPolicy: Always
  schedulingRules:
    nodeSelector:
      workload: demo
components:
  frontend-proxy:
    service:
      type: LoadBalancer
      port: 8080
  flagd:
    sidecarContainers:
    - name: flagd-ui
      resources:
        limits:
          memory: 100Mi
```

Install command:
`helm install --create-namespace -n otel-demo       otel-demo open-telemetry/opentelemetry-demo     --set opentelemetry-collector.enabled="false"     --values otel-demo-values.yaml`

Error:
`Error: INSTALLATION FAILED: template: opentelemetry-demo/templates/component.yaml:12:12: executing "opentelemetry-demo/templates/component.yaml" at <include "otel-demo.deployment" $config>: error calling include: template: opentelemetry-demo/templates/_objects.tpl:106:16: executing "otel-demo.deployment" at <include "otel-demo.pod.env" .>: error calling include: template: opentelemetry-demo/templates/_pod.tpl:14:18: executing "otel-demo.pod.env" at <.useDefault.env>: nil pointer evaluating interface {}.env`

I'm stumped 🤷‍♂

**Comment by obs-gh-frankmartens** [comment]
Figured it out... flagd component should look like the following (not sure why it requires "useDefault"):

```
components:
  flagd:
    sidecarContainers:
      - name: flagd-ui
        useDefault:
          env: true
        resources:
          limits:
            memory: 100Mi
```
