### ISSUE TITLE
[collector] Scrape internal telemetry metrics with Prometheus

### ISSUE THREAD

**Issue by davgia** [open-telemetry/opentelemetry-helm-charts#1595]
Hi,

I have deployed the opentelemetry-operator chart (version: 0.84.0) and I have added a Collector CRD with the following manifest:

``` yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: [REDACTED]
spec:
  mode: deployment
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "environment"
                operator: In
                values:
                  - [REDACTED]
  env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:POD_IP}:4317
          http:
            endpoint: ${env:POD_IP}:4318
    extensions:
      health_check:
        endpoint: ${env:POD_IP}:13133
    processors:
      batch: {}
    exporters:
      otlp:
        endpoint: tempo.monitoring:4317
        tls:
          insecure: true
    service:
      extensions:
        - health_check
      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - otlp
      telemetry:
        metrics:
          address: ${env:POD_IP}:8888
```
As you can see above I have enabled the endpoint to expose internal collector metrics. The problem is that Prometheus does not scrape the endpoint by default. I would probably need to annotate the service with:
``` yaml
annotations: 
  prometheus.io/scrape: "true"
  prometheus.io/port: "8888"
```
but I am struggling to find the documentation about the collector configuration.

Is there a README file/equivalent file/link that explains the entire collector configuration?

Thanks!
