### ISSUE TITLE
[opentelemetry-kube-stack] enabling internal metrics of collectors

### ISSUE THREAD

**Issue by sinux-l5d** [open-telemetry/opentelemetry-helm-charts#1618]
Hello,

When enabling ServiceMonitor via `defaultCRConfig.observability.metrics.enableMetrics`, it doesn't add the following to the Collectors config :
```yaml
service:
  telemetry:
      metrics:
        readers:
          - pull:
              exporter:
                prometheus:
                  host: '0.0.0.0'
                  port: 8888
```

Without this, Prometheus gets a connection refused

**Comment by jaronoff97** [comment]
this is going to be updated in the next release of the operator, right now with the version of the operator and collector set this should still work. Keep an eye out for https://github.com/open-telemetry/opentelemetry-operator/issues/3861

**Comment by sinux-l5d** [comment]
Hello @jaronoff97, thanks to pointing me where this should be resolved. However, I'm struggling to find where this issue was solved.

Do you mean that in release v0.122.1 of the operator, it should now generate `.spec.service.telemetry.metrics` on its own when `.observability.metrics.enableMetrics` is enabled?

**Comment by jaronoff97** [comment]
the operator rewrites it now by default during an upgrade https://github.com/open-telemetry/opentelemetry-operator/pull/3874

**Comment by jaronoff97** [comment]
hmmm i wonder if this was a version of this bug? https://github.com/open-telemetry/opentelemetry-operator/issues/3913 

I haven't been able to test this out yet but if there's a minimal reproduction with 0.123.0 of the operator could you open an issue there and I or another team member could take a look?

**Comment by ethanmdavidson** [comment]
I don't think it's that bug, because I do have some log settings that haven't been clobbered (`logs.encoding` and `logs.level`), plus in that bug there's no mention of the double-set metrics address. 

I don't have time to make a minimal reproduction. Sorry if this comes across as a drive-by, but I thought it would be good to at least give you a heads up and share the workaround in case anyone else hits it. I understand that you can't do anything about it without more info; luckily the workaround is pretty painless :)

**Comment by jaronoff97** [comment]
np! thanks for sharing :bow: I'll flag this for the team and let them know.

**Comment by iblancasa** [comment]
I'm unable to reproduce the issue. I followed this steps:
1. Created a kind cluster
2. Installed cert-manager
3. Installed the 0.79.0 version of the helm chart for the operator: ` helm upgrade --install otel-operator open-telemetry/opentelemetry-operator --version 0.79.0 --set manager.collectorImage.repository=otel/opentelemetry-collector-contrib`
4. Created an OpenTelemetry Collector instance:
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: test
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    processors:

    exporters:
      debug: {}

    extensions:

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [debug]
```
4. The config is applied properly:
```yaml
        telemetry:
          metrics:
            address: 0.0.0.0:8888
```
5. Upgraded the operator `helm upgrade --install otel-operator open-telemetry/opentelemetry-operator --version 0.86.1 --set manager.collectorImage.repository=otel/opentelemetry-collector-contrib`
6. Wait for the upgrade and check the new applied configuration:
```yaml
      telemetry:
        metrics:
          readers:
          - pull:
              exporter:
                prometheus:
                  host: 0.0.0.0
                  port: 8888
```
