### ISSUE TITLE
opentelemetry-operator chart helm values schema does not allow unset CPU limits

### ISSUE THREAD

**Issue by chancez** [open-telemetry/opentelemetry-helm-charts#1621]
Just trying to upgrade to the the latest chart with a minimal values yaml fails because of the following error:

values;
```
manager:
  collectorImage:
    repository: otel/opentelemetry-collector-contrib
  serviceMonitor:
    enabled: true
```

Chart version: `0.84.2`

Error:

```
Error: Error: values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-operator:
- manager.resources.limits.cpu: Invalid type. Expected: string, given: null
- kubeRBACProxy.resources.limits.cpu: Invalid type. Expected: string, given: null
```

https://github.com/open-telemetry/opentelemetry-helm-charts/blob/f3ea561df5ccd0569f7424638608a94e198c6277/charts/opentelemetry-operator/values.schema.json#L1477-L1484

As you can see the helm values schema defines this type as a "string". But, it's actually a StringOrInt, _and_ it should be nullable.

The correct schema is something like:
```
"type": ["string", "number", "null"]
```

**Comment by chancez** [comment]
This is only coming up now, despite the schema having these restrictions for a while because the chart was configuring defaults previously: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/UPGRADING.md#0790-to-0800

**Comment by TylerHelmuth** [comment]
I'm confused as why setting `cpu: null` is desired/necessary. Since the chart no longer sets default resources, this configuration should work:

```yaml
manager:
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

kubeRBACProxy:
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi
```

When I test locally this renders

```yaml
resources: 
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
```
