### ISSUE TITLE
[collector] Consider a preset for logs+metrics collection based on annotation discovery

### ISSUE THREAD

**Issue by ChrsMark** [open-telemetry/opentelemetry-helm-charts#1634]
With https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36581 we added support for [enabling receivers based on discovered annotations](https://opentelemetry.io/blog/2025/otel-collector-k8s-discovery/).

Specifically we provide support:
- for collecting logs from k8s containers by dynamically starting filelog receiver instances when Pods' are annotated properly
- collecting metrics by dynamically starting metrics specific receivers like `nginx`, `redis` etc based on provided annotations

It would be nice to provide a seamless way for enabling this feature through a preset when deploying the Collector using the Helm Chart. 

This can be a new preset called `annotationDiscovery` like the following:

```yaml
annotationDiscovery:
  logs: {}
  metrics: {}
```

This should generate config sections that include the following:
- enabling `k8s_observer`
- adding volumes and volume mounts for logs collection
- adding the `receiver_creator` receivers
- ensuring the clusterRole is present
- pipelines are tuned properly

```yaml
mode: daemonset

clusterRole:
  create: true
  rules:
   - apiGroups:
     - ''
     resources:
     - 'pods'
     - 'nodes'
     verbs:
     - 'get'
     - 'list'
     - 'watch'
   - apiGroups: [ "" ]
     resources: [ "nodes/proxy"]
     verbs: [ "get" ]
   - apiGroups:
       - ""
     resources:
       - nodes/stats
     verbs:
       - get
   - nonResourceURLs:
       - "/metrics"
     verbs:
       - get

extraVolumeMounts:
 - name: varlogpods
   mountPath: /var/log/pods
   readOnly: true

extraVolumes:
  - name: varlogpods
    hostPath:
      path: /var/log/pods

config:
  extensions:
    k8s_observer:
      auth_type: serviceAccount
      node: ${env:K8S_NODE_NAME}

  receivers:

    receiver_creator/metrics:
      watch_observers: [ k8s_observer ]
      discovery:
        enabled: true
      receivers:
    
    receiver_creator/logs:
      watch_observers: [ k8s_observer ]
      discovery:
        enabled: true
      receivers:

  service:
    extensions: [health_check, k8s_observer]
    pipelines:
     metrics:
        receivers: [ receiver_creator/metrics ]
        exporters: [ ]

      logs/discovery:
        receivers: [ receiver_creator/logs ]
        exporters: []
```

In addition, for logs the preset should ensure that supersedes the [`logCollection`](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/ae9b3e59946b2dd75a6af55e2017bb665cd39560/charts/opentelemetry-collector/README.md?plain=1#L109) preset to ensure there won't be log duplication (the 2 presets are mutually exclusive).

**Comment by TylerHelmuth** [comment]
This sounds like a good complex situation that the preset concept can help with. We need to make sure it stays opinionated - the presets should really only have boolean toggles to control options.

**Comment by TylerHelmuth** [comment]
I'm curious to understand more about the logs scenario

**Comment by ChrsMark** [comment]
> I'm curious to understand more about the logs scenario

The [logCollection](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/ae9b3e59946b2dd75a6af55e2017bb665cd39560/charts/opentelemetry-collector/README.md?plain=1#L109) preset adds a filelog `receiver` configuration that matches all containers' logs paths:


```yaml
receivers:
  filelog:
    include: [ /var/log/pods/*/*/*.log ]
    ...
```

Then if we enable the annotation discovery all the annotated target Pods will have their logs being collected twice, one by the above receiver instance and one by the instance that is dynamically created by the annotations' discovery.

Users enabling the annotation discovery strategy should only rely on this for logs' collection and not on the [logCollection](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/ae9b3e59946b2dd75a6af55e2017bb665cd39560/charts/opentelemetry-collector/README.md?plain=1#L109) preset.

I think we could just raise a warning if both are enabled?

**Comment by rogercoll** [comment]
> I think we could just raise a warning if both are enabled?

Or even an error, which preset should take precedence if both enabled? Also, the configuration should be flexible enough to allow `metrics` autodiscovery + all culster logs (logsCollection preset).


The current `logCollection` preset has additional features like the [storeCheckpoints](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/ae9b3e59946b2dd75a6af55e2017bb665cd39560/charts/opentelemetry-collector/values.yaml#L34) to store read file-offsets. Should these features be available in the logs discovery preset as well?

**Comment by TylerHelmuth** [comment]
Ya we can error in `NOTES.txt`.

**Comment by ChrsMark** [comment]
> I like the metrics discovery part. I'm not really sure what is the use-case for logs one? Given logsCollection preset collect everything, why do we need autodiscovery?

The `receivercreator` supports logs collection based on annotation discovery. Through annotations users can enable log collection and define specific configuration per Pod/Container. An example can be found at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/receivercreator/README.md#define-configuration-1.

This will just be an alternative to what `logsCollection` preset does, which under the hood will leverage the `receivercreator`'s feature.

**Comment by ChrsMark** [comment]
> [@ChrsMark](https://github.com/ChrsMark) can you post what you think the preset configuration would be? I suspect it would need a user to supply a string annotation and we've typically been very against configuration in the presets that needs more than booleans.

From the Collector's side we don't need to specify anything like this.

The basic use-case that the preset will cover will only have booleans. If users need more extensive configuration then they will need to build it manually.

I gave an example originally at https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1634#issue-3002469511 but here is a more complete one to illustrate how the preset would be defined:

Example:

```yaml
presets:
  annotationDiscovery:
    logs:
      enabled: true
    metrics:
      enabled: true
```

I intentionally make `logs` and `metrics` objects to leave space for the future in case we want to add more boolean flags, but for now just the enable/disable "toggle" should be enough.

The above would be the equivalent of the following:

```yaml
mode: daemonset

clusterRole:
  create: true
  rules:
   - apiGroups:
     - ''
     resources:
     - 'pods'
     verbs:
     - 'get'
     - 'list'
     - 'watch'

extraVolumeMounts:
 - name: varlogpods
   mountPath: /var/log/pods
   readOnly: true

extraVolumes:
  - name: varlogpods
    hostPath:
      path: /var/log/pods

config:
  extensions:
    k8s_observer:
      auth_type: serviceAccount
      node: ${env:K8S_NODE_NAME}

  receivers:
    receiver_creator/metrics:
      watch_observers: [ k8s_observer ]
      discovery:
        enabled: true
      receivers:
    
    receiver_creator/logs:
      watch_observers: [ k8s_observer ]
      discovery:
        enabled: true
      receivers:

  service:
    extensions: [health_check, k8s_observer]
    pipelines:
     metrics:
        receivers: [ receiver_creator/metrics ]
        exporters: [ ]

      logs/discovery:
        receivers: [ receiver_creator/logs ]
        exporters: []
```
