### ISSUE TITLE
Missing upstream otel/opentelemetry-collector-k8s:0.123.1 image for release 0.122.0

### ISSUE THREAD

**Issue by jmoses** [open-telemetry/opentelemetry-helm-charts#1635]
I'm unable to install the latest helm chart release, as docker hub is missing the expected image.

```
    state:
      waiting:
        message: Back-off pulling image "otel/opentelemetry-collector-k8s:0.123.1"
        reason: ImagePullBackOff
```

![Image](https://github.com/user-attachments/assets/a895dbb7-5b04-4891-8e6e-1ace57218df7)
