### ISSUE TITLE
K8s attributes labels disappeared in latest chart

### ISSUE THREAD

**Issue by dima-sh-papaya** [open-telemetry/opentelemetry-helm-charts#1642]
Hi, we're using the [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector) chart with K8s attributes enabled,
```
presets:
  kubernetesAttributes:
    enabled: true
```

after updating to latest version, the extra labels from prometheus metrics have disappeared, so in our other clusters I can still see those labels and in the one I upgraded we don't have them. Here is the example: 
**Before**:
```
otelcol_process_cpu_seconds{attributes="k8s.namespace.name=\"xyz\", k8s.deployment.name=\"xyz\", k8s.container.name=\"otel-collector\", k8s.pod.name=\"xyz\", k8s.node.name=\"xyz\"",service_instance_id="xyz",service_name="otelcol-contrib",service_version="0.121.0"} 97.13
```
**After**:
```
otelcol_process_cpu_seconds_total{otel_scope_name="go.opentelemetry.io/collector/service",otel_scope_version=""} 3.26
```

The labels are different, but config remains the same (Helm values for the chart), how can we find the upgrade guide, for required config changes? I scrolled a few latest commits in the repo but cannot see other changes except the `telemetry.metrics.address. -> .readers` one.  Also nothing in the [upgrade guide](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/UPGRADING.md) about that. 

The version is: 
```
info	service@v0.123.0/service.go:264	Starting otelcol-contrib...	{"Version": "0.123.0", "NumCPU": 4}
```

**Comment by dima-sh-papaya** [comment]
The related config part looks like this

```
  service:
    telemetry:
      metrics:
        readers:
        - pull:
            exporter:
              prometheus:
                host: $${env:MY_POD_IP}
                port: 8888
      resource:
        attributes: >-
          k8s.namespace.name="xyz",
          k8s.deployment.name="xyz",
          k8s.container.name="otel-collector",
          k8s.pod.ip="$${env:MY_POD_IP}",
          k8s.node.name="$${env:K8S_NODE_NAME}"
```

**Comment by dima-sh-papaya** [comment]
updated the image to a new repo as shown in changelog readme file, now have a single metric that has the attributes:

```
target_info{attributes="k8s.namespace.name=\"xyz\", k8s.deployment.name=\"xyz\", k8s.container.name=\"xyz\", k8s.pod.ip=\"xyz\", k8s.node.name=\"xyz\"",service_instance_id="xyz",service_name="otelcol-contrib",service_version="0.124.1"} 1
```
but all other metrics don't have it. could be a bug of some kind? or just a config issue? 

here's the presets section we use, I only need the attributes so all others disabled: 
```
presets:
  kubernetesEvents:
    enabled: false
  kubernetesAttributes:
    enabled: true
  kubeletMetrics:
    enabled: false
  logsCollection:
    enabled: false
```

**Comment by TylerHelmuth** [comment]
I wonder if we broke something with https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1564. Are you scraping the collector's metrics with the chart's default prometheus receiver and then those metrics pass through the k8sattributes processor?

**Comment by TylerHelmuth** [comment]
I think we need:

```
  service:
    telemetry:
      metrics:
        readers:
        - pull:
            exporter:
              prometheus:
                host: $${env:MY_POD_IP}
                port: 8888
                with_resource_constant_labels:
                  included: [<all your metric names]
```
Can you try that?

**Comment by dima-sh-papaya** [comment]
> I wonder if we broke something with [#1564](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1564). Are you scraping the collector's metrics with the chart's default prometheus receiver and then those metrics pass through the k8sattributes processor?


Yes, the final configMap that the helm chart renders when I use the above values, looks like this, so it creates the processor that looks for metadata: 

```
processors:
      batch:
        send_batch_max_size: 500
        send_batch_size: 200
        timeout: 5000ms
      k8sattributes:
        extract:
          metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.pod.start_time
        filter:
          node_from_env_var: K8S_NODE_NAME
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection
      memory_limiter:
        check_interval: 5s
        limit_percentage: 90
        spike_limit_percentage: 25
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:14250
          thrift_compact:
            endpoint: ${env:MY_POD_IP}:6831
          thrift_http:
            endpoint: ${env:MY_POD_IP}:14268
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${env:MY_POD_IP}:8888
      zipkin:
        endpoint: ${env:MY_POD_IP}:9411
    service:
      extensions:
      - health_check
      - file_storage/cache
      pipelines:
        logs:
          exporters:
          - otlp/elastic
          processors:
          - k8sattributes
          - batch
          receivers:
          - otlp
        metrics:
          exporters:
          - prometheusremotewrite
          processors:
          - k8sattributes
          - batch
          receivers:
          - otlp
        traces:
          exporters:
          - otlp/elastic
          processors:
          - k8sattributes
          - batch
          receivers:
          - otlp
      telemetry:
        metrics:
          address: ${env:MY_POD_IP}:8888
        resource:
          attributes: k8s.namespace.name="otel", k8s.deployment.name="otel-collector",
            k8s.container.name="otel-collector", k8s.pod.ip="${env:MY_POD_IP}", k8s.node.name="${env:K8S_NODE_NAME}"

```

I can try the config you suggest, does it need to be in addition to all the existing values I use or should I turn off some of them? 
Also, in `included: [<all your metric names>]` the metric names are those that I need from the collector itself correct? like the `otelcol_exporter_send_failed_log_records`?

**Comment by dima-sh-papaya** [comment]
oh, actually this is configMap from my current reverted version, I've put the "0.117.1" back, so will need to upgrade again and check what it will show in config map.

**Comment by dima-sh-papaya** [comment]
I tried the suggested now, in 0.122.2, but it had no effect, the metrics on 8888 look the same after applying the latest chart version and this part of config map: 
```
      telemetry:
        metrics:
          readers:
          - pull:
              exporter:
                prometheus:
                  host: ${env:MY_POD_IP}
                  port: 8888
                  with_resource_constant_labels:
                    included:
                    - k8s.node.name
                    - k8s.pod.ip
                    - k8s.container.name
```

the rest of config looks the same 🤔 . no labels of k8s metadata on metrics.

**Comment by TylerHelmuth** [comment]
@dima-sh-papaya can you provide a minimal config for me to test with

**Comment by dima-sh-papaya** [comment]
> [@dima-sh-papaya](https://github.com/dima-sh-papaya) can you provide a minimal values.yaml for me to test with

sure I can share all of it, here's my current, I install with terraform.  these values are for 0.117.1 , and the moment I upgrade to  0.122.2 (with replacing the docker image repo as required, and putting the 'latest' tag) k8s labels will disappear (even with the with_resource_constant_labels part of the telemetry.metrics.readers):

```
...
resource "helm_release" "opentelemetry-collector" {
  name       = "otel"
  repository = "https://open-telemetry.github.io/opentelemetry-helm-charts"
  chart      = "opentelemetry-collector"
  namespace  = "otel"
  depends_on = [kubernetes_namespace.open-telemetry]
  max_history = 3
  version = "0.117.1"
  values = [
<<EOF
mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.121.0

resources:
  limits:
    cpu: 200m
    memory: 256Mi

extraVolumes:
  - name: otel-storage
    emptyDir: {}

extraVolumeMounts:
  - name: otel-storage
    mountPath: /var/lib/otel-collector/cache

presets:
  kubernetesEvents:
    enabled: false
  kubernetesAttributes:
    enabled: true
  kubeletMetrics:
    enabled: false
  logsCollection:
    enabled: false

# turn off jaeger and zipkin ports
ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
  metrics:
    enabled: true

config:
  receivers:
    # disable default receivers
    jaeger: {}
    zipkin: {}
    # enable only otlp
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        # disable http
        http:

  extensions:
    file_storage/cache:
      directory: /var/lib/otel-collector/cache
      timeout: 10s
    health_check:
      endpoint: $${env:MY_POD_IP}:13133

  processors:
    batch:
      timeout: 5000ms
      send_batch_size: 200
      send_batch_max_size: 500
    memory_limiter:
      check_interval: 5s
      limit_percentage: 90
      spike_limit_percentage: 25
  exporters:
      otlp/elastic:
        endpoint: {the elasticsearch url where we export spans and logs}
        timeout: 20s
        headers:
          Authorization: "ApiKey {from aws secrets api key value}"
        sending_queue:
          queue_size: 20000
          storage: file_storage/cache
        retry_on_failure:
          enabled: true
          initial_interval: 15s
          max_interval: 30s
          max_elapsed_time: 15m
      prometheusremotewrite:
        endpoint: "http://prometheus-server.prometheus.svc.cluster.local/api/v1/write"
        timeout: 10s
        external_labels:
          cluster: "${data.terraform_remote_state.eks.outputs.cluster_name}"
          env: "${var.environment}"
        tls:
          insecure: true
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 15m
        resource_to_telemetry_conversion:
          enabled: true
  service:
    extensions:
      - health_check
      - file_storage/cache
    telemetry:
      metrics:
        address: $${env:MY_POD_IP}:8888
      resource:
        attributes: >-
          k8s.namespace.name="otel",
          k8s.deployment.name="otel-collector",
          k8s.container.name="otel-collector",
          k8s.pod.ip="$${env:MY_POD_IP}",
          k8s.node.name="$${env:K8S_NODE_NAME}"
    pipelines:
      logs:
        receivers:
          - otlp
        processors:
          - batch
        exporters:
          - otlp/elastic
      metrics:
        receivers:
          - otlp
        processors:
          - batch
        exporters:
          - prometheusremotewrite
      traces:
        receivers:
          - otlp
        processors:
          - batch
        exporters:
          - otlp/elastic
EOF
  ]
}

```

you can remove the elasticsearch related section and storage stuff (i'm using disk queue for caching spans and logs), and add the required 'telemetry.metrics' configs. thanks 🙏

**Comment by TylerHelmuth** [comment]
@dima-sh-papaya is this definitely the config that was working before? If your metrics pipeline is

```
      metrics:
        receivers:
          - otlp
        processors:
          - batch
        exporters:
          - prometheusremotewrite
```
then it wont have the prometheusreceiver so the collector's internal metrics will not be scraped by this collector.

**Comment by TylerHelmuth** [comment]
Also, I'm not familiar with terraform, but the config for `service.telemetry.resources` does not include the key `attributes`: https://github.com/open-telemetry/opentelemetry-collector/blob/112b889f86966dab9613a640f5e12f282127e1dd/service/telemetry/config.go#L39C2-L39C10

**Comment by TylerHelmuth** [comment]
@dima-sh-papaya I have been unable to reproduce your issue. On v0.122.2 of the helm chart and the following config I see the collector's internal telemetry with the expected attributes:

```yaml
mode: daemonset

image:
  repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib

presets:
  kubernetesAttributes:
    enabled: true

ports:
  metrics:
    enabled: true

config:
  exporters:
    debug:
      verbosity: detailed
  service:
    telemetry:
      metrics:
        address: ${env:MY_POD_IP}:8888
      resource:
        k8s.namespace.name: "otel"
        k8s.deployment.name: "otel-collector"
        k8s.container.name: "otel-collector"
        k8s.pod.ip: "${env:MY_POD_IP}"
        k8s.node.name: "${env:K8S_NODE_NAME}"
```

**Comment by dima-sh-papaya** [comment]
> [@dima-sh-papaya](https://github.com/dima-sh-papaya) is this definitely the config that was working before? If your metrics pipeline is
> 
> ```
>       metrics:
>         receivers:
>           - otlp
>         processors:
>           - batch
>         exporters:
>           - prometheusremotewrite
> ```
> 
> then it wont have the prometheusreceiver so the collector's internal metrics will not be scraped by this collector.

oh, those are values of the helm chart, but later that chart produces this actual config in k8s configMap:

```
    service:
      extensions:
      - health_check
      - file_storage/cache
      pipelines:
        logs:
          exporters:
          - otlp/elastic
          processors:
          - k8sattributes
          - batch
          receivers:
          - otlp
        metrics:
          exporters:
          - prometheusremotewrite
          processors:
          - k8sattributes
          - batch
          receivers:
          - otlp
        traces:
          exporters:
          - otlp/elastic
          processors:
          - k8sattributes
          - batch
          receivers:
          - otlp
      telemetry:
        metrics:
          address: ${env:MY_POD_IP}:8888
        resource:
          attributes: k8s.namespace.name="otel", k8s.deployment.name="otel-collector",
            k8s.container.name="otel-collector", k8s.pod.ip="${env:MY_POD_IP}", k8s.node.name="${env:K8S_NODE_NAME}"
```

the 'k8sattributes' processor gets added by the helm chart rendering I think based on the 
```

presets:
  kubernetesEvents:
    enabled: false
  kubernetesAttributes:
    enabled: true
```

I thought you were asking about helm values so pasted only the values for the chart, not the actual config. The config gets rendered a bit differen. Here's the full config: 


```
data:
  relay: |
    exporters:
      debug: {}
      otlp/elastic:
        endpoint: https://......
        headers:
          Authorization: ApiKey ..........
        retry_on_failure:
          enabled: true
          initial_interval: 15s
          max_elapsed_time: 15m
          max_interval: 30s
        sending_queue:
          queue_size: 20000
          storage: file_storage/cache
        timeout: 20s
      prometheusremotewrite:
        endpoint: http://prometheus-server.prometheus.svc.cluster.local/api/v1/write
        external_labels:
          cluster: eks
          env: production
        resource_to_telemetry_conversion:
          enabled: true
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_elapsed_time: 15m
          max_interval: 30s
        timeout: 10s
        tls:
          insecure: true
    extensions:
      file_storage/cache:
        directory: /var/lib/otel-collector/cache
        timeout: 10s
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    processors:
      batch:
        send_batch_max_size: 500
        send_batch_size: 200
        timeout: 5000ms
      k8sattributes:
        extract:
          metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.pod.start_time
        filter:
          node_from_env_var: K8S_NODE_NAME
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection
      memory_limiter:
        check_interval: 5s
        limit_percentage: 90
        spike_limit_percentage: 25
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:14250
          thrift_compact:
            endpoint: ${env:MY_POD_IP}:6831
          thrift_http:
            endpoint: ${env:MY_POD_IP}:14268
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${env:MY_POD_IP}:8888
      zipkin:
        endpoint: ${env:MY_POD_IP}:9411
    service:
      extensions:
      - health_check
      - file_storage/cache
      pipelines:
        logs:
          exporters:
          - otlp/elastic
          processors:
          - k8sattributes
          - batch
          receivers:
          - otlp
        metrics:
          exporters:
          - prometheusremotewrite
          processors:
          - k8sattributes
          - batch
          receivers:
          - otlp
        traces:
          exporters:
          - otlp/elastic
          processors:
          - k8sattributes
          - batch
          receivers:
          - otlp
      telemetry:
        metrics:
          address: ${env:MY_POD_IP}:8888
        resource:
          attributes: k8s.namespace.name="otel", k8s.deployment.name="otel-collector",
            k8s.container.name="otel-collector", k8s.pod.ip="${env:MY_POD_IP}", k8s.node.name="${env:K8S_NODE_NAME}"

```

and about the 'telemetry.resource.attributes' it's probably a remainder of when I tried to make it work and could've pulled it from some old thread or stackoverflow 🙈 , in any case, this config works unless gets updated to latest helm chart version, so there's something broken 🧐 somewhere.

**Comment by dima-sh-papaya** [comment]
> [@dima-sh-papaya](https://github.com/dima-sh-papaya) in the rendered config you don't have a prometheus receiver to scrape the collector's internal metrics so they would never make it to the k8sattributes processor:
> 
> ```
> metrics:
>           exporters:
>           - prometheusremotewrite
>           processors:
>           - k8sattributes
>           - batch
>           receivers:
>           - otlp
> ```
> 
> is something else scraping the prometheus endpoint to get your collector's internal metrics?

oh, interesting, I see what you mean, those metrics aren't pushed together with all application metrics to prometheus and are coming from the scrape config, yes, prometheus itself reaching out to port 8888 and reading those metrics of the collectors, because if collector is dead in terms of issues with queue or whatnot (the "failure to send" alerts to be triggered) it won't push its own metrics to prometheus and we'll never know that it was failing, so those are scraped externally on the port by prometheus itself. 

```
extraScrapeConfigs: |
  - job_name: 'otel-collector'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - otel
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_component]
        action: keep
        regex: agent-collector
      - source_labels: [__meta_kubernetes_pod_ip]
        target_label: __address__
        regex: (.*)
        replacement: $1:8888
```

and the k8sattributes processor you mean will only work on all other otlp metrics that are going through the collector? I see... but still it doesn't really explain why labels exist in the old chart version and don't exist in the new one?
