### ISSUE TITLE
Opentelemetry helm chart upgrade from version 0.12.1 to 0.13.1 breaks jaeger traces receiver

### ISSUE THREAD

**Issue by sesto** [open-telemetry/opentelemetry-helm-charts#167]
We use 2 receivers in our configuration, jaeger and otel. Jaeger receiver is used to receive traces from traefik ingress controller because it does not support opentelemetry yet. 
After helm chart upgrade to version 0.13.1 jaeger traces receiver stopped working in agent collector, while otel collector works as expected.
The following error is logged in the traefik ingress:
`{"level":"error","msg":"Tracing jaeger error: failed to flush Jaeger spans to server: write udp 10.123.35.47:44543-\u003e10.123.46.29:6831: write: connection refused","time":"2022-04-13T09:51:34Z","tracingProviderName":"jaeger"}`

Relevant configuration:
```
opentelemetry-collector:
  config:
    receivers:
       otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      jaeger:
        protocols:
          thrift_compact:
            endpoint: 0.0.0.0:6831
  ports:
    otlp-http:
      enabled: true
    jaeger-compact:
      enabled: true
      containerPort: 6831
      servicePort: 6831
      hostPort: 6831
      protocol: UDP
  
   agentCollector:
      service:
        pipelines:
          traces:
            receivers: [otlp, jaeger]

**Comment by TylerHelmuth** [comment]
Chart version 0.13.1 updated the default collector version to 0.48.0.  I am curious, if you use chart version 0.13.1 but set the image back to 0.47.0 what happens?

```yaml
image:
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.47.0"
```

Similarly what happens if you use chart version 0.12.1 but update the collector version to 0.48.0?

```yaml
image:
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.48.0"
```

**Comment by sesto** [comment]
Both 0.13.1 + 0.47.0 and 0.12.1 + 0.48.0 do not work. In fact, these combination are not compatible and produce errors in opentelelmetry-collector:
```
2022-04-13T18:44:26.655Z	error	exporterhelper/queued_retry_inmemory.go:106	Exporting failed. No more retries left. Dropping data.	{"kind": "exporter", "name": "otlp", "error": "max elapsed time expired rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup opentelemetry-collector on 10.122.0.2:53: no such host\"", "dropped_items": 35}
```
Strangely enough, the above mentioned error in the traefik log disappear in both combinations

**Comment by TylerHelmuth** [comment]
The most recent error makes it seem like the collector is not able to export data to 10.122.0.2:53.  Your setup is currently working on default 0.12.1?

**Comment by sesto** [comment]
I have tested all combinations again:
version 0.12.1 with default image (0.47.0) works correctly;
all other combinations 0.13.1 with default image (0.48.0), 0.13.1 + 0.47.0 and 0.12.1 + 0.48.0 produce the same error:
```
2022-04-13T18:44:26.655Z	error	exporterhelper/queued_retry_inmemory.go:106	Exporting failed. No more retries left. Dropping data.	{"kind": "exporter", "name": "otlp", "error": "max elapsed time expired rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup opentelemetry-collector on 10.122.0.2:53: no such host\"", "dropped_items": 35}
```
I could not reproduce the very first error 
```
{"level":"error","msg":"Tracing jaeger error: failed to flush Jaeger spans to server: write udp 10.123.35.47:44543-\u003e10.123.46.29:6831: write: connection refused","time":"2022-04-13T09:51:34Z","tracingProviderName":"jaeger"}
```
It was most likely caused by intermittent network issue

**Comment by TylerHelmuth** [comment]
Is the configuration provided in the description your entire values.yaml?  If not, but you share all of it?  Can you also provide the collector logs?

What triggers this error?  Is it during startup or when data is sent to the collector?

**Comment by sesto** [comment]
Full values.yaml

```
opentelemetry-collector:
  # This allowes the k8sattributes processor to enrich the telemtry data with metadata
  clusterRole:
    create: true
    rules:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list", "watch"]
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      jaeger:
        protocols:
          thrift_compact:
            endpoint: 0.0.0.0:6831
      prometheus: null
      zipkin: null
    service:
      pipelines:
        metrics:
          receivers: [otlp]

  ports:
    otlp-http:
      enabled: true
    jaeger-compact:
      enabled: true
      containerPort: 6831
      servicePort: 6831
      hostPort: 6831
      protocol: UDP
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false
  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/alias: "true"
      kubernetes.io/ingress.class: traefik-internal

  agentCollector:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 500Mi
    extraEnvs:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "host.name=$(NODE_NAME)"
    configOverride:
      exporters:
        otlp:
          endpoint: "opentelemetry-collector:4317"
          tls:
            insecure: true
      processors:
        # The k8sattributes in the Agent is in passthrough mode
        # so that it only tags with the minimal info for the
        # collector k8sattributes to complete
        k8sattributes:
          passthrough: true
        # Overwrite the host.name tag with the k8s node name as specified in OTEL_RESOURCE_ATTRIBUTES env var
        resourcedetection:
          detectors: [env]
          timeout: 5s
          override: true
      service:
        pipelines:
          traces:
            receivers: [otlp, jaeger]
            processors: [memory_limiter, resourcedetection, k8sattributes, batch]
            exporters: [otlp]

  standaloneCollector:
    enabled: true
    replicaCount: 3
    resources:
      requests:
        cpu: 200m
        memory: 400Mi
      limits:
        cpu: 1
        memory: 2Gi
    extraEnvs:
      - name: DD_API_KEY
        valueFrom:
          secretKeyRef:
            name: opentelemetry-collector
            key: datadog-api-key
    configOverride:
      exporters:
        datadog:
          api:
            site: datadoghq.eu
          env: dev
      processors:
        batch:
          timeout: 10s
        k8sattributes: {}
        # The translation of opentelemetry traces to Datadog traces for server spans
        # forms a Datadog resource using a combination of http.method + http.route.
        # However the io.opentelemetry.javaagent.tomcat-7.0 library only set http.method, and not http.route
        # This makes it hard to distinguish health calls from actual traffic.
        # We will copy the span name to the http.route attribute (but only if the attribute does not already exist)
        # 1. Extract the route from the span name to a temporary attribute
        span/extract_route:
          include:
            match_type: regexp
            libraries:
              - { name: "^io\\.opentelemetry(\\.javaagent)?\\.tomcat-7\\.0" }
          name:
            to_attributes:
              rules:
                - ^(?P<http_path_temp>.*)
        # 2. Copy the temporary attribute to the http.route attribute
        attributes/insert_route:
          include:
            match_type: regexp
            libraries:
              - { name: "^io\\.opentelemetry(\\.javaagent)?\\.tomcat-7\\.0" }
          actions:
            - key: "http.route"
              from_attribute: http_path_temp
              action: insert
        # 3. span/extract_route will replace the span name with {http_path_temp}, restore it back to its original value.
        span/restore_name:
          include:
            match_type: regexp
            libraries:
              - { name: "^io\\.opentelemetry(\\.javaagent)?\\.tomcat-7\\.0" }
          name:
            from_attributes: [http_path_temp]
        # 4. Delete temporary attribute
        attributes/delete_http_path_temp:
          include:
            match_type: regexp
            libraries:
              - { name: "^io\\.opentelemetry(\\.javaagent)?\\.tomcat-7\\.0" }
          actions:
            - key: "http_path_temp"
              action: delete
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors:
              [
                batch,
                k8sattributes,
                span/extract_route,
                attributes/insert_route,
                span/restore_name,
                attributes/delete_http_path_temp,
              ]
            exporters: [datadog]
```
