### ISSUE TITLE
[opentelemetry-kube-stack] Support for 'extraObjects'

### ISSUE THREAD

**Issue by JorTurFer** [open-telemetry/opentelemetry-helm-charts#1686]
I'm trying to use Secret CSI Driver with the current chart to provide the required secrets to collectors, but currently there isn't any mechanism that I can use to deploy extra configuration that I need.

I do know that adding 3rd party CRDs is something not allowed (and honestly, it's a great decision), but something like a 'extraObjects' parameter that can be used to add arbitrary manifests without having to couple the current chart it it looks as a good option to not coupling this chart, but giving flexibility to end-users to extend the chart without forking it.

For example, in KEDA we have a file like this -> https://github.com/kedacore/charts/blob/main/keda/templates/extensibility/extra-manifests.yaml

```helm
{{ range .Values.extraObjects }}
---
{{ tpl (toYaml .) $ }}
{{ end }}
```

that can be used as:

```yaml
extraObjects: 
- apiVersion: secrets-store.csi.x-k8s.io/v1
  kind: SecretProviderClass
  metadata:
    name: demo
    namespace: test-app
  spec:
    parameters:
      objects: >
        - secretPath: xxxxxxx/data/registry-credentials
          objectName: "imagePullSecret"
          secretKey: registry-credentials
      vaultAddress: xxxxxxx
    provider: vault
    secretObjects:
      - data:
          - key: .dockerconfigjson
            objectName: imagePullSecret
        secretName: demo-image-pull-secrets
        type: kubernetes.io/dockerconfigjson
```

Thanks to this approach, this chart is not attached to any other CRD, but it's extensible for end-users. For example, the case of an external secret provider, could be managed just adding an extraIObject that generates the secret using the 3rd party and then, just with volumes/volumeMounts/extraEnvs, those secrets can be injected into the workload.

I know that I can deploy the secret related stuff by myself in a different way, but conceptually the secrets are part of the workload that I'm deploying with this chart, and don't make sense without it. Their lifecycles are directly related and deploying both together would be nice without having to maintain my own fork of the chart.

I'm willing to open a PR with the changes if you agree with the feature
