### ISSUE TITLE
[opentelemetry-kube-stack] Cannot exclude collector logs with logsCollection preset

### ISSUE THREAD

**Issue by dysfungi** [open-telemetry/opentelemetry-helm-charts#1697]
Disabling any [.presets.logsCollection.includeCollectorLogs](https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-kube-stack/0.6.1?modal=values&path=defaultCRConfig.presets.logsCollection.includeCollectorLogs) does not work for [OpenTelemetry Kube Stack Helm Chart v0.6.1](https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-kube-stack/0.6.1) with any collector mode.

I believe I narrowed this down to the container name for the exclude rule being set to the Chart name (defaults to `opentelemetry-kube-stack`) instead of `otc-container`, which is said to be the container name in the [Operator API Docs](https://github.com/open-telemetry/opentelemetry-operator/blob/1c2913a/docs/api/opentelemetrycollectors.md#opentelemetrycollectorspec).

My daemonset OpenTelemetryCollector CRD YAML snippet:
```
    receivers:
      filelog:
        exclude: /var/log/pods/observability_opentelemetry-kube-stack-daemon*_*/opentelemetry-kube-stack/*.log
        include:
        - /var/log/pods/*/*/*.log
```

My daemonset YAML snippet:
```
      containers:
      - args:
        - --config=/conf/collector.yaml
        image: otel/opentelemetry-collector-k8s:0.120.0
        name: otc-container
```

One of my log filepaths:
```
log.file.path:
    /var/log/pods/observability_opentelemetry-kube-stack-daemon-collector-wzjz6_51637406-3496-4291-a188-39e9fa8523d4/otc-container/0.log
```

From [OpenTelemetryCollector (v1beta1) API](https://github.com/open-telemetry/opentelemetry-operator/blob/1c2913a/docs/api/opentelemetrycollectors.md#opentelemetrycollectorspec-1):

> Container names managed by the operator:
>
> - `otc-container`
>

From [OpenTelemetry Kube Stack Helm Chart _config.tpl](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/4c6e67e/charts/opentelemetry-kube-stack/templates/_config.tpl#L20):

> ```
> {{- if .collector.presets.logsCollection.enabled }}
> {{- $_ := set $collector "exclude" (printf "/var/log/pods/%s_%s*_*/%s/*.log" .namespace (include "opentelemetry-kube-stack.collectorFullname" .) (.Chart.Name | lower)) }}
> ```
