### ISSUE TITLE
[Opentelemetry-operator] Provision a TLS Certificate for the OpenTelemetry Operator with a values file

### ISSUE THREAD

**Issue by sjoerdhooft** [open-telemetry/opentelemetry-helm-charts#1702]
I want to provide my own generated certificate for the opentelemetry-operator. I'm using helmfile to generate the manifest and using the following values file:

```yaml
admissionWebhooks:
  certManager:
    enabled: false
  autoGenerateCert:
    enabled: false
  certFile: "../otel/operator.crt"
  keyFile: "../otel/operator.key"
  caFile: "../otel/ca.crt"
```

However, when creating the manifest the data section inside the tls object is empty:

```yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    helm.sh/chart: opentelemetry-operator-0.89.0
    app.kubernetes.io/name: opentelemetry-operator
    app.kubernetes.io/version: "0.125.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: opentelemetry-operator
    app.kubernetes.io/instance: opentelemetry-operator
    app.kubernetes.io/component: webhook
  name: opentelemetry-operator-controller-manager-service-cert
  namespace: ops
data:
  tls.crt: 
  tls.key: 
  ca.crt:
```

Previously we let helm generate the secret, and then the data section had the generated certificate information. Can you help me?
