### ISSUE TITLE
use unexposed port to check healthy

### ISSUE THREAD

**Issue by caibirdme** [open-telemetry/opentelemetry-helm-charts#172]
in _pod.tpl
```yaml
    livenessProbe:
      httpGet:
        path: /
        port: 13133
    readinessProbe:
      httpGet:
        path: /
        port: 13133
```
But port 13133 is not exposed
