### ISSUE TITLE
ExistingPath does not work

### ISSUE THREAD

**Issue by tehlers320** [open-telemetry/opentelemetry-helm-charts#1737]
I have a chart wrapped in a chart wrapped in a chart.... (i know fun right).... anyways

if i put 
```
otelcol:
  opentelemetry-collector:
    configMap:
      existingPath: "templates/configMap.yaml" # this is set just to highlight the problem
```

I get 
```
entelemetry-collector.configTemplateChecksumAnnotation" at <include (print $.Template.BasePath "/" .Values.configMap.existingPath) .>: error calling include: template: no template "otelcol/charts/otelcol/charts/opentelemetry-collector/templates/templates/configMap.yaml" associated with template "gotpl"

```

I believe the function here:
```
checksum/config: {{ include (print $.Template.BasePath "/" .Values.rcp-otelcol.opentelemetry-collector.configMap.existingPath) . | sha256sum }}
```

helm docs say
```
Template.BasePath: The namespaced path to the templates directory of the current chart (e.g. mychart/templates).
```

i dont have any work-arounds right now.
