### ISSUE TITLE
CrashLoopBackoff error when starting pod

### ISSUE THREAD

**Issue by Sandeepb-nextcar** [open-telemetry/opentelemetry-helm-charts#176]
Error: failed to start container "opentelemetry-collector": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/otelcol-contrib": stat /otelcol-contrib: no such file or directory: unknown

**Comment by TylerHelmuth** [comment]
Hello @Sandeepb-nextcar, can you provide more details on the issue you are having?  What version of the charts are you using, what does your values.yaml look like?

**Comment by Sandeepb-nextcar** [comment]
I deployed otel agent as a daemonset and while starting up i'm seeing Crashloopbackoff error. I'm using the latest version.

Values.yaml
config:
  processors:
    resourcedetection:
      detectors: [env]
      timeout: 5s
      override: false
    k8sattributes:
      passthrough: true
    batch:
      timeout: 10s
  service:
    pipelines:
      traces:
        processors: [batch, resourcedetection, k8sattributes]

image:
  repository: otel/opentelemetry-collector-contrib
  pullPolicy: IfNotPresent
  tag: latest

extraEnvs:
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: "k8s.pod.ip=$(POD_IP)"

agentCollector:
  configOverride:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      processors:
        batch:
          timeout: 10s
        resourcedetection:
          detectors: [ec2, system]
      exporters:
        datadog/api:
          env: qa
          tags:
            - service:test
          api:
            key: "0b2624a632b1278e3b57de2619ef7130"

      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch, resourcedetection, k8sattributes]
            exporters: [datadog/api]

**Comment by TylerHelmuth** [comment]
What happens if you set `image.tag` to `0.48.0` instead of `latest`

**Comment by TylerHelmuth** [comment]
Are you running this in k8s or a kind cluster?

**Comment by Sandeepb-nextcar** [comment]
we are running on EKS, when i ran this yesterday it did pick 0.48.0, however i did apply again today which picked latest but still the same issue.

**Comment by TylerHelmuth** [comment]
Did this break with helm chart 0.14.1 or is this your first time installing?

**Comment by Sandeepb-nextcar** [comment]
Nope we had other environment running fine on version 0.8.1

**Comment by Sandeepb-nextcar** [comment]
and Yes using recent chart version it failed with the error.

**Comment by TylerHelmuth** [comment]
If you go back to the previous version that was working does it still work?

**Comment by Sandeepb-nextcar** [comment]
it did work

**Comment by TylerHelmuth** [comment]
I was only able to reproduce this issue on chart version 0.14.1 if `tag` is set to `latest`.  If `tag` is `0.48.0` then I could install your values.yaml as expected.

Here is the yaml I was able to install successfully

```yaml
config:
  processors:
    resourcedetection:
      detectors: [env]
      timeout: 5s
      override: false
    k8sattributes:
      passthrough: true
    batch:
      timeout: 10s
  service:
    pipelines:
      traces:
        processors: [batch, resourcedetection, k8sattributes]

image:
  repository: otel/opentelemetry-collector-contrib
  pullPolicy: IfNotPresent
  tag: 0.48.0

extraEnvs:
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: "k8s.pod.ip=$(POD_IP)"

agentCollector:
  configOverride:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
        timeout: 10s
      resourcedetection:
        detectors: [ec2, system]
    exporters:
      datadog/api:
        env: qa
        tags:
          - service:test
        api:
          key: "asdafsdf"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, resourcedetection, k8sattributes]
          exporters: [datadog/api]
```
