### ISSUE TITLE
Allow for a setting such as `useExistingConfigMap`

### ISSUE THREAD

**Issue by snuggie12** [open-telemetry/opentelemetry-helm-charts#196]
I see a few other issues (#90 and #158) related to the default config but this is a slightly different approach.

We use other tools to handle creating the config for otel-collector and would like a setting where the helm chart does not create a configmap but uses whatever I input as the configmap to load in.

example can be found here: https://github.com/prometheus-community/helm-charts/blob/ee700113d070664053bb041f97ae5356e6072fe6/charts/kube-prometheus-stack/values.yaml#L427

**Comment by TylerHelmuth** [comment]
@snuggie12 thanks for the request.  Do you want to work on this?

**Comment by dmitryax** [comment]
This must be resolved by presets. 

1. disable default presets
2. provide custom config

cc @TylerHelmuth

**Comment by TylerHelmuth** [comment]
@dmitryax that would work, but this issue reads to me like they don't want the helm chart generating a configmap at all.  Sounds like that want an option for the collector to not generate a configmap and let them provide their own values for

```yaml
volumes:
  - name: opentelemetry-collector-configmap
    configMap:
      name: example-opentelemetry-collector-agent
      items:
        - key: relay
          path: relay.yaml
```

and

```yaml
containers:
  - name: opentelemetry-collector
    command:
      - /otelcol-contrib
      - --config=/conf/relay.yaml
```
