### ISSUE TITLE
Can not see container logs

### ISSUE THREAD

**Issue by NanyinK** [open-telemetry/opentelemetry-helm-charts#198]
Hello,

I would like to enable container logs and I've enabled the values like shown below : 
{
mode: daemonset

containerLogs:
  enabled: true

image:
  repository: otel/opentelemetry-collector-contrib

command:
  name: otelcol-contrib
}

but after my agent & standalone are running, there are no contents in the path I mount.( yet I can see the container & log folders were created )

I can see the logs normally from the pod : 
{
2022-05-06T08:49:59.335Z        info    builder/receivers_builder.go:73 Receiver started.       {"kind": "receiver", "name": "zipkin"}
2022-05-06T08:49:59.335Z        info    healthcheck/handler.go:129      Health Check state change       {"kind": "extension", "name": "health_check", "status": "ready"}
2022-05-06T08:49:59.335Z        info    service/collector.go:249        Starting otelcol-contrib...     {"Version": "0.49.0", "NumCPU": 4}
2022-05-06T08:49:59.335Z        info    service/collector.go:145        Everything is ready. Begin running and processing data.
2022-05-06T08:50:06.348Z        INFO    loggingexporter/logging_exporter.go:56  MetricsExporter {"#metrics": 14}
2022-05-06T08:50:16.365Z        INFO    loggingexporter/logging_exporter.go:56  MetricsExporter {"#metrics": 22}
2022-05-06T08:50:26.383Z        INFO    loggingexporter/logging_exporter.go:56  MetricsExporter {"#metrics": 22}
2022-05-06T08:50:36.400Z        INFO    loggingexporter/logging_exporter.go:56  MetricsExporter {"#metrics": 22}
2022-05-06T08:50:46.418Z        INFO    loggingexporter/logging_exporter.go:56  MetricsExporter {"#metrics": 22}
2022-05-06T08:50:56.436Z        INFO    loggingexporter/logging_exporter.go:56  MetricsExporter {"#metrics": 22}
}

Could any one help troubleshoot?

Thanks a lot.

**Comment by TylerHelmuth** [comment]
@NanyinK Thanks for the issue. We moved it here bc it seemed related to the helm charts. 

Couple questions:

1. What version of the charts are you using?
2. What does the collector's configmap look like?
3. Does the opened issue contain the entire values.yaml?

I have a suspicion that the collector has the filelog receiver configured but it's not in the logs pipeline.

**Comment by NanyinK** [comment]
Hi @TylerHelmuth ,

Please take a look at the answers below : 

1. What version of the charts are you using?
0.6.9
2. What does the collector's configmap look like?
It's the default one, I didnt change anything in the configmap. I just modified the mode & the host mount path in _pod.tpl
3. Does the opened issue contain the entire values.yaml?
I'm afraid I didnt get this question, shall I upload the values.yaml here?

Besides the things I mentioned above, anything else I need to change?

Thanks a lot for your help

**Comment by NanyinK** [comment]
FYI, this is the agent configmap : 
===========================================================

Name:         ot-collector-agent-opentelemetry-collector-agent
Namespace:    ot
Labels:       app.kubernetes.io/instance=ot-collector-agent
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=opentelemetry-collector
              app.kubernetes.io/version=0.49.0
              helm.sh/chart=opentelemetry-collector-0.15.1
Annotations:  meta.helm.sh/release-name: ot-collector-agent
              meta.helm.sh/release-namespace: ot

Data
====
relay:
----
exporters:
  logging: {}
extensions:
  health_check: {}
  memory_ballast:
    size_mib: "819"
processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_mib: 1638
    spike_limit_mib: 512
receivers:
  filelog:
    exclude:
    - /var/log/pods/ot_ot-collector-agent-opentelemetry-collector*_*/opentelemetry-collector/*.log
    include:
    - /var/log/pods/*/*/*.log
    include_file_name: false
    include_file_path: true
    operators:
    - id: get-format
      routes:
      - expr: $$body matches "^\\{"
        output: parser-docker
      - expr: $$body matches "^[^ Z]+ "
        output: parser-crio
      - expr: $$body matches "^[^ Z]+Z"
        output: parser-containerd
      type: router
    - id: parser-crio
      output: extract_metadata_from_filepath
      regex: ^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) (?P<log>.*)$
      timestamp:
        layout: "2006-01-02T15:04:05.000000000-07:00"
        layout_type: gotime
        parse_from: time
      type: regex_parser
    - id: parser-containerd
      output: extract_metadata_from_filepath
      regex: ^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) (?P<log>.*)$
      timestamp:
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        parse_from: time
      type: regex_parser
    - id: parser-docker
      output: extract_metadata_from_filepath
      timestamp:
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        parse_from: time
      type: json_parser
    - id: extract_metadata_from_filepath
      parse_from: $$attributes["file.path"]
      regex: ^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]+)\/(?P<container_name>[^\._]+)\/(?P<run_id>\d+)\.log$
      type: regex_parser
    - attributes:
        k8s.container.name: EXPR($.container_name)
        k8s.namespace.name: EXPR($.namespace)
        k8s.pod.name: EXPR($.pod_name)
        k8s.pod.uid: EXPR($.uid)
        run_id: EXPR($.run_id)
        stream: EXPR($.stream)
      type: metadata
    - id: clean-up-log-body
      ops:
      - move:
          from: log
          to: $
      type: restructure
    start_at: beginning
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector
        scrape_interval: 10s
        static_configs:
        - targets:
          - ${MY_POD_IP}:8888
  zipkin:
    endpoint: 0.0.0.0:9411
service:
  extensions:
  - health_check
  - memory_ballast
  pipelines:
    logs:
      exporters:
      - logging
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
    metrics:
      exporters:
      - logging
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
      - prometheus
    traces:
      exporters:
      - logging
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
      - jaeger
      - zipkin
  telemetry:
    metrics:
      address: 0.0.0.0:8888

Events:  <none>

**Comment by TylerHelmuth** [comment]
I believe my suspicion is correct, the filelog receiver is not in the logs pipeline. 

This can be fixed by adding it to your .Values.config 

'''yaml
config:
  service:
    pipelines:
      logs:
        receivers:
          - otlp
          - filelog
'''

**Comment by TylerHelmuth** [comment]
Also, it is strange that your chart version is 0.6.9 as that is the opentelemetry-operator chart latest release, but your values.yaml and configmap look like they are from the opentelemetry-collector chart.  What command are you using to install the chart?

**Comment by NanyinK** [comment]
Hello @TylerHelmuth 

I'm afraid that it has already been added there by default (in the _config.tpl)
![image](https://user-images.githubusercontent.com/66045363/167261689-486b467a-6aa1-47ff-8433-118a9d7dcd71.png)
is it the correct file to add ?

and for the version, sorry it's 0.15.1

**Comment by TylerHelmuth** [comment]
You're correct that it is there in _config.tpl, but in the same file where the template is used, you can see that whatever is in .Values.config overrides the template. Checkout #199 for an explanation on why this is happening and how to fix it.

**Comment by NanyinK** [comment]
Hi @TylerHelmuth 

I think I get you, yet could you tell me how to add it to my .Values.config?

Sorry I'm new to helm, and not familiar with it. I’m also googling to find the way.

**Comment by NanyinK** [comment]
also I tired to add it here (in the last line)

```
config:
  exporters:
    logging: {}
  extensions:
    health_check: {}
    memory_ballast: {}
  processors:
    batch: {}
    # If set to null, will be overridden with values based on k8s resource limits
    memory_limiter: null
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_http:
          endpoint: 0.0.0.0:14268
        thrift_compact:
          endpoint: 0.0.0.0:6831
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    prometheus:
      config:
        scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
              - targets:
                  - ${MY_POD_IP}:8888
    zipkin:
      endpoint: 0.0.0.0:9411
  service:
    telemetry:
      metrics:
        address: 0.0.0.0:8888
    extensions:
      - health_check
      - memory_ballast
    pipelines:
      logs:
        exporters:
          - logging
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - filelog
```

but I get this error when running it
```
2022/05/09 01:49:46 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/05/09 01:49:46 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
2022-05-09T01:49:46.456Z        info    builder/exporters_builder.go:255        Exporter was built.     {"kind": "exporter", "name": "logging"}
2022-05-09T01:49:46.456Z        info    memorylimiterprocessor/memorylimiter.go:111     Memory limiter configured       {"kind": "processor", "name": "memory_limiter", "pipeline": "traces", "limit_mib": 1638, "spike_limit_mib": 512, "check_interval": 5}
2022-05-09T01:49:46.456Z        info    builder/pipelines_builder.go:224        Pipeline was built.     {"kind": "pipeline", "name": "traces"}
2022-05-09T01:49:46.456Z        info    builder/pipelines_builder.go:224        Pipeline was built.     {"kind": "pipeline", "name": "logs"}
2022-05-09T01:49:46.457Z        info    builder/pipelines_builder.go:224        Pipeline was built.     {"kind": "pipeline", "name": "metrics"}
Error: cannot build receivers: cannot create receiver filelog: unmarshal to regex_parser: unrecognized prefix
2022/05/09 01:49:46 collector server run finished with error: cannot build receivers: cannot create receiver filelog: unmarshal to regex_parser: unrecognized prefix
```

**Comment by NanyinK** [comment]
[ot-collector-agent.tar.gz](https://github.com/open-telemetry/opentelemetry-helm-charts/files/8649461/ot-collector-agent.tar.gz)

this is my helm chart, could you please take a look if needed.

**Comment by NanyinK** [comment]
I also changed the value in examples (add logfile there)
[charts/opentelemetry-collector/examples/daemonset-collector-logs/values.yaml]

but the issue is still there.

**Comment by TylerHelmuth** [comment]
I'm not sure how you are using helm, but it is non-standard to have the charts in a folder named `ot-collector-agent`.  Normally you add a chart repository to helm using the `helm repo add` command.  This will let you interact with the chart via `helm install` or `helm template` commands.  Also, chart users normally only configure the output of a chart via the `values.yaml` file; it is not best practice to be modifying anything in the chart.

For this chart and this use case, the best practice would be:

1. Add the opentelemetry-helm-charts repo:
 `helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts`
2. Create a `values.yaml` file that contains the configuration you want.  In this instance, I think your values.yaml would contain
```yaml
mode: daemonset

config:
  service:
    pipelines:
      logs:
        receivers:
          - otlp
          - filelog

containerLogs:
  enabled: true
```
3. Run either a `helm install` or `helm template` command with the opentelemetry-collector chart, passing in your values .yaml.  
`helm install open-telemetry/opentelemetry-collector --values <path to your values.yaml>`
`helm template open-telemetry/opentelemetry-collector --values <path to your values.yaml>`
