### ISSUE TITLE
memory_limiter configuration

### ISSUE THREAD

**Issue by dudicoco** [open-telemetry/opentelemetry-helm-charts#208]
Hi,

The chart configures the memory parameters for `memory_limiter` automatically as a percentage of the defined resource limits via templating functions: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/ce2098bfb05a269a6b1cc53d9aff29c352f94a91/charts/opentelemetry-collector/templates/_config.tpl#L8-L12

I was wondering why `limit_percentage` and `spike_limit_percentage` were not used instead, as they can already calculate the percentage automatically, according to https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiterprocessor/README.md

**Comment by TylerHelmuth** [comment]
I don't have a reason other than that the current solution is working so there hasn't been a push to change it.  Are you experiencing an issue with the current solution?

I like the idea of simplifying the _config.tpl file, there is currently a lot of logic going into the limit setting.  If percentages would produce the same end result it could be a great change.

**Comment by dudicoco** [comment]
@TylerHelmuth this is actually an issue in the collector repo as well: https://github.com/open-telemetry/opentelemetry-collector/blob/c368d497a2046011da4a39ee977ceed5f841c266/examples/k8s/otel-config.yaml#L28-L33

I wonder if even the percentage parameters work properly with detecting k8s resource limits?
I didn't try these myself yet so I have no idea if they do.
It also doesn't state if these were tested with k8s in https://github.com/open-telemetry/opentelemetry-collector/pull/1622 which added this functionality.

**Comment by dudicoco** [comment]
I've tested `limit_percentage`, `spike_limit_percentage` and the `memory_ballast` `size_in_percentage` parameters with k8s and they are all working as expected.

**Comment by TylerHelmuth** [comment]
Great! Are you able to post any test results?

**Comment by dudicoco** [comment]
Sure.

Container resources:
```yaml
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 2Gi
```

Config file:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 75
    spike_limit_percentage: 25
  batch: {}

exporters:
  logging:
    loglevel: debug

extensions:
  health_check:
     endpoint: 0.0.0.0:13133
  memory_ballast:
    size_in_percentage: 20

service:
  pipelines:
    traces:
      receivers:
      - otlp
      # the order processors are specified in a pipeline is important as this is the order in which each processor is applied
      processors:
      - memory_limiter  # the memory_limiter processor should be the first processor defined in the pipeline
      - batch  # the batch processor should be defined in the pipeline after the memory_limiter as well as any sampling processors
      exporters:
      - logging
  # extensions are going to be loaded by the service in the order given below, and shutdown on reverse order
  extensions:
  - health_check
  - memory_ballast
  telemetry:
    logs:
      level: debug
    metrics:
      level: detailed
      address: 0.0.0.0:8888
```

Container logs:
```log
2022-05-22T18:24:29.716Z	info	memorylimiterprocessor/memorylimiter.go:143	Using percentage memory limiter	{"kind": "processor", "name": "memory_limiter", "pipeline": "traces", "total_memory_mib": 2048, "limit_percentage": 75, "spike_limit_percentage": 25}
2022-05-22T18:24:29.717Z	info	memorylimiterprocessor/memorylimiter.go:111	Memory limiter configured	{"kind": "processor", "name": "memory_limiter", "pipeline": "traces", "limit_mib": 1536, "spike_limit_mib": 512, "check_interval": 5}
2022-05-22T18:24:29.719Z	info	extensions/extensions.go:38	Extension is starting...	{"kind": "extension", "name": "memory_ballast"}
2022-05-22T18:24:29.728Z	info	ballastextension/memory_ballast.go:52	Setting memory ballast	{"kind": "extension", "name": "memory_ballast", "MiBs": 409}
2022-05-22T18:24:29.728Z	info	extensions/extensions.go:42	Extension started.	{"kind": "extension", "name": "memory_ballast"}
```
