### ISSUE TITLE
Disable metrics and logging pipelines is not working as expected in Helm chat 0.18.0

### ISSUE THREAD

**Issue by AnujAroshA** [open-telemetry/opentelemetry-helm-charts#223]
As mentioned in the [basic top level configuration section in the document](https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-collector#basic-top-level-configuration), we have set _null_ values as below.

```
      pipelines:
        traces:
          receivers:
            - otlp
          processors: {}
          exporters:
            - jaeger
            - logging
        metrics: null
        logs: null
```
But when I see the ConfigMap it shows all the pipelines.

```
  pipelines:
    logs:
      exporters:
      - logging
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
    metrics:
      exporters:
      - logging
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
      - prometheus
    traces:
      exporters:
      - jaeger
      - logging
      processors: {}
      receivers:
      - otlp
```

What we need is to get rid of _logs_ and _metrics_ and keep only _traces_.

Following are details of my testing environment, even though some of those are not directly impact with the issue.

- macOS Monterey (Version 12.4)
- Docker Desktop (4.8.2)
- Kubectl (1.24 both Client and Server)
- Helm v3.8.0

**Comment by TylerHelmuth** [comment]
Are you using "mode" or "agentCollector"/"standaloneCollector"?

**Comment by TylerHelmuth** [comment]
I was able to run this command and successfully disable the logs and metrics pipeline

`helm template testing open-telemetry/opentelemetry-collector --values ./charts/opentelemetry-collector/examples/deployment-otlp-traces/values.yaml`

```yaml
# Source: opentelemetry-collector/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: testing-opentelemetry-collector
  labels:
    helm.sh/chart: opentelemetry-collector-0.16.2
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: testing
    app.kubernetes.io/version: "0.50.0"
    app.kubernetes.io/managed-by: Helm
data:
  relay: |
    exporters:
      logging: {}
    extensions:
      health_check: {}
      memory_ballast: {}
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_mib: 1638
        spike_limit_mib: 512
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      extensions:
      - health_check
      - memory_ballast
      pipelines:
        traces:
          exporters:
          - logging
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
      telemetry:
        metrics:
          address: 0.0.0.0:8888
```

I was also able to remove logs and metrics pipeline when using standaloneCollector and agentCollector.  

Can you provide more details on the commands you are running and your full values.yaml?

**Comment by AnujAroshA** [comment]
> I was able to run this command and successfully disable the logs and metrics pipeline
> 
> `helm template testing open-telemetry/opentelemetry-collector --values ./charts/opentelemetry-collector/examples/deployment-otlp-traces/values.yaml`
> 
> ```yaml
> # Source: opentelemetry-collector/templates/configmap.yaml
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: testing-opentelemetry-collector
>   labels:
>     helm.sh/chart: opentelemetry-collector-0.16.2
>     app.kubernetes.io/name: opentelemetry-collector
>     app.kubernetes.io/instance: testing
>     app.kubernetes.io/version: "0.50.0"
>     app.kubernetes.io/managed-by: Helm
> data:
>   relay: |
>     exporters:
>       logging: {}
>     extensions:
>       health_check: {}
>       memory_ballast: {}
>     processors:
>       batch: {}
>       memory_limiter:
>         check_interval: 5s
>         limit_mib: 1638
>         spike_limit_mib: 512
>     receivers:
>       otlp:
>         protocols:
>           grpc:
>             endpoint: 0.0.0.0:4317
>           http:
>             endpoint: 0.0.0.0:4318
>     service:
>       extensions:
>       - health_check
>       - memory_ballast
>       pipelines:
>         traces:
>           exporters:
>           - logging
>           processors:
>           - memory_limiter
>           - batch
>           receivers:
>           - otlp
>       telemetry:
>         metrics:
>           address: 0.0.0.0:8888
> ```
> 
> I was also able to remove logs and metrics pipeline when using standaloneCollector and agentCollector.
> 
> Can you provide more details on the commands you are running and your full values.yaml?

My values file related to otel-collector part is as below
```
opentelemetry-collector:
  mode: deployment
  ports: 
    otlp: 
      enabled: true
    otlp-http: 
      enabled: true
    jaeger-compact: 
      enabled: false
    jaeger-grpc: 
      enabled: false
    jaeger-thrift: 
      enabled: false
    metrics: 
      enabled: false
    zipkin:
      enabled: false
  config:
    exporters:
      jaeger:
        endpoint: otel-jaeger-collector:14250
        tls:
          insecure: true
    extensions:
      health_check: {}
    processors: {}
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      prometheus: {}
      jaeger: null   
      zipkin: null
    service:
      extensions:
        - health_check
      pipelines:
        traces:
          receivers:
            - otlp
          processors: {}
          exporters:
            - jaeger
            - logging
        metrics: null
        logs: null
```

**Comment by TylerHelmuth** [comment]
I am able to use your values.yaml and turn off metrics and logs.  Here is the resulting configmap after running `helm template opentelemetry-collector open-telemetry/opentelemetry-collector --values ./values.yaml --output-dir testing`

```yaml
---
# Source: opentelemetry-collector/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector
  labels:
    helm.sh/chart: opentelemetry-collector-0.20.0
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: opentelemetry-collector
    app.kubernetes.io/version: "0.53.0"
    app.kubernetes.io/managed-by: Helm
data:
  relay: |
    exporters:
      jaeger:
        endpoint: otel-jaeger-collector:14250
        tls:
          insecure: true
      logging: {}
    extensions:
      health_check: {}
      memory_ballast: {}
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_mib: 1638
        spike_limit_mib: 512
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${MY_POD_IP}:8888
    service:
      extensions:
      - health_check
      pipelines:
        traces:
          exporters:
          - jaeger
          - logging
          processors: {}
          receivers:
          - otlp
      telemetry:
        metrics:
          address: 0.0.0.0:8888
```

What command are you using?

**Comment by AnujAroshA** [comment]
Command I used 
`helm template otel helm/values.local.yaml --output-dir testing`

Chart.yaml Otel related configuration

```
dependencies:
  - name: opentelemetry-collector
    alias: collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.x.x

```

One thing that I noticed is, we are pointing to `apiVersion: v2` and seems you are pointing to `v1`

I have added the values.yaml changes in a previous comment.
