### ISSUE TITLE
Additional property enabled is not allowed with Json Schema validation.

### ISSUE THREAD

**Issue by JaredTan95** [open-telemetry/opentelemetry-helm-charts#228]
I use opentelemtry-collector chart as a subchart like this:

```yaml
dependencies:
  - name: opentelemetry-collector
    version: 0.20.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: opentelemetry-operator
    version: 0.7.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
```

and my `values.yaml` as following:

```yaml
opentelemetry-collector:
  enabled: false
  mode: deployment
······
  resources:
    limits:
      cpu: 1
      memory: 2Gi
```

```bash
helm install ...  --set opentelemetry-collector.enabled=true 
```

but I got some errors:

```bash
opentelemetry-collector:
- (root): Additional property enabled is not allowed
```

I think it caused by this https://github.com/open-telemetry/opentelemetry-helm-charts/blob/7b9f67bd6e1c9280deb7132edd091b5714f70bdb/charts/opentelemetry-collector/values.schema.json#L5
 
maybe set it to `true` can fix it.

```yaml
"additionalProperties": true
```

related issue:
- https://github.com/helm/helm/issues/10392

**Comment by TylerHelmuth** [comment]
The error is coming from the fact that `enabled` is being passed in to the chart in the root of the values.yaml but `enabled` is not a valid field in the chart's values.  

What is the purpose of `enabled` in this context?  The opentelemetry-collector chart has no knowledge of that field and will not respect it being true or false.  Is something else expecting that field and making decisions using it?

**Comment by JaredTan95** [comment]
> The error is coming from the fact that `enabled` is being passed in to the chart in the root of the values.yaml but `enabled` is not a valid field in the chart's values.
> 
> What is the purpose of `enabled` in this context? The opentelemetry-collector chart has no knowledge of that field and will not respect it being true or false. Is something else expecting that field and making decisions using it?

Sorry, I lost this in dependencies config:

```yaml
dependencies:
  - name: opentelemetry-collector
    version: 0.20.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector.enabled 👈
```

We can use `--set opentelemetry-collector.enabled=true`  to decide whether to install opentelemetry-collector or not.
