### ISSUE TITLE
pipeline "traces" references processor batch which does not exist

### ISSUE THREAD

**Issue by jjangga0214** [open-telemetry/opentelemetry-helm-charts#23]
## How it behaves

Processor is not defined. 

## How it should behave

Processor should be defined.

### Configuration

```yaml
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
  processors:
    batch:
    memory_limiter:
      ballast_size_mib: 70
      check_interval: 5s
      limit_mib: 170
      spike_limit_mib: 20
  exporters:
    jaeger:
      endpoint: jaeger-collector:14250
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [jaeger]
```

### Error

```shell
➜  capa-viewer git:(ops/tracing) ✗ (☸ |kind-kind:operations) kubectl get pod               
NAME                                                        READY   STATUS             RESTARTS   AGE
opentelemetry-collector-agent-8kzwp                         1/2     CrashLoopBackOff   6          9m27s

➜  capa-viewer git:(ops/tracing) ✗ (☸ |kind-kind:operations) kubectl logs opentelemetry-collector-agent-8kzwp opentelemetry-collector 
{"level":"info","ts":1608967307.530805,"caller":"service/service.go:396","msg":"Starting OpenTelemetry Collector...","Version":"latest","GitHash":"a85c7a2d","NumCPU":4}
{"level":"info","ts":1608967307.5512323,"caller":"service/service.go:577","msg":"Using memory ballast","MiBs":204}
{"level":"info","ts":1608967307.551373,"caller":"service/service.go:240","msg":"Setting up own telemetry..."}
{"level":"info","ts":1608967307.6330154,"caller":"service/telemetry.go:108","msg":"Serving Prometheus metrics","address":"0.0.0.0:8888","legacy_metrics":false,"new_metrics":true,"level":0,"service.instance.id":"0cc8ea06-3312-48d1-9328-677ea81065c9"}
{"level":"info","ts":1608967307.635118,"caller":"service/service.go:277","msg":"Loading configuration..."}
Error: cannot load configuration: pipeline "traces" references processor batch which does not exist
2020/12/26 07:21:47 application run finished with error: cannot load configuration: pipeline "traces" references processor batch which does not exist
```
