### ISSUE TITLE
command extra args makes users confusion.

### ISSUE THREAD

**Issue by JaredTan95** [open-telemetry/opentelemetry-helm-charts#270]
I found https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/templates/_pod.tpl#L13 that configuration file  `--config=/conf/relay.yaml` always takes effect.

It makes confusion when the user configures additional parameters, like :
```yaml
  command:
    name: otelcol-contrib
    extraArgs: ["--config=/conf/custom/config.yaml"]
```

and this will eventually come into effect:
```yaml
          command:
            - /otelcol-contrib
            - '--config=/conf/relay.yaml'
            - '--config=/conf/custom/config.yaml'
```

I think we can refactor this logical here?

**Comment by TylerHelmuth** [comment]
@JaredTan95 the `--config=/conf/relay.yaml` is hard coded because it is the configuration from `.Values. config`.  If you want to modify the collectors configuration you should do it with a values.yaml and using the `config` field.  

Do you have a use case where modifying the collector's configuration via the values.yaml is not sufficient and you need to use a second configuration file?

**Comment by JaredTan95** [comment]
In some cases, we want to inject k8s metadata or use `.global values` when helm install, as follows:

```yaml
config:
    processors:
      batch: {}
      attributes/insert:
        actions:
          - key: "kube-system-id"
            value: {{ (lookup "v1" "Namespace" "" "kube-system").metadata.uid }}
            action: insert
...
  exporters:
    otlp: {{ .Values.global.xxxxx }}
``` 

It will not take effect.
