### ISSUE TITLE
opentelemetry demo chart supoort imageOverride

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-helm-charts#290]
Thanks for the effort on opentelemetry-demo charts,@wph95, I have some cases of reimplementing demo service with more features like integrating into sentinel for rate limiting. current charts need more flexibility adapt it, if it worth to do ,I would like to help it.

the `value.yaml` probably like this:
```
components:
  adService:
    enabled: true
    imageOverride: myCustom:v0.0.1
    servicePort: 8080
```

and the `_objects.tpl` will need a little change:
```
···
containers:
  - name: {{ .name }}
    {{- if .imageOverride }}
    image: {{ .imageOverride }}
    {{- else }}
    image: {{ .image | default (printf "%s:v%s-%s" .imageConfig.repository .Chart.AppVersion (.name | replace "-" "" | lower)) }}
    {{- end }}
    {{- end }}
···
```
