### ISSUE TITLE
otel demo env schema supports extracting k8s metadata.

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-helm-charts#303]
In some scenarios, we want to add some [Pod and container fields](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/) into `OTEL_RESOURCE_ATTRIBUTES` enviroment in some components, like namespace name, node name, pod name, which can help us understand a service's running metadata and also show the span attrubute's usage scenarios. 

a demo values.yaml like:
```
components:
  adService:
    enabled: true
    servicePort: 8080
  env:
    - name: OTEL_K8S_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: OTEL_K8S_CPU_REQUEST
      valueFrom:
        resourceFieldRef:
          containerName: test-container
          resource: requests.cpu
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: k8s.namespace.name=$(OTEL_K8S_NAMESPACE),k8s.cpu.requests=$(OTEL_K8S_CPU_REQUEST)
```

current `values.yaml` schema only support `name` `value` in `env` section:
```
        "Env": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            },
            "required": [
                "name"
            ],
            "title": "Env"
        }
```

I propose to add [env.valueFrom](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#environment-variables) into the schema for catching the feature described above.
