### ISSUE TITLE
[opentelemetry-operator] Issue overriding ServiceAccount

### ISSUE THREAD

**Issue by davidgp1701** [open-telemetry/opentelemetry-helm-charts#313]
If the user overrides the ServiceAccount creation for the Open Telemetry Operator in a value file like this:

```yaml
manager:
  serviceAccount:
    create: false
    name: test
```

The ClusterRoleBinding resource is created correctly:

```yaml
# Source: opentelemetry-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: opentelemetry-operator
  name: opentelemetry-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentelemetry-operator-proxy-role
subjects:
  - kind: ServiceAccount
    name: test-controller-manager
    namespace: default
```

But the `ServiceAccountName` in the `spec` section of the deployment is set incorrectly:

```yaml
# Source: opentelemetry-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: opentelemetry-operator
    control-plane: controller-manager
  name: opentelemetry-operator-controller-manager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-operator
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: opentelemetry-operator
        control-plane: controller-manager
    spec:
      hostNetwork: false
      containers:
      [...]
      serviceAccountName: opentelemetry-operator-controller-manager
      [...]
```
    
As you can see in the last lines of this example: `serviceAccountName: opentelemetry-operator-controller-manager` when that service account does not exists and it should be set to `serviceAccountName: test-controller-manager`.
