### ISSUE TITLE
Headless service for the agent

### ISSUE THREAD

**Issue by renatomjr** [open-telemetry/opentelemetry-helm-charts#35]
How do you usually configure the tracing SDK exporter to point to the agent? Wouldn't be a good idea to include a headless service for the agent?
My stack is: SDK -> Agent -> Standalone Collector

**Comment by krak3n** [comment]
I too am wondering this, the only thing I have come across so far would be exposing the `HOST_IP` to the pod via environment variables, so for example your app deployment would have something like this:

``` yaml
env:
- name: HOST_IP
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
```

This way your nodes IP would be known to the application.

**Comment by mars64** [comment]
re: loadbalanced otel-collector endpoint, I just wanted to highlight a comment from the linked thread ^^ https://github.com/open-telemetry/opentelemetry-helm-charts/issues/79#issuecomment-924197449

As such, @krak3n 's solution is probably more correcterer.

**Comment by renatomjr** [comment]
Closing. @krak3n's solution is certainly the best approach.
I met my need with [env interpolation](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/#define-an-environment-dependent-variable-for-a-container):

```
env:
- name: HOST_IP
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
- name: TRACER_COLLECTOR_URL
  value: http://$(HOST_IP):55681/v1/trace
```
