### ISSUE TITLE
[opentelemetry-operator]  use self-signed cert not works well.

### ISSUE THREAD

**Issue by JaredTan95** [open-telemetry/opentelemetry-helm-charts#351]
As described from https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/README.md#tls-certificate-requirement 3rd way.

We deploy as following sets:
```bash
helm install \
  my-opentelemetry-operator open-telemetry/opentelemetry-operator \
--set admissionWebhooks.certManager.enabled=false
```

and we also create tls by `kubectl create secret tls...`

but the `opentelemetry-operator` pod occurs error :
`TLS handshake error from 10.233.96.0:39014: remote error: tls: bad certificate `

It can be fix by bundle `ca cert` for `MutatingWebhookConfiguration ` and `MutatingWebhookConfiguration ` like :
```yaml
{{- if  and (.Values.admissionWebhooks.enabled) (not .Values.admissionWebhooks.certManager.enabled) }} 👈
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/name: opentelemetry-operator
  name: {{ template "opentelemetry-operator.name" . }}-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle:  "xxxxxxxx" 👈
      service:
        name: {{ template "opentelemetry-operator.name" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-opentelemetry-io-v1alpha1-instrumentation
```
