### ISSUE TITLE
Cannot expose OTLP service using Istio 

### ISSUE THREAD

**Issue by nguyenhoaibao** [open-telemetry/opentelemetry-helm-charts#356]
Currently the opentelemetry-collector Helm chart has a pre-configured ports like [this](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml#L178-L181):
```
ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
# some other ports
```
that makes the installed service has a port name `otlp` and port number set to `4317`.

Now I want to expose that service using Istio. Since that 4317 port is a GRPC service and Istio has a [protocol selection](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/) so the service port name must be in `grpc[-<suffix>]` format. But if I set a port name `grpc` in a new values file like this:

```
# production-values.yaml
ports:
  grpc:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
```
and install using this command:
```
helm install opentelemetry-collector ./opentelemetry-collector-0.30.0.tgz --values production-values.yaml
```
it produces this error:
```
Error: INSTALLATION FAILED: Service "opentelemetry-collector" is invalid: spec.ports[4]: Duplicate value: core.ServicePort{Name:"", Protocol:"TCP", AppProtocol:(*string)(nil), Port:4317, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:""}, NodePort:0}
```

That error is because Helm tries to merge `ports` variable automatically together, so port `4317` is duplicated in the Kubernetes Service.

One possible solution is I can untar the Helm chart and edit its pre-configured values manually, then track all those files to Git, but we don't want to do that because that makes Git has to track multiple files, while a single tgz file is easier to track and review and upgrade later.

Another solution I want to propose is can we update the Kubernetes Service to have the `appProtocol` field, so it can work with Istio protocol selection?

**Comment by TylerHelmuth** [comment]
@nguyenhoaibao in your values.yaml you can do either

```yaml
ports:
  otlp:
    enabled: false
  grpc-otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
```
or 

```yaml
ports
  otlp: null
  grpc-otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
```

to update the name.  Let me know if that works.
