### ISSUE TITLE
Error message while deploying opentelemetry-operator with flux

### ISSUE THREAD

**Issue by adomenech73** [open-telemetry/opentelemetry-helm-charts#360]
I'm trying to deploy `opentelemetry-operator` using flux and I always come to the point of receiving some error messages:

```
Helm install failed: rendered manifests contain a resource that already exists. 
Unable to continue with install: ClusterRole "opentelemetry-operator-manager-role" in namespace "" exists and cannot be imported into the current release: 
invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "observability": current value is "opentelemetry-operator-system"
``` 

I'm probably missing something but I tried to to add the annotation the message points and still getting the same message, then I disabled the clusterRole creation with `clusterRole.create: false` and then I got another error message:

```
Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install:
MutatingWebhookConfiguration "opentelemetry-operator-mutating-webhook-configuration" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: 
key "meta.helm.sh/release-namespace" must equal "observability": current value is "opentelemetry-operator-system"
```
I finally also disabled the `admissionWebhooks` and seems that finally I got the HelmRelease reconciled but my guess is that there is something wrong with this prune approach as this elements seem to be necessary and should be created and reinstalled anytime.  My impression is that they are created first time and then raise errors whenever the helm-controller tries to apply them again.

My helmRelease definitions now looks like this:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: observability
  annotations:
    "meta.helm.sh/release-namespace": "observability"
spec:
  releaseName: opentelemetry-operator
  chart:
    spec:
      chart: opentelemetry-operator
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
      version: 0.11.9
  interval: 10m
  values:
    admissionWebhooks:
      enabled: false 
    clusterRole:
      create: false
    prometheusRule:
      enabled: true
      defaultRules:
        enabled: true
```
Any help would be much appreciated
