### ISSUE TITLE
[opentelemetry-collector] statefulset mode can't be started

### ISSUE THREAD

**Issue by sherifkayad** [open-telemetry/opentelemetry-helm-charts#368]
Currently we are facing the following two issues with the `statefulset` mode:

- **First Issue:** The `volumeClaimTemplates` isn't taken into consideration (not created with the StatefulSet object) .. Our Yaml config is as follows:
```yaml
statefulset:
  # volumeClaimTemplates for a statefulset
  volumeClaimTemplates:
  - metadata:
      name: opentelemetry-collector-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  podManagementPolicy: "Parallel"
```

After some investigation I think the error is here in the StatefulSet Template:
```yaml
  {{- if .Values.statefulset.volumeClaimTemplates }}
  {{- .Values.volumeClaimTemplates | toYaml | indent 2}}
  {{- end }}
```
That should be something like:
```yaml
  {{- if .Values.statefulset.volumeClaimTemplates }}
  volumeClaimTemplates:
  {{- .Values.volumeClaimTemplates | toYaml | indent 2}}
  {{- end }}
```

- **Second issue:** We are getting `create Pod opentelemetry-collector-0 in StatefulSet opentelemetry-collector failed error: Pod "opentelemetry-collector-0" is invalid: spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: Invalid value: "kubernetes.io/hostname null": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName', or 'my.name', or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')` .. Looking at the generated object,  I found: `topologyKey: kubernetes.io/hostname  null` was the generated topology key

Our Yaml config for the affinitiy (BTW the same config works like a charm in the `deployment` mode!):
```yaml
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: opentelemetry-collector
        topologyKey: kubernetes.io/hostname
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: opentelemetry-collector
          topologyKey: failure-domain.beta.kubernetes.io/zone
```
