### ISSUE TITLE
Add option to set the nodePort mapping.

### ISSUE THREAD

**Issue by ydan287** [open-telemetry/opentelemetry-helm-charts#380]
When choosing NodePort kind, the port exposed is randomized from a range. in some runtimes (Kind for example) you need to explicitly do port forwarding:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # port forward 30080 on the host to 30080 on this node
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
- role: worker
```

This is impossible if the nodePort cannot be predetermined.

**Comment by TylerHelmuth** [comment]
@ydan287 are you referring to the opentelemetry-collector chart's `ports` section?

```yaml
# Configuration for ports
ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP
  jaeger-compact:
    enabled: true
    containerPort: 6831
    servicePort: 6831
    hostPort: 6831
    protocol: UDP
  jaeger-thrift:
    enabled: true
    containerPort: 14268
    servicePort: 14268
    hostPort: 14268
    protocol: TCP
  jaeger-grpc:
    enabled: true
    containerPort: 14250
    servicePort: 14250
    hostPort: 14250
    protocol: TCP
  zipkin:
    enabled: true
    containerPort: 9411
    servicePort: 9411
    hostPort: 9411
    protocol: TCP
  metrics:
    # The metrics port is disabled by default. However you need to enable the port
    # in order to use the ServiceMonitor (serviceMonitor.enabled) or PodMonitor (podMonitor.enabled).
    enabled: false
    containerPort: 8888
    servicePort: 8888
    protocol: TCP
```

You would like to specify nodePort as well?
