### ISSUE TITLE
Add Kubernetes attributes processor preset

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-helm-charts#389]
I think it would make a lot of sense to add k8sattributes procssor as another Preset. Especially combined with logs collection, where we can enhance the data with Resource attributes such as StatefulSet, Deployment name, etc. 

What do you think?

UX could be something like:
```
presets:
  kubernetesAttributeProcessor:
    enabled: false
```

Example configuration we could generate:
```
    k8sattributes:
      passthrough: false
      pod_association:
      - sources:
        - from: resource_attribute
          name: k8s.pod.ip
      - sources:
        - from: resource_attribute
          name: k8s.pod.uid
      - sources:
        - from: connection
      extract:
        metadata: 
          - "k8s.namespace.name"
          - "k8s.deployment.name"
          - "k8s.statefulset.name"
          - "k8s.daemonset.name"
          - "k8s.cronjob.name"
          - "k8s.job.name"
```
