### ISSUE TITLE
Config overide issues

### ISSUE THREAD

**Issue by jklaw90** [open-telemetry/opentelemetry-helm-charts#45]
When running the agent and collecctor i've been seeing configs.
it maybe related null values when rendering the config to the configmap.  output from just enabling the agent and collector without touching any config:
```
receivers:
  ...
  otlp:
    protocols: {}
```
it seems to be missing `grpc:`
