### ISSUE TITLE
logsCollection storage extension

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-helm-charts#508]
What do you think if we configure `storage` extension for the filelog receiver using logsCollection preset?

Then we would  set up the `file_storage` extension for it?

As I understand it stores the last file offsets to a file.

Something like:
```
extensions:
  file_storage:
    directory: /var/log/pods/
receivers:
  filelog:
    include: [ /var/log/pods/*/*/*.log ]
    ...
    storage: file_storages
```

Though there is one question - where do we store offsets db?
