### ISSUE TITLE
Enable "env" configuration for jaeger deployment

### ISSUE THREAD

**Issue by tglanz** [open-telemetry/opentelemetry-helm-charts#515]
I'd like to use an ElasticSearch cluster as a storage backend for Jaeger. For this I need to set some environment variables in Jaeger's containers. Some of the variables should be taken from the k8s cluster's secrets so it would be ideal to have an option configuring something like

```yaml
jaeger:
  env:
  - name: ELASTIC_USERNAME
     valueFrom:
       secretKeyRef:
         name: elastic-credentials
         key: username
  - name: ELASTIC_PASSWORD
     valueFrom:
       secretKeyRef:
         name: elastic-credentials
         key: password
```
