### ISSUE TITLE
Automatically create service to expose otel-collector when deployed in daemonset mode

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-helm-charts#524]
Hello all,

When installing the [OpenTelemetry Demo Helm Chart](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-demo) we have the option to change the mode of the collector deployment.
If we use the following `values.yaml` to override the default:
```
opentelemetry-collector:
  nameOverride: otelcol
  mode: daemonset
```
The chart is installed successfully, but the collector is not exposed via k8s service, hence it's not reachable for the other apps.
In order to make it work, I had to manually create the service to expose the collector agent pods.

Would it be possible to automate this service creation within the Helm chart, based on the mode the user chooses?

**Comment by TylerHelmuth** [comment]
@julianocosta89 normally when the collector is deployed as a daemonset the services running on the same node push the data to the node's IP to reach the collector. This ensures that within the collector the traces are able to be correlated with the pod metrics and metadata.

Would that solution work for you?

**Comment by julianocosta89** [comment]
Oh true, that makes sense.
That would work, but that would still require some adjustments in the Helm chart, right?

**Comment by TylerHelmuth** [comment]
The collector helm chart can support the node ip pattern already. Do you mean the demo chart?

**Comment by julianocosta89** [comment]
> The collector helm chart can support the node ip pattern already. Do you mean the demo chart?

Yes, because just changing the deployment mode to daemonset it didn't work.
That's why I've suggested creating the service.

**Comment by puckpuck** [comment]
The existing chart can make this work but requires the demo components to be set up to send their OTLP data to the local node instead. The Helm chart components, when using default env, will get an environment variable called `K8S_OTEL_NODE_NAME`. You can set up the components to use this variable like this (not tested):

```
components:
  adService:
    envOverrides: 
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://${K8S_OTEL_NODE_NAME}:4317
```

You would need to repeat the above for each demo component, noting some demo components are looking to send data to the non-GRPC port (4318).

**Comment by julianocosta89** [comment]
Thanks again @TylerHelmuth and @puckpuck !

**Comment by julianocosta89** [comment]
Just for out of completeness, the suggested solution didn't quite work in an EKS cluster.
For some reason, the pods were not able to reach the node by its nodeName.

But I've followed the same approach and used the following:
```
default:
  envOverrides:
    - name: OTEL_K8S_NODE_INTERNAL_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP

components:
  adService:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://$(OTEL_K8S_NODE_INTERNAL_IP):4317
  cartService:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://$(OTEL_K8S_NODE_INTERNAL_IP):4317
  [...]
  emailService:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://$(OTEL_K8S_NODE_INTERNAL_IP):4317
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: http://$(OTEL_K8S_NODE_INTERNAL_IP):4318/v1/traces
```
