### ISSUE TITLE
[opentelemetry-collector] TracesExporter info logs not showing up in container. 

### ISSUE THREAD

**Issue by seany89** [open-telemetry/opentelemetry-helm-charts#538]
On Chart version `opentelemetry-collector-0.40.7` APP verison `0.66.0`
Since upgrading to the latest chart for the collector I no longer see TraceExporter logs in the container. 

I see metrics logging 

`2022-12-05T11:49:50.398Z	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 25}`

On the previous version chart `opentelemetry-collector-0.7.1` App Version `0.37.1` i would see logs on the collector to confirm it is receiving traces.

`2022-12-05T11:47:28.326Z	INFO	loggingexporter/logging_exporter.go:41	TracesExporter	{"#spans": 1}`

  Is there anything I missing here, so TracesExporter logs show up in the container?

Current config map

```
Data
====
relay:
----
exporters:
  jaeger:
    endpoint: <jaeger-endpoint>
  logging: {}
extensions:
  health_check: {}
  memory_ballast:
    size_in_percentage: 40
processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_mib: 1500
    spike_limit_mib: 512
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector
        scrape_interval: 10s
        static_configs:
        - targets:
          - ${MY_POD_IP}:8888
  zipkin:
    endpoint: 0.0.0.0:9411
service:
  extensions:
  - health_check
  pipelines:
    logs:
      exporters:
      - logging
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
    metrics:
      exporters:
      - logging
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
      - prometheus
    traces:
      exporters:
      - logging
      - jaeger
      processors:
      - memory_limiter
      receivers:
      - otlp
  telemetry:
    metrics:
      address: 0.0.0.0:8888
      ```
