### ISSUE TITLE
Deployment daemonset failed due to failed to create "memory_limiter" processor, permission denied

### ISSUE THREAD

**Issue by wadexu007** [open-telemetry/opentelemetry-helm-charts#543]
Issue Summary:
Deployment daemonset failed due to failed to create "memory_limiter" processor, permission denied when enable hostMetrics.

On env: 
- Chart version opentelemetry-collector-0.40.7 
- APP verison 0.66.0
- GKE 1.22
- Helm v3.5.0

Steps to reproduce:

1. vim test.yaml 

```
fullnameOverride: "otel-collector-ds"

mode: daemonset

presets:
  hostMetrics:
    enabled: true

```

2. `helm install otel-collector  open-telemetry/opentelemetry-collector -f test.yaml`
3. otel-collector pods `CrashLoopBackOff`
4. check pod logs
```
Error: cannot build pipelines: failed to create "memory_limiter" processor, in pipeline "logs": failed to get total memory, use fixed memory settings (limit_mib): open /hostfs/var/lib/docker/overlay2/32e749532f5c2cb81779c4079637174f93b3a18c3220638fa7a43078d0360859/merged/sys/fs/cgroup/memory/memory.limit_in_bytes: permission denied
2022-12-07 09:15:09.499024 I | collector server run finished with error: cannot build pipelines: failed to create "memory_limiter" processor, in pipeline "logs": failed to get total memory, use fixed memory settings (limit_mib): open /hostfs/var/lib/docker/overlay2/32e749532f5c2cb81779c4079637174f93b3a18c3220638fa7a43078d0360859/merged/sys/fs/cgroup/memory/memory.limit_in_bytes: permission denied
```

Workaround is set a fix value for memory_limiter - `limit_mib`
```
config:
  processors:
    memory_limiter:
      check_interval: 5s
      limit_mib: 1600
      spike_limit_mib: 500
```

Can you help to take a look at this issue?

Thanks
