### ISSUE TITLE
Collector Chart for Google Cloud Exporter

### ISSUE THREAD

**Issue by tatashidayat** [open-telemetry/opentelemetry-helm-charts#590]
Hi guys,
I'm trying to deploy OpenTelemetry Collector using Helm.
I've tried the `deployment` by following the example chart.
```yaml
mode: deployment

ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false

config:
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
  exporters:
    logging:
      verbosity: "detailed"
    googlecloud:
      retry_on_failure:
        enabled: false
      log:
        default_log_name: opentelemetry.io/collector-exported-log
  processors:
    memory_limiter:
      check_interval: 1s
      limit_percentage: 65
      spike_limit_percentage: 20
    batch: {}
    resourcedetection:
      detectors: [gcp]
      timeout: 10s
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [logging,googlecloud]
      metrics:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [logging,googlecloud]
      logs:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [logging,googlecloud]
```

But I get difficulties putting the service account JSON for google cloud exporter.
I did this for docker:
`docker run --volume "$(pwd)/cloud-trace-sa.json:/etc/otel/key.json" --volume "$(pwd)/config.yaml:/etc/otelcol-contrib/config.yaml" --env GOOGLE_APPLICATION_CREDENTIALS=/etc/otel/key.json -p 4317:4317 -p 4318:4318 -p 55681:55681 --rm otel/opentelemetry-collector-contrib`

Did you guys know how to put the service account?

**Comment by TylerHelmuth** [comment]
@tatashidayat I am not totally following your question.  Does the Google Cloud Exporter require a secret stored in an env var called `GOOGLE_APPLICATION_CREDENTIALS` and you're wondering how to set that secret and make it accessible with a k8s deployment?

**Comment by tatashidayat** [comment]
@TylerHelmuth Google Cloud Exporter use env called `GOOGLE_APPLICATION_CREDENTIALS` to get the service account file path. My question is how set that ENV and put my service account json into the container path.

**Comment by TylerHelmuth** [comment]
@tatashidayat you can use the `extraEnvs` field in the values.yaml to set environment variables.

**Comment by tatashidayat** [comment]
That's nice @TylerHelmuth, how about put my service account (as a json file) into the container?
I wonder if we can mount a file from a secret

**Comment by TylerHelmuth** [comment]
@tatashidayat you can use `extraVolumes` and `extraVolumeMounts` to add secrets

**Comment by tatashidayat** [comment]
Thanks @TylerHelmuth, It works by adding:
```yaml
extraVolumes:
  - name: secret-mount
    secret: 
      secretName: otel-gcloud-sa
      optional: false

extraVolumeMounts:
  - name: secret-mount
    mountPath: /etc/otel

extraEnvs:
- name: GOOGLE_APPLICATION_CREDENTIALS
  value: /etc/otel/creds
```
