### ISSUE TITLE
Potential fixes for datadog exporter (very long initialization)

### ISSUE THREAD

**Issue by kedare** [open-telemetry/opentelemetry-helm-charts#592]
Hello.

This follows issue #591 

After doing more investigation, it looks like the datadog agent is sometime (depending on where you are hosted) taking more than 1 minute to initialize. blocking the readiness/liveness probes until that

See: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16442 

Right now there is no way to use the current chart in this case, there are potential fixes:

- Allow to specify custom timeouts for liveness/readiness probes.

- Allow to pass custom environment variables, this would allow to setup a workaround to force the hostname based on kubernetes attributes instead of the potentially long datadog hostname detection, to refer it in the configuration file

Example of custom environment variable that would be needed
```
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```

To be referred in the configuration file as
```yaml
config:
  exporters:
    datadog:
      host_metadata:
        hostname: "${env:NODE_NAME}"
```

Ideally both options should be possible.

Thanks

**Comment by TylerHelmuth** [comment]
@kedare does this work for you?

```yaml
mode: deployment

config:
  exporters:
    datadog:
      host_metadata:
        hostname: "${NODE_NAME}"
  service:
    pipelines:
      traces:
        exporters:
          - datadog
          - logging

extraEnvs:
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName 
```
