### ISSUE TITLE
Datadog exporter does not run

### ISSUE THREAD

**Issue by adriangb** [open-telemetry/opentelemetry-helm-charts#60]
I'm posting this here because I think the issue is specific to running the helm chart, not a problem with the Datadog exporter in general. Please let me know if this is not the case and I can post this is the collector contrib repo.

When I run the image directly:

```
docker run -p 4317:4317 \
    -v $PWD/otel-collector-config.yaml:/etc/otel-collector-config.yaml \
    otel/opentelemetry-collector-contrib:0.30.0 \
    --config=/etc/otel-collector-config.yaml
```

Where `otel-collector-config.yaml` looks like:

```yaml
receivers:
    otlp:
        protocols:
            http:
exporters:
    datadog:
        service: test
        env: test
        version: 0.0.0
        api:
            key: "..."
processors:
    batch:
        timeout: 10s
service:
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [datadog]
            processors: [batch]
```

I see:

```
info    utils/api.go:32 Validating API key.     {"kind": "exporter", "name": "datadog"}
info    utils/api.go:39 API key validation successful.  {"kind": "exporter", "name": "datadog"}
...
info    builder/exporters_builder.go:98 Exporter started.       {"kind": "exporter", "name": "datadog"}
```

And everything works as expected.

However if I use this helm chart:

```
helm install opentelemetry-collector open-telemetry/opentelemetry-collector --values opentelemetry-collector.yaml
```

Where `opentelemetry-collector.yaml` looks like:

```yaml
agentCollector:
  enabled: false

standaloneCollector:
  enabled: true

image:
  repository: otel/opentelemetry-collector-contrib
  pullPolicy: IfNotPresent
  tag: "0.30.0"

command:
  name: otelcontribcol

config:
  receivers:
    otlp:
      protocols:
        http:

  processors:
    batch:
      timeout: 10s

  exporters:
    datadog:
      service: test
      env: test
      version: 0.0.0
      api:
        key: "..."

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
```

I see:

```
info    builder/exporters_builder.go:98    Exporter started.    {"kind": "exporter", "name": "datadog"}
```

But I don't see the other messages about verifying the API key.

And if I send over traces, I see them being logged (if I enable the logger exporter ad debug level):

```
Span #57                                                                                                                                                                                                                
     Trace ID       : 12055027ec737720c79be4a66b1e8672
     Parent ID      : 1363f0dfbd1f4d41
     ...
```

But nothing is being exported to Datadog.
So it seems like the Datadog exporter is not starting up correctly.
