### ISSUE TITLE
[collector] Unable to remove CPU limits when used as a subchart

### ISSUE THREAD

**Issue by verejoel** [open-telemetry/opentelemetry-helm-charts#644]
Using this chart forces one to set a CPU limit due to it not being possible to remove the default keys.

As an example, say I want to have 1 core of cpu requests, but not set a limit. If my values are
```
# values.yaml
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: null
      memory: 4Gi
```
this yields the generated manifest:
```
# manifest.yaml
          resources:
            limits:
              cpu: 256m
              memory: 4Gi
            requests:
              cpu: 1000m
              memory: 1Gi
```
i.e., the CPU limit is populated by the default value.

This is a known bug in helm: https://github.com/helm/helm/issues/5184

Can we please comment out the default resources in the value file and leave them as an example?

**Comment by TylerHelmuth** [comment]
@verejoel what version of helm are you using?  When install

```yaml
mode: daemonset
resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: null
      memory: 4Gi
```

I get

```yaml
    Limits:
      memory:  4Gi
    Requests:
      cpu:      1
      memory:   1Gi
```

Are you by any chance using the collector chart as a subchart?

**Comment by verejoel** [comment]
Yes it's deployed as a sub-chart, the chart manifest is:
```
apiVersion: v2
name: collector
version: 1.0.0
description: A Helm chart for deploying Open Telemetry collector as a deployment
type: application
dependencies:
  - name: opentelemetry-collector
    alias: collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.43.5
```
Is there a strong reason why the chart should explicitly set resource requests/limits? These are almost guaranteed to be different for every particular use-case and require some configuration from the user. The common practice seems to be to set the resources key to an empty map in the chart definition, and let the user decide.
