### ISSUE TITLE
Permissions Issue when using Persistence with EBS Volumes

### ISSUE THREAD

**Issue by sherifkayad** [open-telemetry/opentelemetry-helm-charts#650]
Just wanted to point this out in an issue and potentially submit a PR to document it in the Chart Values that are using EBS volumes / anything permissions-limiting for persistence would highly likely produce an error like below:
```bash
Error: cannot start pipelines: open /var/lib/storage/otc/exporter_zipkin__traces: permission denied; failed to shutdown pipelines: no existing monitoring routine is running

collector server run finished with error: cannot start pipelines: open /var/lib/storage/otc/exporter_zipkin__traces: permission denied; failed to shutdown pipelines: no existing monitoring routine is running
``` 

I think the error is due to the fact that the OTLP container by default is using user `10001` and thus get this permissions denied error.

The solution I have is basically using an `InitContainer` that can handle the filesystem ownership change to our guy (`10001`).

```yaml
# List of init container specs, e.g. for copying a binary to be executed as a lifecycle hook.
initContainers:
  - name: init-fs
    image: busybox:1.36
    command:
      - sh
      - '-c'
      - 'chown -R 10001: /var/lib/storage/otc'
    volumeMounts:
      - name: opentelemetry-collector-data
        mountPath: /var/lib/storage/otc
```
