### ISSUE TITLE
[Demo] Add support for env from secrets

### ISSUE THREAD

**Issue by cfallwell** [open-telemetry/opentelemetry-helm-charts#663]
Chart: opentelemetry-demo

As a user, I want to reference stored secrets for certain env vars which may contain sensitive endpoints such as cloud-hosted endpoints for trace ingest so that they are not leaked in public repositories.

Idea: Add support for envFrom:

Is your feature request related to a problem?

Yes, when referencing stored secrets...
Helm install failed: values don't meet the specifications of the schema(s) in the following chart(s): opentelemetry-demo:

default: Additional property envFrom is not allowed
Describe the solution you'd like:

Ability to utilize the following in Helm values override
envFrom:
- secretRef:
name:{{some secret ref}}

**Comment by puckpuck** [comment]
The demo already supports specifying secrets for individual environment variables using the `valueFrom` property of any given variable. Can you use this to specify the sensitive endpoints instead of using an `envFrom` construct?

```
env:
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: my-secret
        key: my-otel-endpoint
```
