### ISSUE TITLE
Kafka metrics not working due to env=false

### ISSUE THREAD

**Issue by rcastley** [open-telemetry/opentelemetry-helm-charts#691]
Hi,

In the `values.yaml` file for the Kafka component it is currently set to:

```
  kafka:
    enabled: true
    useDefault:
      env: false
```

This generates an error in the Kafka logs as it won't pick up `OTEL_COLLECTOR_NAME`. IMHO, `env` should be set to `true`.

Many thanks :-)
