### ISSUE TITLE
Allow overriding the repository for controller.opentelemetry without setting the image tag

### ISSUE THREAD

**Issue by patst** [open-telemetry/opentelemetry-helm-charts#694]
Hey there,

I am trying to get the OpenTelemetry integration running and I am using the helm chart.

I cannot use public container registries directly, but have a cache container registry in between.

Having the definitation of an image like this:
```yaml
controller:
    opentelemetry:
        image: registry.k8s.io/ingress-nginx/opentelemetry:v20230312-helm-chart-4.5.2-28-g66a760794@sha256:40f766ac4a9832f36f217bb0e98d44c8d38faeccbfe861fbc1a76af7e9ab257f
```
(see  https://github.com/kubernetes/ingress-nginx/blob/e4a66fd2f625de3bcc7aaa793b31f529a0662009/charts/ingress-nginx/values.yaml#LL541C9-L541C9 ) is inconvenient for me, since I can only overwrite the complete key and have to worry about updating the tag and sha values from there on.

The other places in the helm chart reference images like this:
```yaml
controller:
    opentelemetry:
        image:
            registry: registry.k8s.io # can but my private registry here
            image: ingress-nginx/opentelemetry
            tag: "v20230312-helm-chart-4.5.2-28-g66a760794"
            digest: sha256:40f766ac4a9832f36f217bb0e98d44c8d38faeccbfe861fbc1a76af7e9ab257f
```
This allows me just to change the registry value to point to my private one.

Maybe it would be possible to change the reference, wdyt?
