### ISSUE TITLE
imagePullSecrets on the collector image

### ISSUE THREAD

**Issue by pseymournutanix** [open-telemetry/opentelemetry-helm-charts#696]
Hello,

The helm chart now allows `imagePullSecrets` for the operator image, but this doesn't fall into the collector (unless I am missing something).

Perhaps it would be easier to add them to the service accounts if set in `.Values.imagePullSecrets`

**Comment by Allex1** [comment]
@pseymournutanix That's a good point and we are aware of it. As we don't actually deploy the cr as part of this chart we should at least update the examples. Can you help with that? 
Thanks

**Comment by sreejesh-radhakrishnan-db** [comment]
I am following https://opentelemetry.io/docs/k8s-operator/automatic/#create-an-opentelemetry-collector-optional  and my deployment is failing for same reason.  as its private reg for image. 

I can see deployment this is the service account used.,  are you saying we should add this serviceAccount with a imagePullSecret ? 

       serviceAccount: care-optl-collector
      serviceAccountName: care-optl-collector

**Comment by sreejesh-radhakrishnan-db** [comment]
@pseymournutanix did you make it work? please give some pointers if the case.

**Comment by TylerHelmuth** [comment]
The OpenTelemetryCollector object does let you specify a image pull policy.  Using https://opentelemetry.io/docs/k8s-operator/automatic/#create-an-opentelemetry-collector-optional as the starting point, I believe you can do


```
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: demo
spec:
  imagePullPolicy: THE_VALUE_YOU_WANT
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]
EOF
```

And it will use that value in the deployment it makes for the collector.

Since this object is created outside the opentelemetry-operator chart the chart cannot be used to set this value.  I believe this is another reason to look at https://github.com/open-telemetry/opentelemetry-helm-charts/issues/562 and https://github.com/open-telemetry/opentelemetry-helm-charts/issues/69
