### ISSUE TITLE
Support configuring and disabling healthcheck extension

### ISSUE THREAD

**Issue by jsirianni** [open-telemetry/opentelemetry-helm-charts#697]
The healthcheck probes are configured like this, without customization options.

```yaml
    livenessProbe:
      httpGet:
        path: /
        port: 13133
    readinessProbe:
      httpGet:
        path: /
        port: 13133
```

I would like the following options
- ability to change path, port
- ability to set other options like `periodSeconds`
- ability to disable healthcheck extension all together.

While I agree that generally healthcheck extension + healthcheck probes should always be in use, I do think this should be up to the user. I think defaulting to the current configuration (enabled with sane defaults) is great.

I would be willing to take on this work if the community agrees.
