### ISSUE TITLE
Question: Export to Dynatrace

### ISSUE THREAD

**Issue by coffeebe4code** [open-telemetry/opentelemetry-helm-charts#698]
I'm not seeing any documentation for being able to take this collector data and export it to some other ingestor like dynatrace. 

Could someone provide me with that documentation?

I apologize that this seems like such a simple question. but I must be blind.

**Comment by puckpuck** [comment]
The chart has a `config` parameter that takes an OpenTelemetry config object. In this, you can specify a dynatrace exporter and include it in one or more pipelines. Because Helm will merge values, whatever you specify will be merged with the config that the Helm chart provides.

You would pass something like this into the `--values` option when installing the chart.

```yaml
config:
  exporters:
    dynatrace:
      # options for dynatrace exporter go here
      
  services:
    pipelines:
      traces:
        exporters: [dynatrace]
      # add other pipelines here as well if needed.
```
