### ISSUE TITLE
[collector] How to use external secrets to for secret mounts.

### ISSUE THREAD

**Issue by indreek** [open-telemetry/opentelemetry-helm-charts#775]
Hello

Looking for guidance. Trying to keep my git clean and secure. And i would like to use secrets for otlp receivers.

What would be the best way to include external secrets (example from Hashicorp vault) into open-telemetry collector secretMounts?
https://github.com/open-telemetry/opentelemetry-helm-charts/pull/765 

As far as i know there are two options:
1) Separate helm for secrets - Using tools like ArgoCD items will be in different projects. No single overview.
2) Wrapper helm chart - downside is that i need to monitor parent chart for updates and update my own chart for this.

Thanks,
Indrek

**Comment by indreek** [comment]
Your tool provisions the secrets .... what tool do you mean? Getting secrets into collector is not an issue. "Creating the secret itself" is the issue.

**Comment by indreek** [comment]
I added option to chart to create extraObjects. https://github.com/open-telemetry/opentelemetry-helm-charts/pull/765/commits/7e6f57de09abc3c8b9d47a90002c1d6d802b7c57 

Because I use ArgoCD and in order to have overview, they must be in same Helm chart. Other option would have been to make wrapper chart, but it adds regular chart maintenance task on every chart release.

**Comment by indreek** [comment]
Yes, I could work with something like this. It would need some modification, but in general yes. I use external-secrets. Would something like this be accepted?

**Comment by indreek** [comment]
@TylerHelmuth Like this. I can even make my git public. You still wouldn't get anything out of it.


With help of https://external-secrets.io/ i can define in my helm chart values:
```
extraObjects:
  - apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: opentelemetry-collector-tls
    spec:
      target:
        creationPolicy: 'Owner'
      data:
        - secretKey: tls.pem
          remoteRef:
            key: secrets/tools/opentelemetry
            property: opentelemetry-collector-tls
      refreshInterval: 1h
      secretStoreRef:
        kind: ClusterSecretStore
        name: vault-backend
```

**Comment by TylerHelmuth** [comment]
We have a [specific rule](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector#crds) for templates that depend on external CRDs and right now it is only Prometheus since OTel has promises to keep with Prometheus compatibility.  In general it is best if the chart includes everything it needs it order to install.

**Comment by mirzaprangon** [comment]
I will add notes for reference.

The openapi collector have values as follows:
```yaml
extraEnvsFrom: []
extraVolumes: []
extraVolumeMounts: []
```

Therefore, if you want to use external secret, for example using a secret csi driver, you will just add add the options in these keys. The secretclass for csi will have to be created separately.

This is a very common use case. I will request the team to add a part in the documentation, specially adding `endpoint` and `Authorization` configurations.
