### ISSUE TITLE
request for only repo override

### ISSUE THREAD

**Issue by blackluck** [open-telemetry/opentelemetry-helm-charts#804]
Hello,

it would be nice if in helm chart values could be change only image repository. We local cache/proxy repository and it's much easier to follow upgrades when releases have minimal changes to our helm values. Like image repo mostly not changing, not like image tag.
And it's really a pain in you know where when I don't even know the image versions, but I have to configure that too, otherwise template won't replace repository. I'm talking about opentelemetry operator autoinstrument images, there is knowhere an easily accessible list about image+tag list for java, python, dotnet etc images, but template replace only works if configure both.
So please change template to work when even changing image repo or tag only.

**Comment by TylerHelmuth** [comment]
@blackluck the operator chart does allow changing the auto-instrumentation images by repository or tag individually.

https://github.com/open-telemetry/opentelemetry-helm-charts/blob/28dc76de32b4477dbbaa500e3724b88a6280efa6/charts/opentelemetry-operator/values.yaml#L29-L58

**Comment by blackluck** [comment]
I meant like one of this:

```
  autoInstrumentationImage:
    dotnet:
      repository: "localproxy/ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet"
      tag: ""
    java:
      repository: "localproxy/ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java"
```
so don't configure tag all the time with new releases, just use the same helm values and the helm chart template should handle to fill with release specific tags.

Thanks!
