### ISSUE TITLE
Allow service.enabled=false for deployment

### ISSUE THREAD

**Issue by devurandom** [open-telemetry/opentelemetry-helm-charts#811]
Currently the service is always enabled unless we deploy in "daemonset" mode:
https://github.com/open-telemetry/opentelemetry-helm-charts/blob/fce6cb43c9f2dc164e4cc22d1febeb4ad750b871/charts/opentelemetry-collector/templates/_helpers.tpl#L134-L145

I deploy a OpenTelemetry collector just for scraping Kubernetes cluster data:
```yaml
presets:
  clusterMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true
  kubernetesEvents:
    enabled: true
```

I have all receivers disabled:
```yaml
config:
  receivers:
    otlp: null
    jaeger: null
    zipkin: null
```

As far as I can tell, no ports need to be exposed in this setup. It would be nice if `service.enabled=false` would also disable the service object in this case.
