### ISSUE TITLE
Not able to disable receivers: jaeger, prometheus

### ISSUE THREAD

**Issue by dawidmalina** [open-telemetry/opentelemetry-helm-charts#825]
I am not able to disable receivers that I am not interested in with following configuration (chart: opentelemetry-collector-0.61.2):

```
mode: "deployment"

config:
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
```

Rendered template always looks like this:
```
...
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:14250
          thrift_compact:
            endpoint: ${env:MY_POD_IP}:6831
          thrift_http:
            endpoint: ${env:MY_POD_IP}:14268
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${env:MY_POD_IP}:8888
      zipkin:
        endpoint: ${env:MY_POD_IP}:9411
...
```

The only way is to modify is to provide some values, like:
```
 mode: "deployment"

config:
  receivers:
    jaeger: ''
    prometheus: ''
    zipkin: ''
```

then rendered configuration looks like this (not sure if this is valid):
```
...
    receivers:
      jaeger: ""
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      prometheus: ""
      zipkin: ""
...
```
