### ISSUE TITLE
Feature: Option to turn off memory ballast

### ISSUE THREAD

**Issue by cep21** [open-telemetry/opentelemetry-helm-charts#840]
Due to a potential bug in the ballast, we would like to turn it off entirely.  We're currently setting the value to `1` in our charts. Can this chart be change to either default off or allow configuration that turns off the ballast entirely?

https://github.com/open-telemetry/opentelemetry-collector/issues/7512

**Comment by TylerHelmuth** [comment]
You can remove the ballast extension from the extension list by explicitly list which extensions you want:

```yaml
config:
  service:
    extensions:
      - health_check
```
