### ISSUE TITLE
helm chart upgrade issues

### ISSUE THREAD

**Issue by jacob-bresciani-everbridge** [open-telemetry/opentelemetry-helm-charts#863]
during an upgrade from chart 0.61.2 to latest I've hit the error

```
Error: UPGRADE FAILED: template: opentelemetry-collector/templates/service.yaml:37:28: executing "opentelemetry-collector/templates/service.yaml" at <include "opentelemetry-collector.serviceInternalTrafficPolicy" .>: error calling include: template: opentelemetry-collector/templates/_helpers.tpl:154:44: executing "opentelemetry-collector.serviceInternalTrafficPolicy" at <eq .Values.service.enabled true>: error calling eq: incompatible types for comparison
``` 

I'm deploying the collector as a statefulset so I'm not supposed to be required to explicitly set service.enabled.

To get around this I've enabled it anyway, another deploy attempt and now I hit 

```
Error: UPGRADE FAILED: template: opentelemetry-collector/templates/NOTES.txt:44:42: executing "opentelemetry-collector/templates/NOTES.txt" at <eq .Values.service.internalTrafficPolicy "Cluster">: error calling eq: incompatible types for comparison
```

I'm going to keep attempting to fix this, but either the config in _helpers has some bugs or the documentation in Values.yaml needs updating for new requirements.

For reference this is (most) of my custom values I'm setting.

```
mode: "statefulset"
    
presets:
  logsCollection:
    enabled: false
    includeCollectorLogs: false
    storeCheckpoints: false

config:
  processors:
    batch: {}
    k8sattributes:
      pod_association:
      - sources:
          - from: resource_attribute
            name: k8s.pod.ip
      # below association matches for pair `k8s.pod.name` and `k8s.namespace.name`
      - sources:
          - from: resource_attribute
            name: k8s.pod.name
          - from: resource_attribute
            name: k8s.namespace.name
    # endpoint ignore list
    filter/spans:
      spans:
        exclude:
          match_type: regexp
          attributes:
            - key: http.target
              value: (/ping|/health|/prometheus/metrics)
    # If set to null, will be overridden with values based on k8s resource limits
    memory_limiter: null

    resourcedetection:
      detectors: [gcp]
      timeout: 10s
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${MY_POD_IP}:4317
        http:
          endpoint: ${MY_POD_IP}:4318
    prometheus:
      config:
        scrape_configs:
        - job_name: common
          scheme: http
          scrape_interval: 60s
          scrape_timeout: 30s
          metrics_path: /prometheus
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                names:
                  - myService

  service:
    telemetry:
      metrics:
        address: ${MY_POD_IP}:8888
      # logs:
      #   level: debug
    extensions:
      - health_check
      - memory_ballast
    pipelines:
      logs:
        receivers:
          - otlp
        processors:
          - k8sattributes
          - memory_limiter
          - batch
        exporters:
          - otlphttp/honeycomb
      metrics:
        receivers:
          - otlp
          - prometheus
        processors:
          - resourcedetection
          - k8sattributes
          - memory_limiter
          - batch
        exporters:
          - otlphttp/metrics
      traces:
        receivers:
          - otlp
        processors:
          - k8sattributes
          - memory_limiter
          - batch
          - filter/spans
        exporters:
          - otlphttp/honeycomb
        
image:
  repository: gcr.io/xmatters-eng-mgmt/otel/opentelemetry-collector-contrib
  pullPolicy: IfNotPresent
  tag: "0.76.1"
  # When digest is set to a non-empty value, images will be pulled by digest (regardless of tag value).
  digest: ""

# OpenTelemetry Collector executable
command:
  name: otelcol-contrib
  extraArgs:
    - --config=file:/vault/secrets/honeycomb.yaml
serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: opentelemetry-collector@{{ .Values.global.googleProject }}.iam.gserviceaccount.com
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

clusterRole:
  create: true
  rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    - events
    - namespaces
    - namespaces/status
    - nodes
    - nodes/proxy
    - nodes/spec
    - nodes/metrics
    - pods
    - pods/status
    - replicationcontrollers
    - replicationcontrollers/status
    - resourcequotas
    - services
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - apps
    resources:
    - daemonsets
    - deployments
    - replicasets
    - statefulsets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    resources:
    - daemonsets
    - deployments
    - replicasets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - batch
    resources:
    - jobs
    - cronjobs
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - autoscaling
    resources:
    - horizontalpodautoscalers
    verbs:
    - get
    - list
    - watch

resources:
  requests:
    cpu: 256m
    memory: 2048Mi
  limits:
    cpu: 512m
    memory: 3072Mi

podAnnotations: 
  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  vault.hashicorp.com/auth-type: gcp
  vault.hashicorp.com/auth-path: auth/gcp
  vault.hashicorp.com/auth-config-type: gce
  vault.hashicorp.com/role: "opentelemetry-{{ .Values.global.environment }}"
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-pre-populate-only: "true"
  vault.hashicorp.com/preserve-secret-case: "true"
  vault.hashicorp.com/agent-inject-secret-honeycomb.yaml: "secrets/opentelemetry/{{ .Values.global.environment }}/honeycomb"
  # the old otlp/metrics and otlp/honeycomb endpoint was `api.honeycomb.io:443`
  vault.hashicorp.com/agent-inject-template-honeycomb.yaml: |
    {{`{{- with secret "secrets/opentelemetry/`}}{{ .Values.global.environment }}{{`/honeycomb" -}}
    exporters:
      otlphttp/honeycomb:
        endpoint: {{ .Data.data.endpoint }}
        headers:
          x-honeycomb-team: {{ .Data.data.apikey }}
      otlphttp/metrics:
        endpoint: {{ .Data.data.endpoint }}
        headers:
          x-honeycomb-dataset: kubernetes_metrics
          x-honeycomb-team: {{ .Data.data.apikey }}
    {{- end }}`}}

service:
  enabled: true
  type: ClusterIP
  annotations:
    consul.hashicorp.com/service-name: otel-collector
    consul.hashicorp.com/service-port: "4317"
    consul.hashicorp.com/service-sync: "true"
    consul.hashicorp.com/service-tags: common
```

**Comment by jacob-bresciani-everbridge** [comment]
I've fixed the second bug, the default for service are

```
service:
  # Enable the creation of a Service.
  # By default, it's enabled on mode != daemonset.
  # However, to enable it on mode = daemonset, its creation must be explicitly enabled
  # enabled: true

  type: ClusterIP
  # type: LoadBalancer
  # loadBalancerIP: 1.2.3.4
  # loadBalancerSourceRanges: []

  # By default, Service of type 'LoadBalancer' will be created setting 'externalTrafficPolicy: Cluster'
  # unless other value is explicitly set.
  # Possible values are Cluster or Local (https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip)
  # externalTrafficPolicy: Cluster

  annotations: {}

  # By default, Service will be created setting 'internalTrafficPolicy: Local' on mode = daemonset
  # unless other value is explicitly set.
  # Setting 'internalTrafficPolicy: Cluster' on a daemonset is not recommended
  # internalTrafficPolicy: Cluster
```

With `mode: statefulset` these no longer work, I had to uncomment `enabled` and `internalTrafficPolicy`

```
mode: statefulset
service:
  enabled: true
  internalTrafficPolicy: Cluster
```
