### ISSUE TITLE
BUG Chart enforces incompatible config options. 

### ISSUE THREAD

**Issue by herrbpl** [open-telemetry/opentelemetry-helm-charts#877]
This in turn leaves colelctor with nonfunctioning config which prevents collector to come up.

Ie, you specify as config part of values.yaml:
```yaml
  receivers:
    otlp:
      protocols:
        grpc:
        http:
    jaeger:
      protocols:
        grpc:
        thrift_binary:
        thrift_compact:
        thrift_http:
    zipkin:
  exporters:  
    otlp/anonymous:
      endpoint: tempo:4317
      tls:
        insecure: false
      headers:
        x-scope-orgid: anonymous
  processors:
    k8sattributes:        
      passthrough: false
      pod_association:
      - sources:
        - from: resource_attribute
          name: k8s.pod.ip
      - sources:
        - from: resource_attribute
          name: k8s.pod.uid
      - sources:
        - from: connection
      extract:
        metadata:
          - "k8s.namespace.name"
          - "k8s.deployment.name"
          - "k8s.statefulset.name"
          - "k8s.daemonset.name"
          - "k8s.cronjob.name"
          - "k8s.job.name"
          - "k8s.node.name"
          - "k8s.pod.name"
          - "k8s.pod.uid"
          - "k8s.pod.start_time"
  service:
    pipelines:
      traces:
        receivers: [otlp, jaeger,zipkin]
        processors: [k8sattributes]
        exporters: **[otlp/anonymous]**
```
and by chart, it gets turned into:
```yaml
    exporters:
      logging: {}
      otlp/anonymous:
        endpoint: tempo:4317
        headers:
          x-scope-orgid: anonymous
        tls:
          insecure: false
    extensions:
      health_check: {}
      memory_ballast:
        size_in_percentage: 40
    processors:
      k8sattributes:
        extract:
          metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.pod.start_time
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    receivers:
      jaeger:
        protocols:
          grpc: {}
          thrift_binary: null
          thrift_compact: {}
          thrift_http: {}
      otlp:
        protocols:
          grpc: {}
          http: {}
      prometheus:
        config: {}
      zipkin: {}
    service:
      pipelines:
        logs: {}
        metrics: {}
        traces:
          exporters:
          - otlp/anonymous
          processors:
          - k8sattributes
          - batch
          receivers:
          - otlp
          - jaeger
          - zipkin
      telemetry:
        metrics: {}
```
This causes collector not to start because of:
```log
Error: invalid configuration: receivers::prometheus: no Prometheus scrape_configs or target_allocator set
2023-08-26T15:30:15.945420398Z 2023/08/26 15:30:15 collector server run finished with error: invalid configuration: receivers::prometheus: no Prometheus scrape_configs or target_allocator set
```

When I remove parts that originally were missing from my provided config:
```yaml
exporters:      
  otlp/anonymous:
    endpoint: tempo:4317
    headers:
      x-scope-orgid: anonymous
    tls:
      insecure: false    
processors:
  k8sattributes:
    extract:
      metadata:
      - k8s.namespace.name
      - k8s.deployment.name
      - k8s.statefulset.name
      - k8s.daemonset.name
      - k8s.cronjob.name
      - k8s.job.name
      - k8s.node.name
      - k8s.pod.name
      - k8s.pod.uid
      - k8s.pod.start_time
    passthrough: false
    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: resource_attribute
        name: k8s.pod.uid
    - sources:
      - from: connection      
receivers:
  jaeger:
    protocols:
      grpc: {}
      thrift_binary: null
      thrift_compact: {}
      thrift_http: {}
  otlp:
    protocols:
      grpc: {}
      http: {}
  zipkin: {}
service:
  pipelines:                
    traces:
      exporters:
      - otlp/anonymous
      processors:
      - k8sattributes        
      receivers:
      - otlp
      - jaeger
      - zipkin      

```

collector starts without issues. 

Do not babysit people, we are capable of providing working config on our own, this is micromanagement (good intentions, no doubt) and is totally unneeded. If there is need to specify default config template, Grafana charts give a good example to chart is using template provided to render default config upon which end user config is merged to.

**Comment by herrbpl** [comment]
Damn, this chart really messes up config you wish to provide to collector. If you remove pipelines you don't want, like logs, metrics etc, chart adds them back with empty config. This will fail config validation by collector and and service won't start. Collector is pretty much unusable unless you go with default config provided by chart.

**Comment by herrbpl** [comment]
This part of README does not work as advertised:

> The Collector's configuration is set via the config section. Default components can be removed with null. Remember that lists in helm are not merged, so if you want to modify any default list you must specify all items, including any default items you want to keep.

>Example: Disable metrics and logging pipelines and non-otlp receivers:

>
```yaml
config:
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
  service:
    pipelines:
      traces:
        receivers:
          - otlp
      metrics: null
      logs: null
```
Pipelines for logs and metrics will still be generated with empty config, failing collector startup checks

**Comment by herrbpl** [comment]
You can remove unwanted pipelines via helm template rendering trick. 
Since logs and metrics are always added back, for example when provisioning as Rancher app, might as well leave them in and have them eliminated from created configmap via unsetting their value prior turning map to yaml.
```yaml
...
service:
    extensions:
      - health_check
      - memory_ballast
    pipelines:      
      logs:
        exporters:
          - logging
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      metrics:
        exporters:
          - logging
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - prometheus    
      traces:
        exporters:
          - logging
        processors:
          - k8sattributes
          - memory_limiter
          - batch{{ $_ := unset .Values.config.service.pipelines "logs" }}{{ $_ := unset .Values.config.service.pipelines "metrics" }}
        receivers:
          - otlp
          - jaeger
          - zipkin
...
```
Too bad one needs to use such tricks to get desired configuration.
