### ISSUE TITLE
Enable logsCollection in Collector for only a subset of pods

### ISSUE THREAD

**Issue by Matthias247** [open-telemetry/opentelemetry-helm-charts#879]
The setting `presets. logsCollection.enabled` will enable log collection for all pods by configuring `filelog.include: [ /var/log/pods/*/*/*.log ]`. For some deployments it is however preferable to collect logs for only a subet of pods. It would be nice if the `include` list could be modified separately from `logsCollection.enabled`.  E.g. allow to specify:

```
presets:
  logsCollection:
    enabled: true
    include: [ /var/log/mynamespace*/*/*/*.log ] # Overwrites the default "include: [ /var/log/pods/*/*/*.log ]"
```

The workaround for this at the moment is to disable `logsCollection` and configure the `filelog` receiver manually. However that also requires to manually configure the k8s log format parsing and the mounting of `varlogpods`which makes things a bit verbose. Directly allowing to specify the path would eliminate the boilerplate.

**Comment by TylerHelmuth** [comment]
@Matthias247 thanks for submitting this issue as this problem has been on my mind recently as well. I definitely want to [make it easier to collect specific logs](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23339).

I agree that manually configuring the filelogreceiver for k8s is boilerplate, and making it easier to configure `include` is helpful. At the same time, we've historically been allergic to any preset configuration that isn't a boolean as the presets are supposed to be extremely opinionated and simple to understand and configure.

If you enable the preset AND configure the filelog receiver in `config` you should be able to get the best of both worlds.  Try something like:

```yaml
mode: daemonset
presets:
  logsCollection:
    enabled: true
config:
  receivers:
    filelog:
      include: [/var/log/mynamespace*/*/*/*.log]
```
