### ISSUE TITLE
podLabels needed in order to deploy

### ISSUE THREAD

**Issue by robertocamp** [open-telemetry/opentelemetry-helm-charts#923]
similar to "Unable to add custom labels to Opentelemetry Collector #862" (you may combine the two issues if that makes sense):

We are unable to deploy the Demo in our environment because we have a requirement that all pods and services have a certain custom label configured (otherwise a webhook prevents the resource from getting deployed).

Can you add this functionality to the Helm chart?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: opentelemetry-demo
    meta.helm.sh/release-namespace: otel-demo
  creationTimestamp: "2023-10-13T21:07:26Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: otelcol
    app.kubernetes.io/version: 0.86.0
    helm.sh/chart: opentelemetry-collector-0.69.1
    custom_label:  value
```
