### ISSUE TITLE
Default configuration not deployable due to misconfigured oltp protocol

### ISSUE THREAD

**Issue by miaucl** [open-telemetry/opentelemetry-helm-charts#94]
I am new to the open telemetry, and was starting to set up an Operator and Collector via helm charts. It is not really a bug, but the default helm chart configuration for Collector **does** specify the protocol "otlp" but provides **no** configuration to it ([here](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/582acccee0dfb91f77b760f7474756b3815738e6/charts/opentelemetry-collector/values.yaml#L25)) resulting in following error when running the container:
```
receiver "otlp" has invalid configuration: must specify at least one protocol when using the OTLP receiver
```

The error is easy to understand and by adding the endpoint values to the "oltp" protocol, everything launches smoothly.
```yaml
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317 # <= Missing
          http:
            endpoint: 0.0.0.0:4318 # <= Missing
```

Adding this default values or removing the "oltp" driver no require this values improves the onboarding and learning process  for newbies like me without having to debug the helm charts first.
