### ISSUE TITLE
[ingress] Issue on the redirection in NGINX ingress

### ISSUE THREAD

**Issue by crisjaytomas** [open-telemetry/opentelemetry-helm-charts#995]
Hi,

Has anyone encountered the issue with regards to redirection? Some static files are not properly loading when placed into a path. Below is my ingress definition:

```
apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  name: my-otel-demo-frontendproxy
  labels:
    helm.sh/chart: opentelemetry-demo-0.27.0
    
    opentelemetry.io/name: my-otel-demo-frontendproxy
    app.kubernetes.io/instance: my-otel-demo
    app.kubernetes.io/component: frontendproxy
    app.kubernetes.io/name: my-otel-demo-frontendproxy
    app.kubernetes.io/version: "1.7.0"
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: Helm
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite_log on;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "agt.otel-demo.net"
      secretName: secret-tls
  rules:
    - host: "agt.otel-demo.net"
      http:
        paths:
          - path: /demo/something(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: my-otel-demo-frontendproxy
                port:
                  number: 8080
```
When I access https://agt.otel-demo.net/demo/something it loads the pages however some static files like images, css and js doesn't load correctly please refer to screenshot below:

![image](https://github.com/open-telemetry/opentelemetry-helm-charts/assets/47767510/1caa4550-91dd-4185-9bc0-a0cba2c26724)
